# Copyright (c) 2018 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from .vulkantypes import *

from copy import deepcopy

import sys, os

class Module(object):
    def __init__(self, directory, basename):
        self.directory = directory
        self.basename = basename

        self.headerPreamble = ""
        self.implPreamble = ""

        self.headerPostamble = ""
        self.implPostamble = ""

        self.headerFileHandle = ""
        self.implFileHandle = ""

    def getMakefileSrcEntry(self):
        return "    " + os.path.join(self.directory, self.basename) + ".cpp \\\n"

    def begin(self, globalDir):
        # Create subdirectory, if needed
        absDir = os.path.join(globalDir, self.directory)

        filename = os.path.join(absDir, self.basename)

        fpHeader = open(filename + ".h", 'w', encoding='utf-8')
        fpImpl = open(filename + ".cpp", 'w', encoding='utf-8')

        self.headerFileHandle = fpHeader
        self.implFileHandle = fpImpl

        self.headerFileHandle.write("// Module: %s (header) Autogenerated by CerealGenerator\n" % self.basename)
        self.implFileHandle.write("// Module: %s (impl) Autogenerated by CerealGenerator\n" % self.basename)

        self.headerFileHandle.write(self.headerPreamble)
        self.implFileHandle.write(self.implPreamble)

    def appendHeader(self, toAppend):
        self.headerFileHandle.write(toAppend)

    def appendImpl(self, toAppend):
        self.implFileHandle.write(toAppend)

    def end(self):
        self.headerFileHandle.write(self.headerPreamble)
        self.implFileHandle.write(self.implPreamble)

        self.headerFileHandle.close()
        self.implFileHandle.close()

class CodeGen(object):
    def __init__(self,):
        self.code = ""
        self.indentLevel = 0

    def swapCode(self,):
        res = "%s" % self.code
        self.code = ""
        return res

    def indent(self,):
        return "".join("    " * self.indentLevel)

    def beginBlock(self,):
        self.code += self.indent() + "{\n"
        self.indentLevel += 1

    def endBlock(self,):
        self.indentLevel -= 1
        self.code += self.indent() + "}\n"

    def beginIf(self, cond):
        self.code += self.indent() + "if (" + cond + ")\n"
        self.beginBlock()

    def beginElse(self, cond):
        self.code += self.indent() + "else\n"
        self.beginBlock()

    def endElse(self):
        self.endBlock()

    def endIf(self):
        self.endBlock()

    def beginWhile(self, cond):
        self.code += self.indent() + "while (" + cond + ")\n"
        self.beginBlock()

    def endWhile(self):
        self.endBlock()

    def beginFor(self, initial, condition, increment):
        self.code += self.indent() + "for (" + "; ".join([initial, condition, increment]) + ")\n"
        self.beginBlock()

    def endFor(self):
        self.endBlock()

    def stmt(self, code):
        self.code += self.indent() + code + ";\n"

    def line(self, code):
        self.code += self.indent() + code + "\n"

    def funcCall(self, lhs, funcName, parameters):
        res = self.indent()

        if lhs is not None:
            res += lhs + " = "

        res += funcName + "(%s);\n" % (", ".join(parameters))

        self.code += res

    # Given a VulkanType object, generate a C type declaration with optional parameter name:
    # [const] [typename][*][const*] [paramName]
    def makeCTypeDecl(self, vulkanType, useParamName = True):
        constness = "const " if vulkanType.isConst else ""
        typeName = vulkanType.typeName

        if vulkanType.pointerIndirectionLevels == 0:
            ptrSpec = ""
        elif vulkanType.isPointerToConstPointer:
            ptrSpec = "* const*"
        else:
            ptrSpec = "*" * vulkanType.pointerIndirectionLevels

        paramStr = (" " + vulkanType.paramName) if useParamName and (vulkanType.paramName is not None) else ""

        return "%s%s%s%s" % (constness, typeName, ptrSpec, paramStr)

    # Given a VulkanAPI object, generate the C function protype:
    # <returntype> <funcname>(<comma-separated parameters each with <type> <name> >)
    def makeFuncProto(self, vulkanApi):

        protoBegin = "%s %s" % (self.makeCTypeDecl(vulkanApi.retType, useParamName = False), vulkanApi.name)
        protoParams = "(\n    %s)" % (",\n    ".join(list(map(self.makeCTypeDecl, vulkanApi.parameters))))

        return protoBegin + protoParams

    def makeFuncDecl(self, vulkanApi):
        return self.makeFuncProto(vulkanApi) + ";\n"

    def makeFuncImpl(self, vulkanApi, codegenFunc):
        self.swapCode()

        self.line(self.makeFuncProto(vulkanApi))
        self.beginBlock()
        codegenFunc(self)
        self.endBlock()

        return self.swapCode()


class VulkanAPIWrapper(object):
    def __init__(self, customApiPrefix, extraParameters = [], returnTypeOverride = None, codegenDef = None):
        self.customApiPrefix = customApiPrefix
        self.extraParameters = extraParameters
        self.returnTypeOverride = returnTypeOverride

        self.codegen = CodeGen()

        self.definitionFunc = codegenDef

        # Private function
        def makeApiFunc(self, typeInfo, apiName):
            customApi = deepcopy(typeInfo.apis[apiName])
            customApi.name = self.customApiPrefix + customApi.name
            customApi.parameters = self.extraParameters + customApi.parameters
            if self.returnTypeOverride is not None:
                customApi.retType = self.returnTypeOverride
            return customApi

        self.makeApi = makeApiFunc

    def setCodegenDef(self, codegenDefFunc):
        self.definitionFunc = codegenDefFunc

    def makeDecl(self, typeInfo, apiName):
        return self.codegen.makeFuncProto(self.makeApi(self, typeInfo, apiName)) + ";\n"

    def makeDefinition(self, typeInfo, apiName, isStatic = False):
        vulkanApi = self.makeApi(self, typeInfo, apiName)

        self.codegen.swapCode()
        self.codegen.beginBlock()

        if self.definitionFunc is None:
            print ("ERROR: No definition found for (%s, %s)" % (vulkanApi.name, self.customApiPrefix))
            sys.exit(1)

        self.definitionFunc(self.codegen, vulkanApi)

        self.codegen.endBlock()

        return ("static " if isStatic else "") + self.codegen.makeFuncProto(vulkanApi) + "\n" + self.codegen.swapCode()

    def getFuncName(self, typeInfo, origName):
        return self.makeApi(self, typeInfo, apiName).name
