/* This file was generated by syncqt. */
#ifndef QT_ACTIVEQT_VERSION_H
#define QT_ACTIVEQT_VERSION_H

#define ACTIVEQT_VERSION_STR "5.11.1"

#define ACTIVEQT_VERSION 0x050B01

#endif // QT_ACTIVEQT_VERSION_H
