
Pkg.UserSrc=false
<<<<<<< HEAD   (f97d82 Merge "Merge cherrypicks of [1676350, 1676351] into emu-30-r)
Pkg.Revision=30.5.5
=======
Pkg.Revision=30.6.5
>>>>>>> BRANCH (a73bfe Merge "c2-codecs: use display sizes when rendering to surfac)
Pkg.Path=emulator
Pkg.Desc=Android Emulator
