Pkg.UserSrc=false
<<<<<<< HEAD   (464e37 Merge "Merge empty history for sparse-5409122-L7540000028739)
Pkg.Revision=28.0.25
=======
Pkg.Revision=30.4.6
>>>>>>> BRANCH (510a80 Merge "Merge cherrypicks of [1623139] into sparse-7187391-L1)
Pkg.Path=emulator
Pkg.Desc=Android Emulator
