Pkg.UserSrc=false
<<<<<<< HEAD   (317ab1 Merge "Revert snapshot code path." into snap-temp-L191000007)
Pkg.Revision=30.2.5
=======
Pkg.Revision=30.2.6
>>>>>>> CHANGE (264a4f Bump emulator version to 30.2.6)
Pkg.Path=emulator
Pkg.Desc=Android Emulator
