#!/bin/sh
./sign-vm-entitlement.sh objs/qemu/darwin-x86_64/qemu-system-i386
./sign-vm-entitlement.sh objs/qemu/darwin-x86_64/qemu-system-x86_64
./sign-vm-entitlement.sh objs/qemu/darwin-x86_64/qemu-system-i386-headless
./sign-vm-entitlement.sh objs/qemu/darwin-x86_64/qemu-system-x86_64-headless
./sign-vm-entitlement.sh objs/qemu/darwin-aarch64/qemu-system-aarch64
./sign-vm-entitlement.sh objs/qemu/darwin-aarch64/qemu-system-aarch64-headless
./sign-vm-entitlement.sh objs/lib64/libemugl_common.dylib
./sign-vm-entitlement.sh objs/lib64/libemugl_test_shared_library.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/platforms/libqcocoa.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/styles/libqmacstyle.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/bearer/libqgenericbearer.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/iconengines/libqsvgicon.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/imageformats/libqgif.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/imageformats/libqwbmp.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/imageformats/libqwebp.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/imageformats/libqico.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/imageformats/libqmacheif.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/imageformats/libqjpeg.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/imageformats/libqtiff.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/imageformats/libqsvg.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/imageformats/libqicns.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/imageformats/libqtga.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/imageformats/libqmacjp2.dylib
./sign-vm-entitlement.sh objs/lib64/gles_swiftshader/libEGL.dylib
./sign-vm-entitlement.sh objs/lib64/gles_swiftshader/libGLES_CM.dylib
./sign-vm-entitlement.sh objs/lib64/gles_swiftshader/libGLESv2.dylib
./sign-vm-entitlement.sh objs/lib64/gles_angle/libEGL.dylib
./sign-vm-entitlement.sh objs/lib64/gles_angle/libGLESv2.dylib
./sign-vm-entitlement.sh objs/lib64/gles_angle/libabsl.dylib
./sign-vm-entitlement.sh objs/lib64/gles_angle/libchrome_zlib.dylib
./sign-vm-entitlement.sh objs/lib64/libshadertranslator.dylib
./sign-vm-entitlement.sh objs/lib64/OpenglRender.dylib
./sign-vm-entitlement.sh objs/lib64/libandroid-emu-shared.dylib
./sign-vm-entitlement.sh objs/lib64/libOpenglRender.dylib
./sign-vm-entitlement.sh objs/lib64/vulkan/libvk_swiftshader.dylib
./sign-vm-entitlement.sh objs/lib64/vulkan/libvulkan.dylib
./sign-vm-entitlement.sh objs/lib64/vulkan/libMoltenVK.dylib
