./sign-vm-entitlement.sh objs/qemu/darwin-aarch64/qemu-system-aarch64
./sign-vm-entitlement.sh objs/qemu/darwin-aarch64/qemu-system-aarch64-headless
./sign-vm-entitlement.sh objs/lib64/libemugl_common.dylib
./sign-vm-entitlement.sh objs/lib64/libemugl_test_shared_library.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/platforms/libqcocoa.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/styles/libqmacstyle.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/bearer/libqgenericbearer.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/iconengines/libqsvgicon.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/imageformats/libqgif.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/imageformats/libqwbmp.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/imageformats/libqwebp.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/imageformats/libqico.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/imageformats/libqmacheif.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/imageformats/libqjpeg.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/imageformats/libqtiff.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/imageformats/libqsvg.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/imageformats/libqicns.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/imageformats/libqtga.dylib
./sign-vm-entitlement.sh objs/lib64/qt/plugins/imageformats/libqmacjp2.dylib
./sign-vm-entitlement.sh objs/lib64/qt/lib/libQt5DBusAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh objs/lib64/qt/lib/libQt5GuiAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh objs/lib64/qt/lib/libQt5SvgAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh objs/lib64/qt/lib/libQt5PrintSupportAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh objs/lib64/qt/lib/libQt5WidgetsAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh objs/lib64/qt/lib/libQt5NetworkAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh objs/lib64/qt/lib/libQt5CoreAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh objs/lib64/gles_swiftshader/libEGL.dylib
./sign-vm-entitlement.sh objs/lib64/gles_swiftshader/libGLES_CM.dylib
./sign-vm-entitlement.sh objs/lib64/gles_swiftshader/libGLESv2.dylib
./sign-vm-entitlement.sh objs/lib64/libshadertranslator.dylib
./sign-vm-entitlement.sh objs/lib64/OpenglRender.dylib
./sign-vm-entitlement.sh objs/lib64/libandroid-emu-shared.dylib
./sign-vm-entitlement.sh objs/lib64/libOpenglRender.dylib
