export PREBUILTS_DIR=../../prebuilts/android-emulator-build/qt/darwin-aarch64-nowebengine

./sign-vm-entitlement.sh ${PREBUILTS_DIR}/bin/moc
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/bin/rcc
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/bin/uic

./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtWebSockets/libdeclarative_qmlwebsockets.dylib.dSYM/Contents/Resources/DWARF/libdeclarative_qmlwebsockets.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtWebSockets/libdeclarative_qmlwebsockets.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtQml/Models.2/libmodelsplugin.dylib.dSYM/Contents/Resources/DWARF/libmodelsplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtQml/Models.2/libmodelsplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtQml/StateMachine/libqtqmlstatemachine.dylib.dSYM/Contents/Resources/DWARF/libqtqmlstatemachine.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtQml/StateMachine/libqtqmlstatemachine.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtQml/RemoteObjects/libqtqmlremoteobjects.dylib.dSYM/Contents/Resources/DWARF/libqtqmlremoteobjects.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtQml/RemoteObjects/libqtqmlremoteobjects.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtGamepad/libdeclarative_gamepad.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtGamepad/libdeclarative_gamepad.dylib.dSYM/Contents/Resources/DWARF/libdeclarative_gamepad.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtRemoteObjects/libqtremoteobjects.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtRemoteObjects/libqtremoteobjects.dylib.dSYM/Contents/Resources/DWARF/libqtremoteobjects.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtPurchasing/libdeclarative_purchasing.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtPurchasing/libdeclarative_purchasing.dylib.dSYM/Contents/Resources/DWARF/libdeclarative_purchasing.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtSensors/libdeclarative_sensors.dylib.dSYM/Contents/Resources/DWARF/libdeclarative_sensors.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtSensors/libdeclarative_sensors.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/Qt/labs/settings/libqmlsettingsplugin.dylib.dSYM/Contents/Resources/DWARF/libqmlsettingsplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/Qt/labs/settings/libqmlsettingsplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/Qt/labs/qmlmodels/liblabsmodelsplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/Qt/labs/qmlmodels/liblabsmodelsplugin.dylib.dSYM/Contents/Resources/DWARF/liblabsmodelsplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/Qt/labs/wavefrontmesh/libqmlwavefrontmeshplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/Qt/labs/wavefrontmesh/libqmlwavefrontmeshplugin.dylib.dSYM/Contents/Resources/DWARF/libqmlwavefrontmeshplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/Qt/labs/folderlistmodel/libqmlfolderlistmodelplugin.dylib.dSYM/Contents/Resources/DWARF/libqmlfolderlistmodelplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/Qt/labs/folderlistmodel/libqmlfolderlistmodelplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/Qt/labs/sharedimage/libsharedimageplugin.dylib.dSYM/Contents/Resources/DWARF/libsharedimageplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/Qt/labs/sharedimage/libsharedimageplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtCanvas3D/libqtcanvas3d.dylib.dSYM/Contents/Resources/DWARF/libqtcanvas3d.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtCanvas3D/libqtcanvas3d.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtQuick.2/libqtquick2plugin.dylib.dSYM/Contents/Resources/DWARF/libqtquick2plugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtQuick.2/libqtquick2plugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtGraphicalEffects/libqtgraphicaleffectsplugin.dylib.dSYM/Contents/Resources/DWARF/libqtgraphicaleffectsplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtGraphicalEffects/libqtgraphicaleffectsplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtGraphicalEffects/private/libqtgraphicaleffectsprivate.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtGraphicalEffects/private/libqtgraphicaleffectsprivate.dylib.dSYM/Contents/Resources/DWARF/libqtgraphicaleffectsprivate.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtQuick/Particles.2/libparticlesplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtQuick/Particles.2/libparticlesplugin.dylib.dSYM/Contents/Resources/DWARF/libparticlesplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtQuick/Shapes/libqmlshapesplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtQuick/Shapes/libqmlshapesplugin.dylib.dSYM/Contents/Resources/DWARF/libqmlshapesplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtQuick/Layouts/libqquicklayoutsplugin.dylib.dSYM/Contents/Resources/DWARF/libqquicklayoutsplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtQuick/Layouts/libqquicklayoutsplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtQuick/XmlListModel/libqmlxmllistmodelplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtQuick/XmlListModel/libqmlxmllistmodelplugin.dylib.dSYM/Contents/Resources/DWARF/libqmlxmllistmodelplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtQuick/LocalStorage/libqmllocalstorageplugin.dylib.dSYM/Contents/Resources/DWARF/libqmllocalstorageplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtQuick/LocalStorage/libqmllocalstorageplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtQuick/Window.2/libwindowplugin.dylib.dSYM/Contents/Resources/DWARF/libwindowplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtQuick/Window.2/libwindowplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtMultimedia/libdeclarative_multimedia.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtMultimedia/libdeclarative_multimedia.dylib.dSYM/Contents/Resources/DWARF/libdeclarative_multimedia.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtAudioEngine/libdeclarative_audioengine.dylib.dSYM/Contents/Resources/DWARF/libdeclarative_audioengine.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtAudioEngine/libdeclarative_audioengine.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtScxml/libdeclarative_scxml.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtScxml/libdeclarative_scxml.dylib.dSYM/Contents/Resources/DWARF/libdeclarative_scxml.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtTest/libqmltestplugin.dylib.dSYM/Contents/Resources/DWARF/libqmltestplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/qml/QtTest/libqmltestplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/mediaservice/libqtmedia_audioengine.dylib.dSYM/Contents/Resources/DWARF/libqtmedia_audioengine.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/mediaservice/libqavfmediaplayer.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/mediaservice/libqavfcamera.dylib.dSYM/Contents/Resources/DWARF/libqavfcamera.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/mediaservice/libqavfmediaplayer.dylib.dSYM/Contents/Resources/DWARF/libqavfmediaplayer.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/mediaservice/libqtmedia_audioengine.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/mediaservice/libqavfcamera.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/sensors/libqtsensors_ios.dylib.dSYM/Contents/Resources/DWARF/libqtsensors_ios.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/sensors/libqtsensors_generic.dylib.dSYM/Contents/Resources/DWARF/libqtsensors_generic.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/sensors/libqtsensors_generic.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/sensors/libqtsensors_ios.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/platforms/libqoffscreen.dylib.dSYM/Contents/Resources/DWARF/libqoffscreen.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/platforms/libqwebgl.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/platforms/libqoffscreen.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/platforms/libqminimal.dylib.dSYM/Contents/Resources/DWARF/libqminimal.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/platforms/libqminimal.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/platforms/libqwebgl.dylib.dSYM/Contents/Resources/DWARF/libqwebgl.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/platforms/libqcocoa.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/platforms/libqcocoa.dylib.dSYM/Contents/Resources/DWARF/libqcocoa.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/qmltooling/libqmldbg_quickprofiler.dylib.dSYM/Contents/Resources/DWARF/libqmldbg_quickprofiler.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/qmltooling/libqmldbg_native.dylib.dSYM/Contents/Resources/DWARF/libqmldbg_native.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/qmltooling/libqmldbg_messages.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/qmltooling/libqmldbg_server.dylib.dSYM/Contents/Resources/DWARF/libqmldbg_server.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/qmltooling/libqmldbg_inspector.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/qmltooling/libqmldbg_quickprofiler.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/qmltooling/libqmldbg_inspector.dylib.dSYM/Contents/Resources/DWARF/libqmldbg_inspector.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/qmltooling/libqmldbg_tcp.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/qmltooling/libqmldbg_tcp.dylib.dSYM/Contents/Resources/DWARF/libqmldbg_tcp.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/qmltooling/libqmldbg_preview.dylib.dSYM/Contents/Resources/DWARF/libqmldbg_preview.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/qmltooling/libqmldbg_profiler.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/qmltooling/libqmldbg_debugger.dylib.dSYM/Contents/Resources/DWARF/libqmldbg_debugger.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/qmltooling/libqmldbg_preview.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/qmltooling/libqmldbg_nativedebugger.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/qmltooling/libqmldbg_local.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/qmltooling/libqmldbg_server.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/qmltooling/libqmldbg_local.dylib.dSYM/Contents/Resources/DWARF/libqmldbg_local.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/qmltooling/libqmldbg_messages.dylib.dSYM/Contents/Resources/DWARF/libqmldbg_messages.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/qmltooling/libqmldbg_nativedebugger.dylib.dSYM/Contents/Resources/DWARF/libqmldbg_nativedebugger.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/qmltooling/libqmldbg_native.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/qmltooling/libqmldbg_profiler.dylib.dSYM/Contents/Resources/DWARF/libqmldbg_profiler.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/qmltooling/libqmldbg_debugger.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/platformthemes/libqxdgdesktopportal.dylib.dSYM/Contents/Resources/DWARF/libqxdgdesktopportal.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/platformthemes/libqxdgdesktopportal.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/printsupport/libcocoaprintersupport.dylib.dSYM/Contents/Resources/DWARF/libcocoaprintersupport.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/printsupport/libcocoaprintersupport.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/sensorgestures/libqtsensorgestures_shakeplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/sensorgestures/libqtsensorgestures_plugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/sensorgestures/libqtsensorgestures_plugin.dylib.dSYM/Contents/Resources/DWARF/libqtsensorgestures_plugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/sensorgestures/libqtsensorgestures_shakeplugin.dylib.dSYM/Contents/Resources/DWARF/libqtsensorgestures_shakeplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/styles/libqmacstyle.dylib.dSYM/Contents/Resources/DWARF/libqmacstyle.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/styles/libqmacstyle.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/audio/libqtaudio_coreaudio.dylib.dSYM/Contents/Resources/DWARF/libqtaudio_coreaudio.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/audio/libqtaudio_coreaudio.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/canbus/libqttinycanbus.dylib.dSYM/Contents/Resources/DWARF/libqttinycanbus.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/canbus/libqttinycanbus.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/canbus/libqtpassthrucanbus.dylib.dSYM/Contents/Resources/DWARF/libqtpassthrucanbus.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/canbus/libqtpassthrucanbus.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/canbus/libqtvirtualcanbus.dylib.dSYM/Contents/Resources/DWARF/libqtvirtualcanbus.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/canbus/libqtvirtualcanbus.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/canbus/libqtpeakcanbus.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/canbus/libqtpeakcanbus.dylib.dSYM/Contents/Resources/DWARF/libqtpeakcanbus.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/bearer/libqgenericbearer.dylib.dSYM/Contents/Resources/DWARF/libqgenericbearer.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/bearer/libqgenericbearer.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/iconengines/libqsvgicon.dylib.dSYM/Contents/Resources/DWARF/libqsvgicon.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/iconengines/libqsvgicon.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/sqldrivers/libqsqlite.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/sqldrivers/libqsqlite.dylib.dSYM/Contents/Resources/DWARF/libqsqlite.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/imageformats/libqico.dylib.dSYM/Contents/Resources/DWARF/libqico.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/imageformats/libqjpeg.dylib.dSYM/Contents/Resources/DWARF/libqjpeg.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/imageformats/libqgif.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/imageformats/libqwbmp.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/imageformats/libqwebp.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/imageformats/libqico.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/imageformats/libqgif.dylib.dSYM/Contents/Resources/DWARF/libqgif.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/imageformats/libqmacjp2.dylib.dSYM/Contents/Resources/DWARF/libqmacjp2.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/imageformats/libqmacheif.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/imageformats/libqmacheif.dylib.dSYM/Contents/Resources/DWARF/libqmacheif.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/imageformats/libqtiff.dylib.dSYM/Contents/Resources/DWARF/libqtiff.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/imageformats/libqtga.dylib.dSYM/Contents/Resources/DWARF/libqtga.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/imageformats/libqjpeg.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/imageformats/libqwebp.dylib.dSYM/Contents/Resources/DWARF/libqwebp.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/imageformats/libqtiff.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/imageformats/libqsvg.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/imageformats/libqsvg.dylib.dSYM/Contents/Resources/DWARF/libqsvg.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/imageformats/libqicns.dylib.dSYM/Contents/Resources/DWARF/libqicns.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/imageformats/libqicns.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/imageformats/libqtga.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/imageformats/libqmacjp2.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/imageformats/libqwbmp.dylib.dSYM/Contents/Resources/DWARF/libqwbmp.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/designer/libqquickwidget.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/designer/libqquickwidget.dylib.dSYM/Contents/Resources/DWARF/libqquickwidget.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/generic/libqtuiotouchplugin.dylib.dSYM/Contents/Resources/DWARF/libqtuiotouchplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/generic/libqtuiotouchplugin.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/playlistformats/libqtmultimedia_m3u.dylib.dSYM/Contents/Resources/DWARF/libqtmultimedia_m3u.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/playlistformats/libqtmultimedia_m3u.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/gamepads/libdarwingamepad.dylib.dSYM/Contents/Resources/DWARF/libdarwingamepad.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/plugins/gamepads/libdarwingamepad.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5CoreAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5CoreAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SqlAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5WebSocketsAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5WidgetsAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5WidgetsAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5DesignerAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5DesignerAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MacExtrasAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5CoreAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5CoreAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MultimediaWidgetsAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5MultimediaWidgetsAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SensorsAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5DesignerComponentsAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5DesignerComponentsAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SqlAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5SqlAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5ScxmlAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5ScxmlAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5ScxmlAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5ScxmlAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5ScxmlAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5TestAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickTestAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SerialPortAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5SerialPortAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5PurchasingAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5PurchasingAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickWidgetsAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5DBusAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5DBusAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5HelpAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5PurchasingAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5DBusAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MultimediaQuickAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5MultimediaQuickAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SerialBusAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5SerialBusAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5ScxmlAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5ScxmlAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5ScxmlAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5PrintSupportAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5WidgetsAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5WidgetsAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5PurchasingAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5PurchasingAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5PurchasingAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickShapesAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5DesignerComponentsAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5QuickAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5DesignerComponentsAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5DesignerComponentsAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5DesignerComponentsAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5XmlPatternsAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5XmlAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5XmlAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5XmlAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SerialPortAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5NfcAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5NfcAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5NetworkAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5WidgetsAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5WidgetsAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SerialBusAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5RemoteObjectsAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5RemoteObjectsAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5DesignerComponentsAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5DesignerComponentsAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5DBusAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5DBusAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SerialBusAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5DBusAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5DBusAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5DBusAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SvgAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickShapesAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickShapesAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5QuickShapesAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SensorsAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5SensorsAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickTestAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MultimediaAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5XmlPatternsAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5XmlPatternsAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5GuiAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5GuiAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5GuiAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5XmlAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickWidgetsAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5QuickWidgetsAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickWidgetsAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5CoreAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5CoreAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SensorsAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5OpenGLAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5OpenGLAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickParticlesAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5RemoteObjectsAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5RemoteObjectsAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickParticlesAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5QuickParticlesAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickTestAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5QuickTestAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5DesignerAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5PrintSupportAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5PrintSupportAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SqlAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5SqlAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SensorsAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5SensorsAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5WebSocketsAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5WebSocketsAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5WidgetsAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MacExtrasAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5MacExtrasAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5RemoteObjectsAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5RemoteObjectsAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5RemoteObjectsAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5TestAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5NetworkAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5PrintSupportAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5ScxmlAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SensorsAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SensorsAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5SensorsAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5TestAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5TestAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5ConcurrentAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5ConcurrentAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5CoreAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SqlAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5DesignerComponentsAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SvgAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5SvgAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SvgAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5WebSocketsAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5WebSocketsAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5PrintSupportAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5PrintSupportAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5PrintSupportAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SensorsAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5SensorsAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5OpenGLAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5OpenGLAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickWidgetsAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5QuickWidgetsAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5GamepadAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QmlAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5PrintSupportAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5PrintSupportAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickShapesAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5QuickShapesAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5XmlPatternsAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5XmlPatternsAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5WidgetsAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QmlAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QmlAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QmlAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5QmlAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SerialPortAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5SerialPortAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickShapesAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5NetworkAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5NetworkAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5WidgetsAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5WidgetsAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5WidgetsAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5NetworkAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5NetworkAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SensorsAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SqlAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5SqlAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SqlAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5RemoteObjectsAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5NetworkAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5NetworkAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MultimediaQuickAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5DBusAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5HelpAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5HelpAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5HelpAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QmlAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5QmlAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SerialPortAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SerialPortAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5SerialPortAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5XmlPatternsAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5XmlPatternsAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5XmlPatternsAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5GamepadAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5GamepadAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5GamepadAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MultimediaQuickAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5MultimediaQuickAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MultimediaWidgetsAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MultimediaQuickAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MultimediaWidgetsAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5MultimediaWidgetsAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SvgAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5SvgAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5PrintSupportAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5DesignerComponentsAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SerialPortAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickWidgetsAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5QuickWidgetsAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5NfcAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5DesignerAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5DesignerAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5DesignerAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5DesignerAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5DesignerAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickTestAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5WebSocketsAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5WebSocketsAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5OpenGLAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5RemoteObjectsAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5XmlPatternsAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MultimediaWidgetsAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickShapesAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5QuickShapesAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5ConcurrentAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5ConcurrentAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5RemoteObjectsAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5RemoteObjectsAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5ScxmlAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5ScxmlAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QmlAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5QmlAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5ScxmlAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5OpenGLAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5GamepadAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5GamepadAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5NetworkAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5NetworkAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5NetworkAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5GuiAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5HelpAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5HelpAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickShapesAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5QuickShapesAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MultimediaAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5GuiAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5GuiAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5WebSocketsAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5PurchasingAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5GamepadAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MultimediaAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5MultimediaAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5QuickAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5NfcAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5DesignerAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5DesignerAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5NfcAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5NfcAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SerialPortAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5SerialPortAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickTestAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5QuickTestAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickTestAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5DBusAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QmlAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5QmlAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5GuiAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5GamepadAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5GamepadAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MultimediaWidgetsAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5MultimediaWidgetsAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5HelpAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5HelpAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickParticlesAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5QuickParticlesAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickTestAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5QuickTestAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SerialBusAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5GamepadAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5DesignerComponentsAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5DesignerComponentsAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5PurchasingAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SvgAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5SvgAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5XmlAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5XmlAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5XmlAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5GuiAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5OpenGLAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5ConcurrentAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5XmlPatternsAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5NfcAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SerialBusAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5SerialBusAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5WebSocketsAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5XmlAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5XmlAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SerialPortAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MultimediaQuickAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5PrintSupportAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5PrintSupportAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MacExtrasAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5MacExtrasAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MacExtrasAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5HelpAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5QuickAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickParticlesAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5QuickParticlesAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5ConcurrentAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MultimediaWidgetsAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5MultimediaWidgetsAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5RemoteObjectsAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickWidgetsAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5QuickWidgetsAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickParticlesAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5CoreAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5CoreAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SvgAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5DesignerAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5TestAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5TestAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SvgAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5SvgAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5TestAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5ConcurrentAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5OpenGLAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5OpenGLAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SerialBusAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SerialBusAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5SerialBusAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5QuickAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MultimediaAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5MultimediaAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MultimediaQuickAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5MultimediaQuickAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5PurchasingAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5PurchasingAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5WidgetsAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5CoreAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5CoreAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5CoreAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MacExtrasAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MultimediaAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MultimediaAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5MultimediaAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MacExtrasAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5OpenGLAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5OpenGLAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5OpenGLAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5GamepadAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5GamepadAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MacExtrasAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5MacExtrasAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MultimediaAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5DesignerAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickParticlesAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QmlAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SqlAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MultimediaAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5MultimediaAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickTestAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5QuickTestAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SvgAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5HelpAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MultimediaWidgetsAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SerialBusAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5SerialBusAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5PurchasingAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5PurchasingAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5NetworkAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5XmlPatternsAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5XmlPatternsAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5ConcurrentAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5ConcurrentAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5NfcAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5NfcAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5ConcurrentAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5XmlAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5XmlAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5NfcAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5NfcAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MultimediaQuickAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5XmlAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5GuiAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5GuiAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5ConcurrentAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5ConcurrentAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5WebSocketsAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5WebSocketsAndroidEmu.5.dylib.dSYM/Contents/Resources/DWARF/libQt5WebSocketsAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickParticlesAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5QuickParticlesAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickParticlesAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5GuiAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5GuiAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickWidgetsAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickShapesAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5TestAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5TestAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MultimediaQuickAndroidEmu.dylib.dSYM/Contents/Resources/DWARF/libQt5MultimediaQuickAndroidEmu.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5SqlAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5SqlAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5DBusAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5DBusAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5TestAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5TestAndroidEmu.5.12.1.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5TestAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MultimediaWidgetsAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5QuickWidgetsAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5NfcAndroidEmu.5.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5HelpAndroidEmu.5.12.dylib.dSYM/Contents/Resources/DWARF/libQt5HelpAndroidEmu.5.12.dylib
./sign-vm-entitlement.sh ${PREBUILTS_DIR}/lib/libQt5MacExtrasAndroidEmu.5.12.1.dylib.dSYM/Contents/Resources/DWARF/libQt5MacExtrasAndroidEmu.5.12.1.dylib
