Pkg.UserSrc=false
<<<<<<< HEAD   (1f1fc0 Merge "Merge cherrypicks of [1671025, 1671026] into emu-30-r)
Pkg.Revision=30.5.4
=======
Pkg.Revision=30.5.5
>>>>>>> CHANGE (b23f77 Bump emulator version to 30.5.5)
Pkg.Path=emulator
Pkg.Desc=Android Emulator
