Pkg.UserSrc=false
<<<<<<< HEAD   (921171 Merge "Merge cherrypicks of [1493823, 1493824] into emu-30-r)
Pkg.Revision=30.2.6
=======
Pkg.Revision=30.3.4
>>>>>>> BRANCH (613ca0 Merge "Add 140 and 180 as supported LCD densities" into emu-)
Pkg.Path=emulator
Pkg.Desc=Android Emulator
