Pkg.UserSrc=false
<<<<<<< HEAD   (3c6fcd Merge "Bump revision to 26.0.1" into emu-2.4-release)
Pkg.Revision=26.0.1
=======
Pkg.Revision=26.0.2
>>>>>>> BRANCH (c551e1 Merge "Allow multiple active AdbGuestPipes" into emu-master-)
Pkg.Path=emulator
Pkg.Desc=Android Emulator
Pkg.Dependencies=tools#25.3
