Pkg.UserSrc=false
<<<<<<< HEAD   (2a9869 Merge "Merge cherrypicks of [1621320] into emu-30-release" i)
Pkg.Revision=30.4.5
=======
Pkg.Revision=30.5.3
>>>>>>> BRANCH (227581 Merge "Use other file names when an imported qcow2 cannot be)
Pkg.Path=emulator
Pkg.Desc=Android Emulator
