Pkg.UserSrc=false
<<<<<<< HEAD   (2a9869 Merge "Merge cherrypicks of [1621320] into emu-30-release" i)
Pkg.Revision=30.4.5
=======
Pkg.Revision=30.4.6
>>>>>>> CHANGE (cb3e45 Bump emulator version to 30.4.6)
Pkg.Path=emulator
Pkg.Desc=Android Emulator
