Pkg.UserSrc=false
<<<<<<< HEAD   (2a9869 Merge "Merge cherrypicks of [1621320] into emu-30-release" i)
Pkg.Revision=30.4.5
=======
Pkg.Revision=30.5.3
>>>>>>> BRANCH (7de27f Merge "Fix behavior in landscape mode" into emu-master-dev)
Pkg.Path=emulator
Pkg.Desc=Android Emulator
