#!/usr/bin/python3 -i
#
# Copyright (c) 2013-2018 The Khronos Group Inc.
# Copyright (c) 2013-2018 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os, re, sys
from generator import *

# CerealGenerator - generates complete set of encoder and decoder source
# while being agnostic to the stream implementation

class Module(object):
    def __init__(self, directory, basename):
        self.directory = directory
        self.basename = basename

        self.headerPreamble = ""
        self.implPreamble = ""

        self.headerPostamble = ""
        self.implPostamble = ""

        self.headerFileHandle = ""
        self.implFileHandle = ""

    def getMakefileSrcEntry(self):
        return "    " + os.path.join(self.directory, self.basename) + ".cpp \\\n"

    def begin(self, globalDir):
        # Create subdirectory, if needed
        absDir = os.path.join(globalDir, self.directory)

        filename = os.path.join(absDir, self.basename)

        fpHeader = open(filename + ".h", 'w', encoding='utf-8')
        write("// Module: %s (header) Autogenerated by CerealGenerator\n" % self.basename, file = fpHeader)

        fpImpl = open(filename + ".cpp", 'w', encoding='utf-8')
        write("// Module: %s (impl) Autogenerated by CerealGenerator\n" % self.basename, file = fpImpl)

        self.headerFileHandle = fpHeader
        self.implFileHandle = fpImpl

        write(self.headerPreamble, file = fpHeader)
        write(self.implPreamble, file = fpImpl)

    def appendHeader(self, toAppend):
        write(toAppend, file = self.headerFileHandle)

    def appendImpl(self, toAppend):
        write(toAppend, file = self.implFileHandle)

    def end(self):
        write(self.headerPreamble, file = self.headerFileHandle)
        write(self.implPreamble, file = self.implFileHandle)

        self.headerFileHandle.close()
        self.implFileHandle.close()


# ---- methods overriding base class ----
# beginFile(genOpts)
# endFile()
# beginFeature(interface, emit)
# endFeature()
# genType(typeinfo,name)
# genStruct(typeinfo,name)
# genGroup(groupinfo,name)
# genEnum(enuminfo, name)
# genCmd(cmdinfo)
class CerealGenerator(OutputGenerator):

    """Generate serialization code"""
    def __init__(self, errFile = sys.stderr,
                       warnFile = sys.stderr,
                       diagFile = sys.stdout):
        OutputGenerator.__init__(self, errFile, warnFile, diagFile)

        self.modules = {}

        self.indentLevel = 0
        self.code = ""

        self.cereal_Android_mk_header = """
LOCAL_PATH := $(call my-dir)

# For Vulkan libraries

cereal_C_INCLUDES := \\
    $(LOCAL_PATH) \\
    $(EMUGL_PATH)/host/include/vulkan \\

cereal_STATIC_LIBRARIES := \\
    android-emu \\
    android-emu-base \\
"""

        # Define our generated modules here
        self.addModule("guest", "goldfish_vk_frontend")
        self.addModule("guest", "goldfish_vk_encoder")

        self.addModule("common", "goldfish_vk_marshaling")

        self.cereal_Android_mk_body = """
$(call emugl-begin-static-library,lib$(BUILD_TARGET_SUFFIX)OpenglRender_vulkan_cereal_guest)

LOCAL_C_INCLUDES += $(cereal_C_INCLUDES)

LOCAL_STATIC_LIBRARIES += $(cereal_STATIC_LIBRARIES)

LOCAL_SRC_FILES := \\
"""
        def addSrcEntry(m):
            self.cereal_Android_mk_body += m.getMakefileSrcEntry()
        self.forEachModule(addSrcEntry)

        self.cereal_Android_mk_body += """
$(call emugl-end-module)
"""

        self.modules["goldfish_vk_frontend"].headerPreamble = """
#include <vulkan.h>
"""

        self.modules["goldfish_vk_frontend"].implPreamble = """
#include "guest/goldfish_vk_frontend.h"

#include "guest/goldfish_vk_encoder.h"
"""

        self.modules["goldfish_vk_encoder"].implPreamble = """
#include "guest/goldfish_vk_encoder.h"

#include "common/goldfish_vk_marshaling.h"
"""

    def addModule(self, directory, basename):
        self.modules[basename] = Module(directory, basename)

    def forEachModule(self, func):
        for _, m in self.modules.items():
            func(m)

################################################################################

    def swapCode(self,):
        res = "%s" % self.code
        self.code = ""
        return res

    def indent(self,):
        return "".join("    " * self.indentLevel)

    def beginBlock(self,):
        self.code += self.indent() + "{\n"
        self.indentLevel += 1

    def endBlock(self,):
        self.indentLevel -= 1
        self.code += self.indent() + "}\n"

    def beginIf(self, cond):
        self.code += self.indent() + "if (" + cond + ")\n"
        self.beginBlock()

    def beginElse(self, cond):
        self.code += self.indent() + "else\n"
        self.beginBlock()

    def endElse(self):
        self.endBlock()

    def endIf(self):
        self.endBlock()

    def beginWhile(self, cond):
        self.code += self.indent() + "while (" + cond + ")\n"
        self.beginBlock()

    def endWhile(self):
        self.endBlock()

    def beginFor(self, initial, condition, increment):
        self.code += self.indent() + "for (" + "; ".join([initial, condition, increment]) + ")\n"
        self.beginBlock()

    def endFor(self, initial, condition, increment):
        self.endBlock()

    def stmt(self, code):
        self.code += self.indent() + code + ";\n"

    def line(self, code):
        self.code += self.indent() + code + "\n"

    def makeFuncProto(self, cmdInfoElem, name, callNamePrefix = "", extraArgs = None, retTypeOverride = None):
        params = cmdInfoElem.findall('param')

        if extraArgs:
            args = list(extraArgs)
        else:
            args = []

        for p in params:
            args.append(self.makeCParamDecl(p, 0).strip())

        callName = callNamePrefix + name

        if retTypeOverride:
            retType = retTypeOverride
        else:
            retType = cmdInfoElem.find('proto').find('type').text

        divider = "\n    "
        funcPrototype = retType + " " + callName + "(" + divider + ("," + divider).join(args) + ")\n"

        return funcPrototype

## Marshaling definitions#######################################################

    def makeMarshalingProto(self, cmdInfoElem, name):
        return self.makeFuncProto(
            cmdInfoElem, name, "marshal_",
            extraArgs = ["void* vkStream"],
            retTypeOverride = "void")

    def makeMarshalingDef(self, cmdInfoElem, name):
        params = cmdInfoElem.findall('param')

        funcPrototype = \
            self.makeMarshalingProto(cmdInfoElem, name)

        self.swapCode();

        self.beginBlock();

        retType = cmdInfoElem.find('proto').find('type').text

        if retType != "void":
            self.stmt("return (%s)0" % retType)

        self.endBlock();
        return funcPrototype + self.swapCode()

    def makeMarshalingCall(self, cmdInfoElem, name):
        params = cmdInfoElem.findall('param')

        args = ["vkStream"]
        for p in params:
            ptype = p.find('type')
            pname = p.find('name')
            args.append(pname.text)

        callName = "encode_" + name

        return callName + "(" + ", ".join(args) + ")"

## Encoder definitions##########################################################

    def makeEncodeProto(self, cmdInfoElem, name):
        return self.makeFuncProto(
            cmdInfoElem, name, "encode_",
            extraArgs = ["void* vkStream"])

    def makeEncoderDef(self, cmdInfoElem, name):
        params = cmdInfoElem.findall('param')

        funcPrototype = \
            self.makeEncodeProto(cmdInfoElem, name)

        self.swapCode();

        self.beginBlock();

        retType = cmdInfoElem.find('proto').find('type').text

        if retType != "void":
            self.stmt("return (%s)0" % retType)

        self.endBlock();
        return funcPrototype + self.swapCode()

    def makeEncoderCall(self, cmdInfoElem, name):
        params = cmdInfoElem.findall('param')

        args = ["vkStream"]
        for p in params:
            ptype = p.find('type')
            pname = p.find('name')
            args.append(pname.text)

        callName = "encode_" + name

        return callName + "(" + ", ".join(args) + ")"


## Validate definitions#########################################################

    def makeValidateProto(self, cmdInfoElem, name):
        return self.makeFuncProto(
            cmdInfoElem, name, "validate_",
            extraArgs = ["VkResult* validateResult"],
            retTypeOverride = "void")

    def makeValidateDef(self, cmdInfoElem, name):
        params = cmdInfoElem.findall('param')

        funcPrototype = \
            "static " + \
            self.makeValidateProto(cmdInfoElem, name)

        self.swapCode();

        self.beginBlock();

        self.endBlock();
        return funcPrototype + self.swapCode()

    def makeValidateCall(self, cmdInfoElem, name):
        params = cmdInfoElem.findall('param')

        args = ["&validateResult"]
        for p in params:
            ptype = p.find('type')
            pname = p.find('name')
            args.append(pname.text)

        callName = "validate_" + name

        return callName + "(" + ", ".join(args) + ")"

## Frontend definitions#########################################################

    def makeFrontendProto(self, cmdInfoElem, name):
        return self.makeFuncProto(
            cmdInfoElem, name, "goldfish_frontend_")

    def makeFrontendDef(self, cmdInfoElem, name):

        prototype = self.makeFrontendProto(cmdInfoElem, name)

        self.swapCode()

        self.beginBlock()

        self.stmt("VkResult validateResult = VK_SUCCESS")

        retType = cmdInfoElem.find('proto').find('type').text

        self.stmt(self.makeValidateCall(cmdInfoElem, name))

        self.beginIf("validateResult != VK_SUCCESS")
        if retType == 'VkResult':
            self.stmt("return validateResult")
        elif retType != "void":
            self.stmt("return (%s)0" % retType)
        else:
            self.stmt("return")
        self.endIf()

        self.stmt("// VULKAN_STREAM_GET()")
        self.stmt("void* vkStream = 0")

        if retType != 'void':
            self.stmt(retType + " res = " + self.makeEncoderCall(cmdInfoElem, name))
            self.stmt("return res")
        else:
            self.stmt(self.makeEncoderCall(cmdInfoElem, name))

        self.endBlock()

        implBody = self.swapCode()
        res = prototype + implBody

        return res

## Overrides################3###################################################

    def beginFile(self, genOpts):
        OutputGenerator.beginFile(self, genOpts)

        write(self.cereal_Android_mk_header, file = self.outFile)

        write(self.cereal_Android_mk_body, file = self.outFile)

        self.forEachModule(lambda m: m.begin(self.genOpts.directory))

    def endFile(self):
        OutputGenerator.endFile(self)

        self.forEachModule(lambda m: m.end())

    def beginFeature(self, interface, emit):
        # Start processing in superclass
        OutputGenerator.beginFeature(self, interface, emit)

        self.forEachModule(lambda m: m.appendHeader("#ifdef %s\n" % self.featureName))
        self.forEachModule(lambda m: m.appendImpl("#ifdef %s\n" % self.featureName))

    def endFeature(self):
        # Finish processing in superclass
        OutputGenerator.endFeature(self)

        self.forEachModule(lambda m: m.appendHeader("#endif\n"))
        self.forEachModule(lambda m: m.appendImpl("#endif\n"))

    def genType(self, typeinfo, name, alias):
        OutputGenerator.genType(self, typeinfo, name, alias)
        #typeElem = typeinfo.elem

        ## Determine the category of the type, and the type section to add
        ## its definition to.
        ## 'funcpointer' is added to the 'struct' section as a workaround for
        ## internal issue #877, since structures and function pointer types
        ## can have cross-dependencies.
        #category = typeElem.get('category')
        #if category == 'funcpointer':
        #    section = 'struct'
        #else:
        #    section = category

        #if category == 'struct' or category == 'union':
        #    # If the type is a struct type, generate it using the
        #    # special-purpose generator.
        #    self.genStruct(typeinfo, name, alias)
        #else:
        #    if alias:
        #        # If the type is an alias, just emit a typedef declaration
        #        body = 'typedef ' + alias + ' ' + name + ';\n'
        #    else:
        #        # Replace <apientry /> tags with an APIENTRY-style string
        #        # (from self.genOpts). Copy other text through unchanged.
        #        # If the resulting text is an empty string, don't emit it.
        #        body = noneStr(typeElem.text)
        #        for elem in typeElem:
        #            if (elem.tag == 'apientry'):
        #                body += self.genOpts.apientry + noneStr(elem.tail)
        #            else:
        #                body += noneStr(elem.text) + noneStr(elem.tail)

        #    if body:
        #        # Add extra newline after multi-line entries.
        #        if '\n' in body[0:-1]:
        #            body += '\n'
        #        self.appendSection(section, body)
    #
    # Struct (e.g. C "struct" type) generation.
    # This is a special case of the <type> tag where the contents are
    # interpreted as a set of <member> tags instead of freeform C
    # C type declarations. The <member> tags are just like <param>
    # tags - they are a declaration of a struct or union member.
    # Only simple member declarations are supported (no nested
    # structs etc.)
    # If alias != None, then this struct aliases another; just
    #   generate a typedef of that alias.
    def genStruct(self, typeinfo, typeName, alias):
        OutputGenerator.genStruct(self, typeinfo, typeName, alias)

        #typeElem = typeinfo.elem

        #if alias:
        #    body = 'typedef ' + alias + ' ' + typeName + ';\n'
        #else:
        #    body = 'typedef ' + typeElem.get('category') + ' ' + typeName + ' {\n'

        #    targetLen = 0;
        #    for member in typeElem.findall('.//member'):
        #        targetLen = max(targetLen, self.getCParamTypeLength(member))
        #    for member in typeElem.findall('.//member'):
        #        body += self.makeCParamDecl(member, targetLen + 4)
        #        body += ';\n'
        #    body += '} ' + typeName + ';\n'

        #self.appendSection('struct', body)
    #
    # Group (e.g. C "enum" type) generation.
    # These are concatenated together with other types.
    # If alias != None, it is the name of another group type
    #   which aliases this type; just generate that alias.
    def genGroup(self, groupinfo, groupName, alias = None):
        OutputGenerator.genGroup(self, groupinfo, groupName, alias)
        #groupElem = groupinfo.elem

        #if alias:
        #    # If the group name is aliased, just emit a typedef declaration
        #    # for the alias.
        #    body = 'typedef ' + alias + ' ' + groupName + ';\n'
        #else:
        #    self.logMsg('diag', 'CGenerator.genGroup group =', groupName, 'alias =', alias)

        #    # Otherwise, emit an actual enumerated type declaration
        #    expandName = re.sub(r'([0-9a-z_])([A-Z0-9])',r'\1_\2',groupName).upper()

        #    expandPrefix = expandName
        #    expandSuffix = ''
        #    expandSuffixMatch = re.search(r'[A-Z][A-Z]+$',groupName)
        #    if expandSuffixMatch:
        #        expandSuffix = '_' + expandSuffixMatch.group()
        #        # Strip off the suffix from the prefix
        #        expandPrefix = expandName.rsplit(expandSuffix, 1)[0]

        #    # Prefix
        #    body = "\ntypedef enum " + groupName + " {\n"

        #    # @@ Should use the type="bitmask" attribute instead
        #    isEnum = ('FLAG_BITS' not in expandPrefix)

        #    # Get a list of nested 'enum' tags.
        #    enums = groupElem.findall('enum')

        #    # Check for and report duplicates, and return a list with them
        #    # removed.
        #    enums = self.checkDuplicateEnums(enums)

        #    # Loop over the nested 'enum' tags. Keep track of the minimum and
        #    # maximum numeric values, if they can be determined; but only for
        #    # core API enumerants, not extension enumerants. This is inferred
        #    # by looking for 'extends' attributes.
        #    minName = None

        #    # Accumulate non-numeric enumerant values separately and append
        #    # them following the numeric values, to allow for aliases.
        #    # NOTE: this doesn't do a topological sort yet, so aliases of
        #    # aliases can still get in the wrong order.
        #    aliasText = ""

        #    for elem in enums:
        #        # Convert the value to an integer and use that to track min/max.
        #        (numVal,strVal) = self.enumToValue(elem, True)
        #        name = elem.get('name')

        #        # Extension enumerants are only included if they are required
        #        if self.isEnumRequired(elem):
        #            decl = "    " + name + " = " + strVal + ",\n"
        #            if numVal != None:
        #                body += decl
        #            else:
        #                aliasText += decl

        #        # Don't track min/max for non-numbers (numVal == None)
        #        if isEnum and numVal != None and elem.get('extends') is None:
        #            if minName == None:
        #                minName = maxName = name
        #                minValue = maxValue = numVal
        #            elif numVal < minValue:
        #                minName = name
        #                minValue = numVal
        #            elif numVal > maxValue:
        #                maxName = name
        #                maxValue = numVal

        #    # Now append the non-numeric enumerant values
        #    body += aliasText

        #    # Generate min/max value tokens and a range-padding enum. Need some
        #    # additional padding to generate correct names...
        #    if isEnum:
        #        body += "    " + expandPrefix + "_BEGIN_RANGE" + expandSuffix + " = " + minName + ",\n"
        #        body += "    " + expandPrefix + "_END_RANGE" + expandSuffix + " = " + maxName + ",\n"
        #        body += "    " + expandPrefix + "_RANGE_SIZE" + expandSuffix + " = (" + maxName + " - " + minName + " + 1),\n"

        #    body += "    " + expandPrefix + "_MAX_ENUM" + expandSuffix + " = 0x7FFFFFFF\n"

        #    # Postfix
        #    body += "} " + groupName + ";"

        ## After either enumerated type or alias paths, add the declaration
        ## to the appropriate section for the group being defined.
        #if groupElem.get('type') == 'bitmask':
        #    section = 'bitmask'
        #else:
        #    section = 'group'
        #self.appendSection(section, body)

    # Enumerant generation
    # <enum> tags may specify their values in several ways, but are usually
    # just integers.
    def genEnum(self, enuminfo, name, alias):
        OutputGenerator.genEnum(self, enuminfo, name, alias)
        #(numVal,strVal) = self.enumToValue(enuminfo.elem, False)
        #body = '#define ' + name.ljust(33) + ' ' + strVal
        #self.appendSection('enum', body)

    def genCmd(self, cmdinfo, name, alias):
        OutputGenerator.genCmd(self, cmdinfo, name, alias)

        frontendDecl = self.makeFrontendProto(cmdinfo.elem, name) + ";\n"

        validateDef = self.makeValidateDef(cmdinfo.elem, name)
        frontendDef = self.makeFrontendDef(cmdinfo.elem, name)

        self.modules["goldfish_vk_frontend"].appendHeader(frontendDecl)
        self.modules["goldfish_vk_frontend"].appendImpl(validateDef)
        self.modules["goldfish_vk_frontend"].appendImpl(frontendDef)

        encoderDecl = self.makeEncodeProto(cmdinfo.elem, name) + ";\n"
        encoderDef = self.makeEncoderDef(cmdinfo.elem, name)

        self.modules["goldfish_vk_encoder"].appendHeader(encoderDecl)
        self.modules["goldfish_vk_encoder"].appendImpl(encoderDef)

        marshalingDecl = self.makeMarshalingProto(cmdinfo.elem, name) + ";\n"
        marshalingDef = self.makeMarshalingDef(cmdinfo.elem, name) + ";\n"

        self.modules["goldfish_vk_marshaling"].appendHeader(marshalingDecl)
        self.modules["goldfish_vk_marshaling"].appendImpl(marshalingDef)

