// Copyright (C) 2018 The Android Open Source Project
// Copyright (C) 2018 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Autogenerated module goldfish_vk_dispatch
// (impl) generated by android/android-emugl/host/libs/libOpenglRender/vulkan-registry/xml/genvk.py -registry android/android-emugl/host/libs/libOpenglRender/vulkan-registry/xml/vk.xml cereal -o android/android-emugl/host/libs/libOpenglRender/vulkan/cereal
// Please do not modify directly;
// re-run android/scripts/generate-vulkan-sources.sh,
// or directly from Python by defining:
// VULKAN_REGISTRY_XML_DIR : Directory containing genvk.py and vk.xml
// CEREAL_OUTPUT_DIR: Where to put the generated sources.
// python3 $VULKAN_REGISTRY_XML_DIR/genvk.py -registry $VULKAN_REGISTRY_XML_DIR/vk.xml cereal -o $CEREAL_OUTPUT_DIR

#include "goldfish_vk_dispatch.h"



namespace goldfish_vk {

#ifdef VK_VERSION_1_0
#endif
#ifdef VK_VERSION_1_1
#endif
#ifdef VK_KHR_surface
#endif
#ifdef VK_KHR_swapchain
#endif
#ifdef VK_KHR_display
#endif
#ifdef VK_KHR_display_swapchain
#endif
#ifdef VK_KHR_xlib_surface
#endif
#ifdef VK_KHR_xcb_surface
#endif
#ifdef VK_KHR_wayland_surface
#endif
#ifdef VK_KHR_mir_surface
#endif
#ifdef VK_KHR_android_surface
#endif
#ifdef VK_KHR_win32_surface
#endif
#ifdef VK_KHR_sampler_mirror_clamp_to_edge
#endif
#ifdef VK_KHR_multiview
#endif
#ifdef VK_KHR_get_physical_device_properties2
#endif
#ifdef VK_KHR_device_group
#endif
#ifdef VK_KHR_shader_draw_parameters
#endif
#ifdef VK_KHR_maintenance1
#endif
#ifdef VK_KHR_device_group_creation
#endif
#ifdef VK_KHR_external_memory_capabilities
#endif
#ifdef VK_KHR_external_memory
#endif
#ifdef VK_KHR_external_memory_win32
#endif
#ifdef VK_KHR_external_memory_fd
#endif
#ifdef VK_KHR_win32_keyed_mutex
#endif
#ifdef VK_KHR_external_semaphore_capabilities
#endif
#ifdef VK_KHR_external_semaphore
#endif
#ifdef VK_KHR_external_semaphore_win32
#endif
#ifdef VK_KHR_external_semaphore_fd
#endif
#ifdef VK_KHR_push_descriptor
#endif
#ifdef VK_KHR_16bit_storage
#endif
#ifdef VK_KHR_incremental_present
#endif
#ifdef VK_KHR_descriptor_update_template
#endif
#ifdef VK_KHR_create_renderpass2
#endif
#ifdef VK_KHR_shared_presentable_image
#endif
#ifdef VK_KHR_external_fence_capabilities
#endif
#ifdef VK_KHR_external_fence
#endif
#ifdef VK_KHR_external_fence_win32
#endif
#ifdef VK_KHR_external_fence_fd
#endif
#ifdef VK_KHR_maintenance2
#endif
#ifdef VK_KHR_get_surface_capabilities2
#endif
#ifdef VK_KHR_variable_pointers
#endif
#ifdef VK_KHR_get_display_properties2
#endif
#ifdef VK_KHR_dedicated_allocation
#endif
#ifdef VK_KHR_storage_buffer_storage_class
#endif
#ifdef VK_KHR_relaxed_block_layout
#endif
#ifdef VK_KHR_get_memory_requirements2
#endif
#ifdef VK_KHR_image_format_list
#endif
#ifdef VK_KHR_sampler_ycbcr_conversion
#endif
#ifdef VK_KHR_bind_memory2
#endif
#ifdef VK_KHR_maintenance3
#endif
#ifdef VK_KHR_draw_indirect_count
#endif
#ifdef VK_KHR_8bit_storage
#endif
#ifdef VK_EXT_debug_report
#endif
#ifdef VK_NV_glsl_shader
#endif
#ifdef VK_EXT_depth_range_unrestricted
#endif
#ifdef VK_IMG_filter_cubic
#endif
#ifdef VK_AMD_rasterization_order
#endif
#ifdef VK_AMD_shader_trinary_minmax
#endif
#ifdef VK_AMD_shader_explicit_vertex_parameter
#endif
#ifdef VK_EXT_debug_marker
#endif
#ifdef VK_AMD_gcn_shader
#endif
#ifdef VK_NV_dedicated_allocation
#endif
#ifdef VK_AMD_draw_indirect_count
#endif
#ifdef VK_AMD_negative_viewport_height
#endif
#ifdef VK_AMD_gpu_shader_half_float
#endif
#ifdef VK_AMD_shader_ballot
#endif
#ifdef VK_AMD_texture_gather_bias_lod
#endif
#ifdef VK_AMD_shader_info
#endif
#ifdef VK_AMD_shader_image_load_store_lod
#endif
#ifdef VK_IMG_format_pvrtc
#endif
#ifdef VK_NV_external_memory_capabilities
#endif
#ifdef VK_NV_external_memory
#endif
#ifdef VK_NV_external_memory_win32
#endif
#ifdef VK_NV_win32_keyed_mutex
#endif
#ifdef VK_EXT_validation_flags
#endif
#ifdef VK_NN_vi_surface
#endif
#ifdef VK_EXT_shader_subgroup_ballot
#endif
#ifdef VK_EXT_shader_subgroup_vote
#endif
#ifdef VK_EXT_conditional_rendering
#endif
#ifdef VK_NVX_device_generated_commands
#endif
#ifdef VK_NV_clip_space_w_scaling
#endif
#ifdef VK_EXT_direct_mode_display
#endif
#ifdef VK_EXT_acquire_xlib_display
#endif
#ifdef VK_EXT_display_surface_counter
#endif
#ifdef VK_EXT_display_control
#endif
#ifdef VK_GOOGLE_display_timing
#endif
#ifdef VK_NV_sample_mask_override_coverage
#endif
#ifdef VK_NV_geometry_shader_passthrough
#endif
#ifdef VK_NV_viewport_array2
#endif
#ifdef VK_NVX_multiview_per_view_attributes
#endif
#ifdef VK_NV_viewport_swizzle
#endif
#ifdef VK_EXT_discard_rectangles
#endif
#ifdef VK_EXT_conservative_rasterization
#endif
#ifdef VK_EXT_swapchain_colorspace
#endif
#ifdef VK_EXT_hdr_metadata
#endif
#ifdef VK_MVK_ios_surface
#endif
#ifdef VK_MVK_macos_surface
#endif
#ifdef VK_EXT_external_memory_dma_buf
#endif
#ifdef VK_EXT_queue_family_foreign
#endif
#ifdef VK_EXT_debug_utils
#endif
#ifdef VK_ANDROID_external_memory_android_hardware_buffer
#endif
#ifdef VK_EXT_sampler_filter_minmax
#endif
#ifdef VK_AMD_gpu_shader_int16
#endif
#ifdef VK_AMD_mixed_attachment_samples
#endif
#ifdef VK_AMD_shader_fragment_mask
#endif
#ifdef VK_EXT_shader_stencil_export
#endif
#ifdef VK_EXT_sample_locations
#endif
#ifdef VK_EXT_blend_operation_advanced
#endif
#ifdef VK_NV_fragment_coverage_to_color
#endif
#ifdef VK_NV_framebuffer_mixed_samples
#endif
#ifdef VK_NV_fill_rectangle
#endif
#ifdef VK_EXT_post_depth_coverage
#endif
#ifdef VK_EXT_validation_cache
#endif
#ifdef VK_EXT_descriptor_indexing
#endif
#ifdef VK_EXT_shader_viewport_index_layer
#endif
#ifdef VK_EXT_global_priority
#endif
#ifdef VK_EXT_external_memory_host
#endif
#ifdef VK_AMD_buffer_marker
#endif
#ifdef VK_AMD_shader_core_properties
#endif
#ifdef VK_EXT_vertex_attribute_divisor
#endif
#ifdef VK_NV_shader_subgroup_partitioned
#endif
#ifdef VK_NV_device_diagnostic_checkpoints
#endif

#ifdef _WIN32
#define VULKAN_LIB_NAME "vulkan-1"
else
#define VULKAN_LIB_NAME "vulkan"
#endif

void init_vulkan_dispatch_from_system_loader(
    DlOpenFunc dlOpenFunc,
    DlSymFunc dlSymFunc,
    InstanceGetter instanceGetter,
    DeviceGetter deviceGetter,
    VulkanDispatch* out)
{
    out->instance = nullptr;
    out->physicalDevice = nullptr;
    out->device = nullptr;
    out->graphicsQueue = nullptr;
    out->computeQueue = nullptr;
    out->presentQueue = nullptr;
    void* lib = dlOpenFunc();
    if (!lib) return;
#ifdef VK_VERSION_1_0
    out->vkGetInstanceProcAddr = (PFN_vkGetInstanceProcAddr)dlSymFunc(lib, "vkGetInstanceProcAddr");
#endif
    if (!out->vkGetInstanceProcAddr) return;
#ifdef VK_VERSION_1_0
    out->vkCreateInstance = (PFN_vkCreateInstance)out->vkGetInstanceProcAddr(nullptr, "vkCreateInstance");
    out->vkDestroyInstance = (PFN_vkDestroyInstance)out->vkGetInstanceProcAddr(nullptr, "vkDestroyInstance");
    out->vkEnumeratePhysicalDevices = (PFN_vkEnumeratePhysicalDevices)out->vkGetInstanceProcAddr(nullptr, "vkEnumeratePhysicalDevices");
    out->vkGetPhysicalDeviceFeatures = (PFN_vkGetPhysicalDeviceFeatures)out->vkGetInstanceProcAddr(nullptr, "vkGetPhysicalDeviceFeatures");
    out->vkGetPhysicalDeviceFormatProperties = (PFN_vkGetPhysicalDeviceFormatProperties)out->vkGetInstanceProcAddr(nullptr, "vkGetPhysicalDeviceFormatProperties");
    out->vkGetPhysicalDeviceImageFormatProperties = (PFN_vkGetPhysicalDeviceImageFormatProperties)out->vkGetInstanceProcAddr(nullptr, "vkGetPhysicalDeviceImageFormatProperties");
    out->vkGetPhysicalDeviceProperties = (PFN_vkGetPhysicalDeviceProperties)out->vkGetInstanceProcAddr(nullptr, "vkGetPhysicalDeviceProperties");
    out->vkGetPhysicalDeviceQueueFamilyProperties = (PFN_vkGetPhysicalDeviceQueueFamilyProperties)out->vkGetInstanceProcAddr(nullptr, "vkGetPhysicalDeviceQueueFamilyProperties");
    out->vkGetPhysicalDeviceMemoryProperties = (PFN_vkGetPhysicalDeviceMemoryProperties)out->vkGetInstanceProcAddr(nullptr, "vkGetPhysicalDeviceMemoryProperties");
    out->vkGetDeviceProcAddr = (PFN_vkGetDeviceProcAddr)out->vkGetInstanceProcAddr(nullptr, "vkGetDeviceProcAddr");
    out->vkCreateDevice = (PFN_vkCreateDevice)out->vkGetInstanceProcAddr(nullptr, "vkCreateDevice");
    out->vkDestroyDevice = (PFN_vkDestroyDevice)out->vkGetInstanceProcAddr(nullptr, "vkDestroyDevice");
    out->vkEnumerateInstanceExtensionProperties = (PFN_vkEnumerateInstanceExtensionProperties)out->vkGetInstanceProcAddr(nullptr, "vkEnumerateInstanceExtensionProperties");
    out->vkEnumerateDeviceExtensionProperties = (PFN_vkEnumerateDeviceExtensionProperties)out->vkGetInstanceProcAddr(nullptr, "vkEnumerateDeviceExtensionProperties");
    out->vkEnumerateInstanceLayerProperties = (PFN_vkEnumerateInstanceLayerProperties)out->vkGetInstanceProcAddr(nullptr, "vkEnumerateInstanceLayerProperties");
    out->vkEnumerateDeviceLayerProperties = (PFN_vkEnumerateDeviceLayerProperties)out->vkGetInstanceProcAddr(nullptr, "vkEnumerateDeviceLayerProperties");
    out->vkGetDeviceQueue = (PFN_vkGetDeviceQueue)out->vkGetInstanceProcAddr(nullptr, "vkGetDeviceQueue");
    out->vkQueueSubmit = (PFN_vkQueueSubmit)out->vkGetInstanceProcAddr(nullptr, "vkQueueSubmit");
    out->vkQueueWaitIdle = (PFN_vkQueueWaitIdle)out->vkGetInstanceProcAddr(nullptr, "vkQueueWaitIdle");
    out->vkDeviceWaitIdle = (PFN_vkDeviceWaitIdle)out->vkGetInstanceProcAddr(nullptr, "vkDeviceWaitIdle");
#endif
    if (!instanceGetter(out, &out->instance)) return;
#ifdef VK_VERSION_1_1
    out->vkEnumeratePhysicalDeviceGroups = (PFN_vkEnumeratePhysicalDeviceGroups)out->vkGetInstanceProcAddr(out->instance, "vkEnumeratePhysicalDeviceGroups");
#endif
#ifdef VK_KHR_surface
    out->vkDestroySurfaceKHR = (PFN_vkDestroySurfaceKHR)out->vkGetInstanceProcAddr(out->instance, "vkDestroySurfaceKHR");
#endif
#ifdef VK_KHR_swapchain
    out->vkCreateSwapchainKHR = (PFN_vkCreateSwapchainKHR)out->vkGetInstanceProcAddr(out->instance, "vkCreateSwapchainKHR");
    out->vkDestroySwapchainKHR = (PFN_vkDestroySwapchainKHR)out->vkGetInstanceProcAddr(out->instance, "vkDestroySwapchainKHR");
    out->vkGetSwapchainImagesKHR = (PFN_vkGetSwapchainImagesKHR)out->vkGetInstanceProcAddr(out->instance, "vkGetSwapchainImagesKHR");
    out->vkAcquireNextImageKHR = (PFN_vkAcquireNextImageKHR)out->vkGetInstanceProcAddr(out->instance, "vkAcquireNextImageKHR");
    out->vkQueuePresentKHR = (PFN_vkQueuePresentKHR)out->vkGetInstanceProcAddr(out->instance, "vkQueuePresentKHR");
#endif
#ifdef VK_KHR_display
    out->vkCreateDisplayPlaneSurfaceKHR = (PFN_vkCreateDisplayPlaneSurfaceKHR)out->vkGetInstanceProcAddr(out->instance, "vkCreateDisplayPlaneSurfaceKHR");
#endif
#ifdef VK_KHR_xlib_surface
    out->vkCreateXlibSurfaceKHR = (PFN_vkCreateXlibSurfaceKHR)out->vkGetInstanceProcAddr(out->instance, "vkCreateXlibSurfaceKHR");
    out->vkGetPhysicalDeviceXlibPresentationSupportKHR = (PFN_vkGetPhysicalDeviceXlibPresentationSupportKHR)out->vkGetInstanceProcAddr(out->instance, "vkGetPhysicalDeviceXlibPresentationSupportKHR");
#endif
#ifdef VK_KHR_xcb_surface
    out->vkCreateXcbSurfaceKHR = (PFN_vkCreateXcbSurfaceKHR)out->vkGetInstanceProcAddr(out->instance, "vkCreateXcbSurfaceKHR");
    out->vkGetPhysicalDeviceXcbPresentationSupportKHR = (PFN_vkGetPhysicalDeviceXcbPresentationSupportKHR)out->vkGetInstanceProcAddr(out->instance, "vkGetPhysicalDeviceXcbPresentationSupportKHR");
#endif
#ifdef VK_KHR_wayland_surface
    out->vkCreateWaylandSurfaceKHR = (PFN_vkCreateWaylandSurfaceKHR)out->vkGetInstanceProcAddr(out->instance, "vkCreateWaylandSurfaceKHR");
#endif
#ifdef VK_KHR_mir_surface
    out->vkCreateMirSurfaceKHR = (PFN_vkCreateMirSurfaceKHR)out->vkGetInstanceProcAddr(out->instance, "vkCreateMirSurfaceKHR");
#endif
#ifdef VK_KHR_android_surface
    out->vkCreateAndroidSurfaceKHR = (PFN_vkCreateAndroidSurfaceKHR)out->vkGetInstanceProcAddr(out->instance, "vkCreateAndroidSurfaceKHR");
#endif
#ifdef VK_KHR_win32_surface
    out->vkCreateWin32SurfaceKHR = (PFN_vkCreateWin32SurfaceKHR)out->vkGetInstanceProcAddr(out->instance, "vkCreateWin32SurfaceKHR");
    out->vkGetPhysicalDeviceWin32PresentationSupportKHR = (PFN_vkGetPhysicalDeviceWin32PresentationSupportKHR)out->vkGetInstanceProcAddr(out->instance, "vkGetPhysicalDeviceWin32PresentationSupportKHR");
#endif
#ifdef VK_KHR_device_group_creation
    out->vkEnumeratePhysicalDeviceGroupsKHR = (PFN_vkEnumeratePhysicalDeviceGroupsKHR)out->vkGetInstanceProcAddr(out->instance, "vkEnumeratePhysicalDeviceGroupsKHR");
#endif
#ifdef VK_EXT_debug_report
    out->vkCreateDebugReportCallbackEXT = (PFN_vkCreateDebugReportCallbackEXT)out->vkGetInstanceProcAddr(out->instance, "vkCreateDebugReportCallbackEXT");
    out->vkDestroyDebugReportCallbackEXT = (PFN_vkDestroyDebugReportCallbackEXT)out->vkGetInstanceProcAddr(out->instance, "vkDestroyDebugReportCallbackEXT");
    out->vkDebugReportMessageEXT = (PFN_vkDebugReportMessageEXT)out->vkGetInstanceProcAddr(out->instance, "vkDebugReportMessageEXT");
#endif
#ifdef VK_NN_vi_surface
    out->vkCreateViSurfaceNN = (PFN_vkCreateViSurfaceNN)out->vkGetInstanceProcAddr(out->instance, "vkCreateViSurfaceNN");
#endif
#ifdef VK_MVK_ios_surface
    out->vkCreateIOSSurfaceMVK = (PFN_vkCreateIOSSurfaceMVK)out->vkGetInstanceProcAddr(out->instance, "vkCreateIOSSurfaceMVK");
#endif
#ifdef VK_MVK_macos_surface
    out->vkCreateMacOSSurfaceMVK = (PFN_vkCreateMacOSSurfaceMVK)out->vkGetInstanceProcAddr(out->instance, "vkCreateMacOSSurfaceMVK");
#endif
#ifdef VK_EXT_debug_utils
    out->vkCreateDebugUtilsMessengerEXT = (PFN_vkCreateDebugUtilsMessengerEXT)out->vkGetInstanceProcAddr(out->instance, "vkCreateDebugUtilsMessengerEXT");
    out->vkDestroyDebugUtilsMessengerEXT = (PFN_vkDestroyDebugUtilsMessengerEXT)out->vkGetInstanceProcAddr(out->instance, "vkDestroyDebugUtilsMessengerEXT");
    out->vkSubmitDebugUtilsMessageEXT = (PFN_vkSubmitDebugUtilsMessageEXT)out->vkGetInstanceProcAddr(out->instance, "vkSubmitDebugUtilsMessageEXT");
#endif
    if (!deviceGetter(out, out->instance, &out->physicalDevice, &out->device)) return;
#ifdef VK_VERSION_1_0
    out->vkAllocateMemory = (PFN_vkAllocateMemory)out->vkGetDeviceProcAddr(out->device, "vkAllocateMemory");
    out->vkFreeMemory = (PFN_vkFreeMemory)out->vkGetDeviceProcAddr(out->device, "vkFreeMemory");
    out->vkMapMemory = (PFN_vkMapMemory)out->vkGetDeviceProcAddr(out->device, "vkMapMemory");
    out->vkUnmapMemory = (PFN_vkUnmapMemory)out->vkGetDeviceProcAddr(out->device, "vkUnmapMemory");
    out->vkFlushMappedMemoryRanges = (PFN_vkFlushMappedMemoryRanges)out->vkGetDeviceProcAddr(out->device, "vkFlushMappedMemoryRanges");
    out->vkInvalidateMappedMemoryRanges = (PFN_vkInvalidateMappedMemoryRanges)out->vkGetDeviceProcAddr(out->device, "vkInvalidateMappedMemoryRanges");
    out->vkGetDeviceMemoryCommitment = (PFN_vkGetDeviceMemoryCommitment)out->vkGetDeviceProcAddr(out->device, "vkGetDeviceMemoryCommitment");
    out->vkBindBufferMemory = (PFN_vkBindBufferMemory)out->vkGetDeviceProcAddr(out->device, "vkBindBufferMemory");
    out->vkBindImageMemory = (PFN_vkBindImageMemory)out->vkGetDeviceProcAddr(out->device, "vkBindImageMemory");
    out->vkGetBufferMemoryRequirements = (PFN_vkGetBufferMemoryRequirements)out->vkGetDeviceProcAddr(out->device, "vkGetBufferMemoryRequirements");
    out->vkGetImageMemoryRequirements = (PFN_vkGetImageMemoryRequirements)out->vkGetDeviceProcAddr(out->device, "vkGetImageMemoryRequirements");
    out->vkGetImageSparseMemoryRequirements = (PFN_vkGetImageSparseMemoryRequirements)out->vkGetDeviceProcAddr(out->device, "vkGetImageSparseMemoryRequirements");
    out->vkGetPhysicalDeviceSparseImageFormatProperties = (PFN_vkGetPhysicalDeviceSparseImageFormatProperties)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceSparseImageFormatProperties");
    out->vkQueueBindSparse = (PFN_vkQueueBindSparse)out->vkGetDeviceProcAddr(out->device, "vkQueueBindSparse");
    out->vkCreateFence = (PFN_vkCreateFence)out->vkGetDeviceProcAddr(out->device, "vkCreateFence");
    out->vkDestroyFence = (PFN_vkDestroyFence)out->vkGetDeviceProcAddr(out->device, "vkDestroyFence");
    out->vkResetFences = (PFN_vkResetFences)out->vkGetDeviceProcAddr(out->device, "vkResetFences");
    out->vkGetFenceStatus = (PFN_vkGetFenceStatus)out->vkGetDeviceProcAddr(out->device, "vkGetFenceStatus");
    out->vkWaitForFences = (PFN_vkWaitForFences)out->vkGetDeviceProcAddr(out->device, "vkWaitForFences");
    out->vkCreateSemaphore = (PFN_vkCreateSemaphore)out->vkGetDeviceProcAddr(out->device, "vkCreateSemaphore");
    out->vkDestroySemaphore = (PFN_vkDestroySemaphore)out->vkGetDeviceProcAddr(out->device, "vkDestroySemaphore");
    out->vkCreateEvent = (PFN_vkCreateEvent)out->vkGetDeviceProcAddr(out->device, "vkCreateEvent");
    out->vkDestroyEvent = (PFN_vkDestroyEvent)out->vkGetDeviceProcAddr(out->device, "vkDestroyEvent");
    out->vkGetEventStatus = (PFN_vkGetEventStatus)out->vkGetDeviceProcAddr(out->device, "vkGetEventStatus");
    out->vkSetEvent = (PFN_vkSetEvent)out->vkGetDeviceProcAddr(out->device, "vkSetEvent");
    out->vkResetEvent = (PFN_vkResetEvent)out->vkGetDeviceProcAddr(out->device, "vkResetEvent");
    out->vkCreateQueryPool = (PFN_vkCreateQueryPool)out->vkGetDeviceProcAddr(out->device, "vkCreateQueryPool");
    out->vkDestroyQueryPool = (PFN_vkDestroyQueryPool)out->vkGetDeviceProcAddr(out->device, "vkDestroyQueryPool");
    out->vkGetQueryPoolResults = (PFN_vkGetQueryPoolResults)out->vkGetDeviceProcAddr(out->device, "vkGetQueryPoolResults");
    out->vkCreateBuffer = (PFN_vkCreateBuffer)out->vkGetDeviceProcAddr(out->device, "vkCreateBuffer");
    out->vkDestroyBuffer = (PFN_vkDestroyBuffer)out->vkGetDeviceProcAddr(out->device, "vkDestroyBuffer");
    out->vkCreateBufferView = (PFN_vkCreateBufferView)out->vkGetDeviceProcAddr(out->device, "vkCreateBufferView");
    out->vkDestroyBufferView = (PFN_vkDestroyBufferView)out->vkGetDeviceProcAddr(out->device, "vkDestroyBufferView");
    out->vkCreateImage = (PFN_vkCreateImage)out->vkGetDeviceProcAddr(out->device, "vkCreateImage");
    out->vkDestroyImage = (PFN_vkDestroyImage)out->vkGetDeviceProcAddr(out->device, "vkDestroyImage");
    out->vkGetImageSubresourceLayout = (PFN_vkGetImageSubresourceLayout)out->vkGetDeviceProcAddr(out->device, "vkGetImageSubresourceLayout");
    out->vkCreateImageView = (PFN_vkCreateImageView)out->vkGetDeviceProcAddr(out->device, "vkCreateImageView");
    out->vkDestroyImageView = (PFN_vkDestroyImageView)out->vkGetDeviceProcAddr(out->device, "vkDestroyImageView");
    out->vkCreateShaderModule = (PFN_vkCreateShaderModule)out->vkGetDeviceProcAddr(out->device, "vkCreateShaderModule");
    out->vkDestroyShaderModule = (PFN_vkDestroyShaderModule)out->vkGetDeviceProcAddr(out->device, "vkDestroyShaderModule");
    out->vkCreatePipelineCache = (PFN_vkCreatePipelineCache)out->vkGetDeviceProcAddr(out->device, "vkCreatePipelineCache");
    out->vkDestroyPipelineCache = (PFN_vkDestroyPipelineCache)out->vkGetDeviceProcAddr(out->device, "vkDestroyPipelineCache");
    out->vkGetPipelineCacheData = (PFN_vkGetPipelineCacheData)out->vkGetDeviceProcAddr(out->device, "vkGetPipelineCacheData");
    out->vkMergePipelineCaches = (PFN_vkMergePipelineCaches)out->vkGetDeviceProcAddr(out->device, "vkMergePipelineCaches");
    out->vkCreateGraphicsPipelines = (PFN_vkCreateGraphicsPipelines)out->vkGetDeviceProcAddr(out->device, "vkCreateGraphicsPipelines");
    out->vkCreateComputePipelines = (PFN_vkCreateComputePipelines)out->vkGetDeviceProcAddr(out->device, "vkCreateComputePipelines");
    out->vkDestroyPipeline = (PFN_vkDestroyPipeline)out->vkGetDeviceProcAddr(out->device, "vkDestroyPipeline");
    out->vkCreatePipelineLayout = (PFN_vkCreatePipelineLayout)out->vkGetDeviceProcAddr(out->device, "vkCreatePipelineLayout");
    out->vkDestroyPipelineLayout = (PFN_vkDestroyPipelineLayout)out->vkGetDeviceProcAddr(out->device, "vkDestroyPipelineLayout");
    out->vkCreateSampler = (PFN_vkCreateSampler)out->vkGetDeviceProcAddr(out->device, "vkCreateSampler");
    out->vkDestroySampler = (PFN_vkDestroySampler)out->vkGetDeviceProcAddr(out->device, "vkDestroySampler");
    out->vkCreateDescriptorSetLayout = (PFN_vkCreateDescriptorSetLayout)out->vkGetDeviceProcAddr(out->device, "vkCreateDescriptorSetLayout");
    out->vkDestroyDescriptorSetLayout = (PFN_vkDestroyDescriptorSetLayout)out->vkGetDeviceProcAddr(out->device, "vkDestroyDescriptorSetLayout");
    out->vkCreateDescriptorPool = (PFN_vkCreateDescriptorPool)out->vkGetDeviceProcAddr(out->device, "vkCreateDescriptorPool");
    out->vkDestroyDescriptorPool = (PFN_vkDestroyDescriptorPool)out->vkGetDeviceProcAddr(out->device, "vkDestroyDescriptorPool");
    out->vkResetDescriptorPool = (PFN_vkResetDescriptorPool)out->vkGetDeviceProcAddr(out->device, "vkResetDescriptorPool");
    out->vkAllocateDescriptorSets = (PFN_vkAllocateDescriptorSets)out->vkGetDeviceProcAddr(out->device, "vkAllocateDescriptorSets");
    out->vkFreeDescriptorSets = (PFN_vkFreeDescriptorSets)out->vkGetDeviceProcAddr(out->device, "vkFreeDescriptorSets");
    out->vkUpdateDescriptorSets = (PFN_vkUpdateDescriptorSets)out->vkGetDeviceProcAddr(out->device, "vkUpdateDescriptorSets");
    out->vkCreateFramebuffer = (PFN_vkCreateFramebuffer)out->vkGetDeviceProcAddr(out->device, "vkCreateFramebuffer");
    out->vkDestroyFramebuffer = (PFN_vkDestroyFramebuffer)out->vkGetDeviceProcAddr(out->device, "vkDestroyFramebuffer");
    out->vkCreateRenderPass = (PFN_vkCreateRenderPass)out->vkGetDeviceProcAddr(out->device, "vkCreateRenderPass");
    out->vkDestroyRenderPass = (PFN_vkDestroyRenderPass)out->vkGetDeviceProcAddr(out->device, "vkDestroyRenderPass");
    out->vkGetRenderAreaGranularity = (PFN_vkGetRenderAreaGranularity)out->vkGetDeviceProcAddr(out->device, "vkGetRenderAreaGranularity");
    out->vkCreateCommandPool = (PFN_vkCreateCommandPool)out->vkGetDeviceProcAddr(out->device, "vkCreateCommandPool");
    out->vkDestroyCommandPool = (PFN_vkDestroyCommandPool)out->vkGetDeviceProcAddr(out->device, "vkDestroyCommandPool");
    out->vkResetCommandPool = (PFN_vkResetCommandPool)out->vkGetDeviceProcAddr(out->device, "vkResetCommandPool");
    out->vkAllocateCommandBuffers = (PFN_vkAllocateCommandBuffers)out->vkGetDeviceProcAddr(out->device, "vkAllocateCommandBuffers");
    out->vkFreeCommandBuffers = (PFN_vkFreeCommandBuffers)out->vkGetDeviceProcAddr(out->device, "vkFreeCommandBuffers");
    out->vkBeginCommandBuffer = (PFN_vkBeginCommandBuffer)out->vkGetDeviceProcAddr(out->device, "vkBeginCommandBuffer");
    out->vkEndCommandBuffer = (PFN_vkEndCommandBuffer)out->vkGetDeviceProcAddr(out->device, "vkEndCommandBuffer");
    out->vkResetCommandBuffer = (PFN_vkResetCommandBuffer)out->vkGetDeviceProcAddr(out->device, "vkResetCommandBuffer");
    out->vkCmdBindPipeline = (PFN_vkCmdBindPipeline)out->vkGetDeviceProcAddr(out->device, "vkCmdBindPipeline");
    out->vkCmdSetViewport = (PFN_vkCmdSetViewport)out->vkGetDeviceProcAddr(out->device, "vkCmdSetViewport");
    out->vkCmdSetScissor = (PFN_vkCmdSetScissor)out->vkGetDeviceProcAddr(out->device, "vkCmdSetScissor");
    out->vkCmdSetLineWidth = (PFN_vkCmdSetLineWidth)out->vkGetDeviceProcAddr(out->device, "vkCmdSetLineWidth");
    out->vkCmdSetDepthBias = (PFN_vkCmdSetDepthBias)out->vkGetDeviceProcAddr(out->device, "vkCmdSetDepthBias");
    out->vkCmdSetBlendConstants = (PFN_vkCmdSetBlendConstants)out->vkGetDeviceProcAddr(out->device, "vkCmdSetBlendConstants");
    out->vkCmdSetDepthBounds = (PFN_vkCmdSetDepthBounds)out->vkGetDeviceProcAddr(out->device, "vkCmdSetDepthBounds");
    out->vkCmdSetStencilCompareMask = (PFN_vkCmdSetStencilCompareMask)out->vkGetDeviceProcAddr(out->device, "vkCmdSetStencilCompareMask");
    out->vkCmdSetStencilWriteMask = (PFN_vkCmdSetStencilWriteMask)out->vkGetDeviceProcAddr(out->device, "vkCmdSetStencilWriteMask");
    out->vkCmdSetStencilReference = (PFN_vkCmdSetStencilReference)out->vkGetDeviceProcAddr(out->device, "vkCmdSetStencilReference");
    out->vkCmdBindDescriptorSets = (PFN_vkCmdBindDescriptorSets)out->vkGetDeviceProcAddr(out->device, "vkCmdBindDescriptorSets");
    out->vkCmdBindIndexBuffer = (PFN_vkCmdBindIndexBuffer)out->vkGetDeviceProcAddr(out->device, "vkCmdBindIndexBuffer");
    out->vkCmdBindVertexBuffers = (PFN_vkCmdBindVertexBuffers)out->vkGetDeviceProcAddr(out->device, "vkCmdBindVertexBuffers");
    out->vkCmdDraw = (PFN_vkCmdDraw)out->vkGetDeviceProcAddr(out->device, "vkCmdDraw");
    out->vkCmdDrawIndexed = (PFN_vkCmdDrawIndexed)out->vkGetDeviceProcAddr(out->device, "vkCmdDrawIndexed");
    out->vkCmdDrawIndirect = (PFN_vkCmdDrawIndirect)out->vkGetDeviceProcAddr(out->device, "vkCmdDrawIndirect");
    out->vkCmdDrawIndexedIndirect = (PFN_vkCmdDrawIndexedIndirect)out->vkGetDeviceProcAddr(out->device, "vkCmdDrawIndexedIndirect");
    out->vkCmdDispatch = (PFN_vkCmdDispatch)out->vkGetDeviceProcAddr(out->device, "vkCmdDispatch");
    out->vkCmdDispatchIndirect = (PFN_vkCmdDispatchIndirect)out->vkGetDeviceProcAddr(out->device, "vkCmdDispatchIndirect");
    out->vkCmdCopyBuffer = (PFN_vkCmdCopyBuffer)out->vkGetDeviceProcAddr(out->device, "vkCmdCopyBuffer");
    out->vkCmdCopyImage = (PFN_vkCmdCopyImage)out->vkGetDeviceProcAddr(out->device, "vkCmdCopyImage");
    out->vkCmdBlitImage = (PFN_vkCmdBlitImage)out->vkGetDeviceProcAddr(out->device, "vkCmdBlitImage");
    out->vkCmdCopyBufferToImage = (PFN_vkCmdCopyBufferToImage)out->vkGetDeviceProcAddr(out->device, "vkCmdCopyBufferToImage");
    out->vkCmdCopyImageToBuffer = (PFN_vkCmdCopyImageToBuffer)out->vkGetDeviceProcAddr(out->device, "vkCmdCopyImageToBuffer");
    out->vkCmdUpdateBuffer = (PFN_vkCmdUpdateBuffer)out->vkGetDeviceProcAddr(out->device, "vkCmdUpdateBuffer");
    out->vkCmdFillBuffer = (PFN_vkCmdFillBuffer)out->vkGetDeviceProcAddr(out->device, "vkCmdFillBuffer");
    out->vkCmdClearColorImage = (PFN_vkCmdClearColorImage)out->vkGetDeviceProcAddr(out->device, "vkCmdClearColorImage");
    out->vkCmdClearDepthStencilImage = (PFN_vkCmdClearDepthStencilImage)out->vkGetDeviceProcAddr(out->device, "vkCmdClearDepthStencilImage");
    out->vkCmdClearAttachments = (PFN_vkCmdClearAttachments)out->vkGetDeviceProcAddr(out->device, "vkCmdClearAttachments");
    out->vkCmdResolveImage = (PFN_vkCmdResolveImage)out->vkGetDeviceProcAddr(out->device, "vkCmdResolveImage");
    out->vkCmdSetEvent = (PFN_vkCmdSetEvent)out->vkGetDeviceProcAddr(out->device, "vkCmdSetEvent");
    out->vkCmdResetEvent = (PFN_vkCmdResetEvent)out->vkGetDeviceProcAddr(out->device, "vkCmdResetEvent");
    out->vkCmdWaitEvents = (PFN_vkCmdWaitEvents)out->vkGetDeviceProcAddr(out->device, "vkCmdWaitEvents");
    out->vkCmdPipelineBarrier = (PFN_vkCmdPipelineBarrier)out->vkGetDeviceProcAddr(out->device, "vkCmdPipelineBarrier");
    out->vkCmdBeginQuery = (PFN_vkCmdBeginQuery)out->vkGetDeviceProcAddr(out->device, "vkCmdBeginQuery");
    out->vkCmdEndQuery = (PFN_vkCmdEndQuery)out->vkGetDeviceProcAddr(out->device, "vkCmdEndQuery");
    out->vkCmdResetQueryPool = (PFN_vkCmdResetQueryPool)out->vkGetDeviceProcAddr(out->device, "vkCmdResetQueryPool");
    out->vkCmdWriteTimestamp = (PFN_vkCmdWriteTimestamp)out->vkGetDeviceProcAddr(out->device, "vkCmdWriteTimestamp");
    out->vkCmdCopyQueryPoolResults = (PFN_vkCmdCopyQueryPoolResults)out->vkGetDeviceProcAddr(out->device, "vkCmdCopyQueryPoolResults");
    out->vkCmdPushConstants = (PFN_vkCmdPushConstants)out->vkGetDeviceProcAddr(out->device, "vkCmdPushConstants");
    out->vkCmdBeginRenderPass = (PFN_vkCmdBeginRenderPass)out->vkGetDeviceProcAddr(out->device, "vkCmdBeginRenderPass");
    out->vkCmdNextSubpass = (PFN_vkCmdNextSubpass)out->vkGetDeviceProcAddr(out->device, "vkCmdNextSubpass");
    out->vkCmdEndRenderPass = (PFN_vkCmdEndRenderPass)out->vkGetDeviceProcAddr(out->device, "vkCmdEndRenderPass");
    out->vkCmdExecuteCommands = (PFN_vkCmdExecuteCommands)out->vkGetDeviceProcAddr(out->device, "vkCmdExecuteCommands");
#endif
#ifdef VK_VERSION_1_1
    out->vkEnumerateInstanceVersion = (PFN_vkEnumerateInstanceVersion)out->vkGetDeviceProcAddr(out->device, "vkEnumerateInstanceVersion");
    out->vkBindBufferMemory2 = (PFN_vkBindBufferMemory2)out->vkGetDeviceProcAddr(out->device, "vkBindBufferMemory2");
    out->vkBindImageMemory2 = (PFN_vkBindImageMemory2)out->vkGetDeviceProcAddr(out->device, "vkBindImageMemory2");
    out->vkGetDeviceGroupPeerMemoryFeatures = (PFN_vkGetDeviceGroupPeerMemoryFeatures)out->vkGetDeviceProcAddr(out->device, "vkGetDeviceGroupPeerMemoryFeatures");
    out->vkCmdSetDeviceMask = (PFN_vkCmdSetDeviceMask)out->vkGetDeviceProcAddr(out->device, "vkCmdSetDeviceMask");
    out->vkCmdDispatchBase = (PFN_vkCmdDispatchBase)out->vkGetDeviceProcAddr(out->device, "vkCmdDispatchBase");
    out->vkGetImageMemoryRequirements2 = (PFN_vkGetImageMemoryRequirements2)out->vkGetDeviceProcAddr(out->device, "vkGetImageMemoryRequirements2");
    out->vkGetBufferMemoryRequirements2 = (PFN_vkGetBufferMemoryRequirements2)out->vkGetDeviceProcAddr(out->device, "vkGetBufferMemoryRequirements2");
    out->vkGetImageSparseMemoryRequirements2 = (PFN_vkGetImageSparseMemoryRequirements2)out->vkGetDeviceProcAddr(out->device, "vkGetImageSparseMemoryRequirements2");
    out->vkGetPhysicalDeviceFeatures2 = (PFN_vkGetPhysicalDeviceFeatures2)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceFeatures2");
    out->vkGetPhysicalDeviceProperties2 = (PFN_vkGetPhysicalDeviceProperties2)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceProperties2");
    out->vkGetPhysicalDeviceFormatProperties2 = (PFN_vkGetPhysicalDeviceFormatProperties2)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceFormatProperties2");
    out->vkGetPhysicalDeviceImageFormatProperties2 = (PFN_vkGetPhysicalDeviceImageFormatProperties2)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceImageFormatProperties2");
    out->vkGetPhysicalDeviceQueueFamilyProperties2 = (PFN_vkGetPhysicalDeviceQueueFamilyProperties2)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceQueueFamilyProperties2");
    out->vkGetPhysicalDeviceMemoryProperties2 = (PFN_vkGetPhysicalDeviceMemoryProperties2)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceMemoryProperties2");
    out->vkGetPhysicalDeviceSparseImageFormatProperties2 = (PFN_vkGetPhysicalDeviceSparseImageFormatProperties2)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceSparseImageFormatProperties2");
    out->vkTrimCommandPool = (PFN_vkTrimCommandPool)out->vkGetDeviceProcAddr(out->device, "vkTrimCommandPool");
    out->vkGetDeviceQueue2 = (PFN_vkGetDeviceQueue2)out->vkGetDeviceProcAddr(out->device, "vkGetDeviceQueue2");
    out->vkCreateSamplerYcbcrConversion = (PFN_vkCreateSamplerYcbcrConversion)out->vkGetDeviceProcAddr(out->device, "vkCreateSamplerYcbcrConversion");
    out->vkDestroySamplerYcbcrConversion = (PFN_vkDestroySamplerYcbcrConversion)out->vkGetDeviceProcAddr(out->device, "vkDestroySamplerYcbcrConversion");
    out->vkCreateDescriptorUpdateTemplate = (PFN_vkCreateDescriptorUpdateTemplate)out->vkGetDeviceProcAddr(out->device, "vkCreateDescriptorUpdateTemplate");
    out->vkDestroyDescriptorUpdateTemplate = (PFN_vkDestroyDescriptorUpdateTemplate)out->vkGetDeviceProcAddr(out->device, "vkDestroyDescriptorUpdateTemplate");
    out->vkUpdateDescriptorSetWithTemplate = (PFN_vkUpdateDescriptorSetWithTemplate)out->vkGetDeviceProcAddr(out->device, "vkUpdateDescriptorSetWithTemplate");
    out->vkGetPhysicalDeviceExternalBufferProperties = (PFN_vkGetPhysicalDeviceExternalBufferProperties)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceExternalBufferProperties");
    out->vkGetPhysicalDeviceExternalFenceProperties = (PFN_vkGetPhysicalDeviceExternalFenceProperties)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceExternalFenceProperties");
    out->vkGetPhysicalDeviceExternalSemaphoreProperties = (PFN_vkGetPhysicalDeviceExternalSemaphoreProperties)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceExternalSemaphoreProperties");
    out->vkGetDescriptorSetLayoutSupport = (PFN_vkGetDescriptorSetLayoutSupport)out->vkGetDeviceProcAddr(out->device, "vkGetDescriptorSetLayoutSupport");
#endif
#ifdef VK_KHR_surface
    out->vkGetPhysicalDeviceSurfaceSupportKHR = (PFN_vkGetPhysicalDeviceSurfaceSupportKHR)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceSurfaceSupportKHR");
    out->vkGetPhysicalDeviceSurfaceCapabilitiesKHR = (PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceSurfaceCapabilitiesKHR");
    out->vkGetPhysicalDeviceSurfaceFormatsKHR = (PFN_vkGetPhysicalDeviceSurfaceFormatsKHR)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceSurfaceFormatsKHR");
    out->vkGetPhysicalDeviceSurfacePresentModesKHR = (PFN_vkGetPhysicalDeviceSurfacePresentModesKHR)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceSurfacePresentModesKHR");
#endif
#ifdef VK_KHR_swapchain
    out->vkGetDeviceGroupPresentCapabilitiesKHR = (PFN_vkGetDeviceGroupPresentCapabilitiesKHR)out->vkGetDeviceProcAddr(out->device, "vkGetDeviceGroupPresentCapabilitiesKHR");
    out->vkGetDeviceGroupSurfacePresentModesKHR = (PFN_vkGetDeviceGroupSurfacePresentModesKHR)out->vkGetDeviceProcAddr(out->device, "vkGetDeviceGroupSurfacePresentModesKHR");
    out->vkGetPhysicalDevicePresentRectanglesKHR = (PFN_vkGetPhysicalDevicePresentRectanglesKHR)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDevicePresentRectanglesKHR");
    out->vkAcquireNextImage2KHR = (PFN_vkAcquireNextImage2KHR)out->vkGetDeviceProcAddr(out->device, "vkAcquireNextImage2KHR");
#endif
#ifdef VK_KHR_display
    out->vkGetPhysicalDeviceDisplayPropertiesKHR = (PFN_vkGetPhysicalDeviceDisplayPropertiesKHR)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceDisplayPropertiesKHR");
    out->vkGetPhysicalDeviceDisplayPlanePropertiesKHR = (PFN_vkGetPhysicalDeviceDisplayPlanePropertiesKHR)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceDisplayPlanePropertiesKHR");
    out->vkGetDisplayPlaneSupportedDisplaysKHR = (PFN_vkGetDisplayPlaneSupportedDisplaysKHR)out->vkGetDeviceProcAddr(out->device, "vkGetDisplayPlaneSupportedDisplaysKHR");
    out->vkGetDisplayModePropertiesKHR = (PFN_vkGetDisplayModePropertiesKHR)out->vkGetDeviceProcAddr(out->device, "vkGetDisplayModePropertiesKHR");
    out->vkCreateDisplayModeKHR = (PFN_vkCreateDisplayModeKHR)out->vkGetDeviceProcAddr(out->device, "vkCreateDisplayModeKHR");
    out->vkGetDisplayPlaneCapabilitiesKHR = (PFN_vkGetDisplayPlaneCapabilitiesKHR)out->vkGetDeviceProcAddr(out->device, "vkGetDisplayPlaneCapabilitiesKHR");
#endif
#ifdef VK_KHR_display_swapchain
    out->vkCreateSharedSwapchainsKHR = (PFN_vkCreateSharedSwapchainsKHR)out->vkGetDeviceProcAddr(out->device, "vkCreateSharedSwapchainsKHR");
#endif
#ifdef VK_KHR_wayland_surface
    out->vkGetPhysicalDeviceWaylandPresentationSupportKHR = (PFN_vkGetPhysicalDeviceWaylandPresentationSupportKHR)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceWaylandPresentationSupportKHR");
#endif
#ifdef VK_KHR_mir_surface
    out->vkGetPhysicalDeviceMirPresentationSupportKHR = (PFN_vkGetPhysicalDeviceMirPresentationSupportKHR)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceMirPresentationSupportKHR");
#endif
#ifdef VK_KHR_get_physical_device_properties2
    out->vkGetPhysicalDeviceFeatures2KHR = (PFN_vkGetPhysicalDeviceFeatures2KHR)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceFeatures2KHR");
    out->vkGetPhysicalDeviceProperties2KHR = (PFN_vkGetPhysicalDeviceProperties2KHR)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceProperties2KHR");
    out->vkGetPhysicalDeviceFormatProperties2KHR = (PFN_vkGetPhysicalDeviceFormatProperties2KHR)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceFormatProperties2KHR");
    out->vkGetPhysicalDeviceImageFormatProperties2KHR = (PFN_vkGetPhysicalDeviceImageFormatProperties2KHR)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceImageFormatProperties2KHR");
    out->vkGetPhysicalDeviceQueueFamilyProperties2KHR = (PFN_vkGetPhysicalDeviceQueueFamilyProperties2KHR)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceQueueFamilyProperties2KHR");
    out->vkGetPhysicalDeviceMemoryProperties2KHR = (PFN_vkGetPhysicalDeviceMemoryProperties2KHR)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceMemoryProperties2KHR");
    out->vkGetPhysicalDeviceSparseImageFormatProperties2KHR = (PFN_vkGetPhysicalDeviceSparseImageFormatProperties2KHR)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceSparseImageFormatProperties2KHR");
#endif
#ifdef VK_KHR_device_group
    out->vkGetDeviceGroupPeerMemoryFeaturesKHR = (PFN_vkGetDeviceGroupPeerMemoryFeaturesKHR)out->vkGetDeviceProcAddr(out->device, "vkGetDeviceGroupPeerMemoryFeaturesKHR");
    out->vkCmdSetDeviceMaskKHR = (PFN_vkCmdSetDeviceMaskKHR)out->vkGetDeviceProcAddr(out->device, "vkCmdSetDeviceMaskKHR");
    out->vkCmdDispatchBaseKHR = (PFN_vkCmdDispatchBaseKHR)out->vkGetDeviceProcAddr(out->device, "vkCmdDispatchBaseKHR");
#endif
#ifdef VK_KHR_maintenance1
    out->vkTrimCommandPoolKHR = (PFN_vkTrimCommandPoolKHR)out->vkGetDeviceProcAddr(out->device, "vkTrimCommandPoolKHR");
#endif
#ifdef VK_KHR_external_memory_capabilities
    out->vkGetPhysicalDeviceExternalBufferPropertiesKHR = (PFN_vkGetPhysicalDeviceExternalBufferPropertiesKHR)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceExternalBufferPropertiesKHR");
#endif
#ifdef VK_KHR_external_memory_win32
    out->vkGetMemoryWin32HandleKHR = (PFN_vkGetMemoryWin32HandleKHR)out->vkGetDeviceProcAddr(out->device, "vkGetMemoryWin32HandleKHR");
    out->vkGetMemoryWin32HandlePropertiesKHR = (PFN_vkGetMemoryWin32HandlePropertiesKHR)out->vkGetDeviceProcAddr(out->device, "vkGetMemoryWin32HandlePropertiesKHR");
#endif
#ifdef VK_KHR_external_memory_fd
    out->vkGetMemoryFdKHR = (PFN_vkGetMemoryFdKHR)out->vkGetDeviceProcAddr(out->device, "vkGetMemoryFdKHR");
    out->vkGetMemoryFdPropertiesKHR = (PFN_vkGetMemoryFdPropertiesKHR)out->vkGetDeviceProcAddr(out->device, "vkGetMemoryFdPropertiesKHR");
#endif
#ifdef VK_KHR_external_semaphore_capabilities
    out->vkGetPhysicalDeviceExternalSemaphorePropertiesKHR = (PFN_vkGetPhysicalDeviceExternalSemaphorePropertiesKHR)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceExternalSemaphorePropertiesKHR");
#endif
#ifdef VK_KHR_external_semaphore_win32
    out->vkImportSemaphoreWin32HandleKHR = (PFN_vkImportSemaphoreWin32HandleKHR)out->vkGetDeviceProcAddr(out->device, "vkImportSemaphoreWin32HandleKHR");
    out->vkGetSemaphoreWin32HandleKHR = (PFN_vkGetSemaphoreWin32HandleKHR)out->vkGetDeviceProcAddr(out->device, "vkGetSemaphoreWin32HandleKHR");
#endif
#ifdef VK_KHR_external_semaphore_fd
    out->vkImportSemaphoreFdKHR = (PFN_vkImportSemaphoreFdKHR)out->vkGetDeviceProcAddr(out->device, "vkImportSemaphoreFdKHR");
    out->vkGetSemaphoreFdKHR = (PFN_vkGetSemaphoreFdKHR)out->vkGetDeviceProcAddr(out->device, "vkGetSemaphoreFdKHR");
#endif
#ifdef VK_KHR_push_descriptor
    out->vkCmdPushDescriptorSetKHR = (PFN_vkCmdPushDescriptorSetKHR)out->vkGetDeviceProcAddr(out->device, "vkCmdPushDescriptorSetKHR");
    out->vkCmdPushDescriptorSetWithTemplateKHR = (PFN_vkCmdPushDescriptorSetWithTemplateKHR)out->vkGetDeviceProcAddr(out->device, "vkCmdPushDescriptorSetWithTemplateKHR");
#endif
#ifdef VK_KHR_descriptor_update_template
    out->vkCreateDescriptorUpdateTemplateKHR = (PFN_vkCreateDescriptorUpdateTemplateKHR)out->vkGetDeviceProcAddr(out->device, "vkCreateDescriptorUpdateTemplateKHR");
    out->vkDestroyDescriptorUpdateTemplateKHR = (PFN_vkDestroyDescriptorUpdateTemplateKHR)out->vkGetDeviceProcAddr(out->device, "vkDestroyDescriptorUpdateTemplateKHR");
    out->vkUpdateDescriptorSetWithTemplateKHR = (PFN_vkUpdateDescriptorSetWithTemplateKHR)out->vkGetDeviceProcAddr(out->device, "vkUpdateDescriptorSetWithTemplateKHR");
#endif
#ifdef VK_KHR_create_renderpass2
    out->vkCreateRenderPass2KHR = (PFN_vkCreateRenderPass2KHR)out->vkGetDeviceProcAddr(out->device, "vkCreateRenderPass2KHR");
    out->vkCmdBeginRenderPass2KHR = (PFN_vkCmdBeginRenderPass2KHR)out->vkGetDeviceProcAddr(out->device, "vkCmdBeginRenderPass2KHR");
    out->vkCmdNextSubpass2KHR = (PFN_vkCmdNextSubpass2KHR)out->vkGetDeviceProcAddr(out->device, "vkCmdNextSubpass2KHR");
    out->vkCmdEndRenderPass2KHR = (PFN_vkCmdEndRenderPass2KHR)out->vkGetDeviceProcAddr(out->device, "vkCmdEndRenderPass2KHR");
#endif
#ifdef VK_KHR_shared_presentable_image
    out->vkGetSwapchainStatusKHR = (PFN_vkGetSwapchainStatusKHR)out->vkGetDeviceProcAddr(out->device, "vkGetSwapchainStatusKHR");
#endif
#ifdef VK_KHR_external_fence_capabilities
    out->vkGetPhysicalDeviceExternalFencePropertiesKHR = (PFN_vkGetPhysicalDeviceExternalFencePropertiesKHR)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceExternalFencePropertiesKHR");
#endif
#ifdef VK_KHR_external_fence_win32
    out->vkImportFenceWin32HandleKHR = (PFN_vkImportFenceWin32HandleKHR)out->vkGetDeviceProcAddr(out->device, "vkImportFenceWin32HandleKHR");
    out->vkGetFenceWin32HandleKHR = (PFN_vkGetFenceWin32HandleKHR)out->vkGetDeviceProcAddr(out->device, "vkGetFenceWin32HandleKHR");
#endif
#ifdef VK_KHR_external_fence_fd
    out->vkImportFenceFdKHR = (PFN_vkImportFenceFdKHR)out->vkGetDeviceProcAddr(out->device, "vkImportFenceFdKHR");
    out->vkGetFenceFdKHR = (PFN_vkGetFenceFdKHR)out->vkGetDeviceProcAddr(out->device, "vkGetFenceFdKHR");
#endif
#ifdef VK_KHR_get_surface_capabilities2
    out->vkGetPhysicalDeviceSurfaceCapabilities2KHR = (PFN_vkGetPhysicalDeviceSurfaceCapabilities2KHR)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceSurfaceCapabilities2KHR");
    out->vkGetPhysicalDeviceSurfaceFormats2KHR = (PFN_vkGetPhysicalDeviceSurfaceFormats2KHR)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceSurfaceFormats2KHR");
#endif
#ifdef VK_KHR_get_display_properties2
    out->vkGetPhysicalDeviceDisplayProperties2KHR = (PFN_vkGetPhysicalDeviceDisplayProperties2KHR)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceDisplayProperties2KHR");
    out->vkGetPhysicalDeviceDisplayPlaneProperties2KHR = (PFN_vkGetPhysicalDeviceDisplayPlaneProperties2KHR)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceDisplayPlaneProperties2KHR");
    out->vkGetDisplayModeProperties2KHR = (PFN_vkGetDisplayModeProperties2KHR)out->vkGetDeviceProcAddr(out->device, "vkGetDisplayModeProperties2KHR");
    out->vkGetDisplayPlaneCapabilities2KHR = (PFN_vkGetDisplayPlaneCapabilities2KHR)out->vkGetDeviceProcAddr(out->device, "vkGetDisplayPlaneCapabilities2KHR");
#endif
#ifdef VK_KHR_get_memory_requirements2
    out->vkGetImageMemoryRequirements2KHR = (PFN_vkGetImageMemoryRequirements2KHR)out->vkGetDeviceProcAddr(out->device, "vkGetImageMemoryRequirements2KHR");
    out->vkGetBufferMemoryRequirements2KHR = (PFN_vkGetBufferMemoryRequirements2KHR)out->vkGetDeviceProcAddr(out->device, "vkGetBufferMemoryRequirements2KHR");
    out->vkGetImageSparseMemoryRequirements2KHR = (PFN_vkGetImageSparseMemoryRequirements2KHR)out->vkGetDeviceProcAddr(out->device, "vkGetImageSparseMemoryRequirements2KHR");
#endif
#ifdef VK_KHR_sampler_ycbcr_conversion
    out->vkCreateSamplerYcbcrConversionKHR = (PFN_vkCreateSamplerYcbcrConversionKHR)out->vkGetDeviceProcAddr(out->device, "vkCreateSamplerYcbcrConversionKHR");
    out->vkDestroySamplerYcbcrConversionKHR = (PFN_vkDestroySamplerYcbcrConversionKHR)out->vkGetDeviceProcAddr(out->device, "vkDestroySamplerYcbcrConversionKHR");
#endif
#ifdef VK_KHR_bind_memory2
    out->vkBindBufferMemory2KHR = (PFN_vkBindBufferMemory2KHR)out->vkGetDeviceProcAddr(out->device, "vkBindBufferMemory2KHR");
    out->vkBindImageMemory2KHR = (PFN_vkBindImageMemory2KHR)out->vkGetDeviceProcAddr(out->device, "vkBindImageMemory2KHR");
#endif
#ifdef VK_KHR_maintenance3
    out->vkGetDescriptorSetLayoutSupportKHR = (PFN_vkGetDescriptorSetLayoutSupportKHR)out->vkGetDeviceProcAddr(out->device, "vkGetDescriptorSetLayoutSupportKHR");
#endif
#ifdef VK_KHR_draw_indirect_count
    out->vkCmdDrawIndirectCountKHR = (PFN_vkCmdDrawIndirectCountKHR)out->vkGetDeviceProcAddr(out->device, "vkCmdDrawIndirectCountKHR");
    out->vkCmdDrawIndexedIndirectCountKHR = (PFN_vkCmdDrawIndexedIndirectCountKHR)out->vkGetDeviceProcAddr(out->device, "vkCmdDrawIndexedIndirectCountKHR");
#endif
#ifdef VK_EXT_debug_marker
    out->vkDebugMarkerSetObjectTagEXT = (PFN_vkDebugMarkerSetObjectTagEXT)out->vkGetDeviceProcAddr(out->device, "vkDebugMarkerSetObjectTagEXT");
    out->vkDebugMarkerSetObjectNameEXT = (PFN_vkDebugMarkerSetObjectNameEXT)out->vkGetDeviceProcAddr(out->device, "vkDebugMarkerSetObjectNameEXT");
    out->vkCmdDebugMarkerBeginEXT = (PFN_vkCmdDebugMarkerBeginEXT)out->vkGetDeviceProcAddr(out->device, "vkCmdDebugMarkerBeginEXT");
    out->vkCmdDebugMarkerEndEXT = (PFN_vkCmdDebugMarkerEndEXT)out->vkGetDeviceProcAddr(out->device, "vkCmdDebugMarkerEndEXT");
    out->vkCmdDebugMarkerInsertEXT = (PFN_vkCmdDebugMarkerInsertEXT)out->vkGetDeviceProcAddr(out->device, "vkCmdDebugMarkerInsertEXT");
#endif
#ifdef VK_AMD_draw_indirect_count
    out->vkCmdDrawIndirectCountAMD = (PFN_vkCmdDrawIndirectCountAMD)out->vkGetDeviceProcAddr(out->device, "vkCmdDrawIndirectCountAMD");
    out->vkCmdDrawIndexedIndirectCountAMD = (PFN_vkCmdDrawIndexedIndirectCountAMD)out->vkGetDeviceProcAddr(out->device, "vkCmdDrawIndexedIndirectCountAMD");
#endif
#ifdef VK_AMD_shader_info
    out->vkGetShaderInfoAMD = (PFN_vkGetShaderInfoAMD)out->vkGetDeviceProcAddr(out->device, "vkGetShaderInfoAMD");
#endif
#ifdef VK_NV_external_memory_capabilities
    out->vkGetPhysicalDeviceExternalImageFormatPropertiesNV = (PFN_vkGetPhysicalDeviceExternalImageFormatPropertiesNV)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceExternalImageFormatPropertiesNV");
#endif
#ifdef VK_NV_external_memory_win32
    out->vkGetMemoryWin32HandleNV = (PFN_vkGetMemoryWin32HandleNV)out->vkGetDeviceProcAddr(out->device, "vkGetMemoryWin32HandleNV");
#endif
#ifdef VK_EXT_conditional_rendering
    out->vkCmdBeginConditionalRenderingEXT = (PFN_vkCmdBeginConditionalRenderingEXT)out->vkGetDeviceProcAddr(out->device, "vkCmdBeginConditionalRenderingEXT");
    out->vkCmdEndConditionalRenderingEXT = (PFN_vkCmdEndConditionalRenderingEXT)out->vkGetDeviceProcAddr(out->device, "vkCmdEndConditionalRenderingEXT");
#endif
#ifdef VK_NVX_device_generated_commands
    out->vkCmdProcessCommandsNVX = (PFN_vkCmdProcessCommandsNVX)out->vkGetDeviceProcAddr(out->device, "vkCmdProcessCommandsNVX");
    out->vkCmdReserveSpaceForCommandsNVX = (PFN_vkCmdReserveSpaceForCommandsNVX)out->vkGetDeviceProcAddr(out->device, "vkCmdReserveSpaceForCommandsNVX");
    out->vkCreateIndirectCommandsLayoutNVX = (PFN_vkCreateIndirectCommandsLayoutNVX)out->vkGetDeviceProcAddr(out->device, "vkCreateIndirectCommandsLayoutNVX");
    out->vkDestroyIndirectCommandsLayoutNVX = (PFN_vkDestroyIndirectCommandsLayoutNVX)out->vkGetDeviceProcAddr(out->device, "vkDestroyIndirectCommandsLayoutNVX");
    out->vkCreateObjectTableNVX = (PFN_vkCreateObjectTableNVX)out->vkGetDeviceProcAddr(out->device, "vkCreateObjectTableNVX");
    out->vkDestroyObjectTableNVX = (PFN_vkDestroyObjectTableNVX)out->vkGetDeviceProcAddr(out->device, "vkDestroyObjectTableNVX");
    out->vkRegisterObjectsNVX = (PFN_vkRegisterObjectsNVX)out->vkGetDeviceProcAddr(out->device, "vkRegisterObjectsNVX");
    out->vkUnregisterObjectsNVX = (PFN_vkUnregisterObjectsNVX)out->vkGetDeviceProcAddr(out->device, "vkUnregisterObjectsNVX");
    out->vkGetPhysicalDeviceGeneratedCommandsPropertiesNVX = (PFN_vkGetPhysicalDeviceGeneratedCommandsPropertiesNVX)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceGeneratedCommandsPropertiesNVX");
#endif
#ifdef VK_NV_clip_space_w_scaling
    out->vkCmdSetViewportWScalingNV = (PFN_vkCmdSetViewportWScalingNV)out->vkGetDeviceProcAddr(out->device, "vkCmdSetViewportWScalingNV");
#endif
#ifdef VK_EXT_direct_mode_display
    out->vkReleaseDisplayEXT = (PFN_vkReleaseDisplayEXT)out->vkGetDeviceProcAddr(out->device, "vkReleaseDisplayEXT");
#endif
#ifdef VK_EXT_acquire_xlib_display
    out->vkAcquireXlibDisplayEXT = (PFN_vkAcquireXlibDisplayEXT)out->vkGetDeviceProcAddr(out->device, "vkAcquireXlibDisplayEXT");
    out->vkGetRandROutputDisplayEXT = (PFN_vkGetRandROutputDisplayEXT)out->vkGetDeviceProcAddr(out->device, "vkGetRandROutputDisplayEXT");
#endif
#ifdef VK_EXT_display_surface_counter
    out->vkGetPhysicalDeviceSurfaceCapabilities2EXT = (PFN_vkGetPhysicalDeviceSurfaceCapabilities2EXT)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceSurfaceCapabilities2EXT");
#endif
#ifdef VK_EXT_display_control
    out->vkDisplayPowerControlEXT = (PFN_vkDisplayPowerControlEXT)out->vkGetDeviceProcAddr(out->device, "vkDisplayPowerControlEXT");
    out->vkRegisterDeviceEventEXT = (PFN_vkRegisterDeviceEventEXT)out->vkGetDeviceProcAddr(out->device, "vkRegisterDeviceEventEXT");
    out->vkRegisterDisplayEventEXT = (PFN_vkRegisterDisplayEventEXT)out->vkGetDeviceProcAddr(out->device, "vkRegisterDisplayEventEXT");
    out->vkGetSwapchainCounterEXT = (PFN_vkGetSwapchainCounterEXT)out->vkGetDeviceProcAddr(out->device, "vkGetSwapchainCounterEXT");
#endif
#ifdef VK_GOOGLE_display_timing
    out->vkGetRefreshCycleDurationGOOGLE = (PFN_vkGetRefreshCycleDurationGOOGLE)out->vkGetDeviceProcAddr(out->device, "vkGetRefreshCycleDurationGOOGLE");
    out->vkGetPastPresentationTimingGOOGLE = (PFN_vkGetPastPresentationTimingGOOGLE)out->vkGetDeviceProcAddr(out->device, "vkGetPastPresentationTimingGOOGLE");
#endif
#ifdef VK_EXT_discard_rectangles
    out->vkCmdSetDiscardRectangleEXT = (PFN_vkCmdSetDiscardRectangleEXT)out->vkGetDeviceProcAddr(out->device, "vkCmdSetDiscardRectangleEXT");
#endif
#ifdef VK_EXT_hdr_metadata
    out->vkSetHdrMetadataEXT = (PFN_vkSetHdrMetadataEXT)out->vkGetDeviceProcAddr(out->device, "vkSetHdrMetadataEXT");
#endif
#ifdef VK_EXT_debug_utils
    out->vkSetDebugUtilsObjectNameEXT = (PFN_vkSetDebugUtilsObjectNameEXT)out->vkGetDeviceProcAddr(out->device, "vkSetDebugUtilsObjectNameEXT");
    out->vkSetDebugUtilsObjectTagEXT = (PFN_vkSetDebugUtilsObjectTagEXT)out->vkGetDeviceProcAddr(out->device, "vkSetDebugUtilsObjectTagEXT");
    out->vkQueueBeginDebugUtilsLabelEXT = (PFN_vkQueueBeginDebugUtilsLabelEXT)out->vkGetDeviceProcAddr(out->device, "vkQueueBeginDebugUtilsLabelEXT");
    out->vkQueueEndDebugUtilsLabelEXT = (PFN_vkQueueEndDebugUtilsLabelEXT)out->vkGetDeviceProcAddr(out->device, "vkQueueEndDebugUtilsLabelEXT");
    out->vkQueueInsertDebugUtilsLabelEXT = (PFN_vkQueueInsertDebugUtilsLabelEXT)out->vkGetDeviceProcAddr(out->device, "vkQueueInsertDebugUtilsLabelEXT");
    out->vkCmdBeginDebugUtilsLabelEXT = (PFN_vkCmdBeginDebugUtilsLabelEXT)out->vkGetDeviceProcAddr(out->device, "vkCmdBeginDebugUtilsLabelEXT");
    out->vkCmdEndDebugUtilsLabelEXT = (PFN_vkCmdEndDebugUtilsLabelEXT)out->vkGetDeviceProcAddr(out->device, "vkCmdEndDebugUtilsLabelEXT");
    out->vkCmdInsertDebugUtilsLabelEXT = (PFN_vkCmdInsertDebugUtilsLabelEXT)out->vkGetDeviceProcAddr(out->device, "vkCmdInsertDebugUtilsLabelEXT");
#endif
#ifdef VK_ANDROID_external_memory_android_hardware_buffer
    out->vkGetAndroidHardwareBufferPropertiesANDROID = (PFN_vkGetAndroidHardwareBufferPropertiesANDROID)out->vkGetDeviceProcAddr(out->device, "vkGetAndroidHardwareBufferPropertiesANDROID");
    out->vkGetMemoryAndroidHardwareBufferANDROID = (PFN_vkGetMemoryAndroidHardwareBufferANDROID)out->vkGetDeviceProcAddr(out->device, "vkGetMemoryAndroidHardwareBufferANDROID");
#endif
#ifdef VK_EXT_sample_locations
    out->vkCmdSetSampleLocationsEXT = (PFN_vkCmdSetSampleLocationsEXT)out->vkGetDeviceProcAddr(out->device, "vkCmdSetSampleLocationsEXT");
    out->vkGetPhysicalDeviceMultisamplePropertiesEXT = (PFN_vkGetPhysicalDeviceMultisamplePropertiesEXT)out->vkGetDeviceProcAddr(out->device, "vkGetPhysicalDeviceMultisamplePropertiesEXT");
#endif
#ifdef VK_EXT_validation_cache
    out->vkCreateValidationCacheEXT = (PFN_vkCreateValidationCacheEXT)out->vkGetDeviceProcAddr(out->device, "vkCreateValidationCacheEXT");
    out->vkDestroyValidationCacheEXT = (PFN_vkDestroyValidationCacheEXT)out->vkGetDeviceProcAddr(out->device, "vkDestroyValidationCacheEXT");
    out->vkMergeValidationCachesEXT = (PFN_vkMergeValidationCachesEXT)out->vkGetDeviceProcAddr(out->device, "vkMergeValidationCachesEXT");
    out->vkGetValidationCacheDataEXT = (PFN_vkGetValidationCacheDataEXT)out->vkGetDeviceProcAddr(out->device, "vkGetValidationCacheDataEXT");
#endif
#ifdef VK_EXT_external_memory_host
    out->vkGetMemoryHostPointerPropertiesEXT = (PFN_vkGetMemoryHostPointerPropertiesEXT)out->vkGetDeviceProcAddr(out->device, "vkGetMemoryHostPointerPropertiesEXT");
#endif
#ifdef VK_AMD_buffer_marker
    out->vkCmdWriteBufferMarkerAMD = (PFN_vkCmdWriteBufferMarkerAMD)out->vkGetDeviceProcAddr(out->device, "vkCmdWriteBufferMarkerAMD");
#endif
#ifdef VK_NV_device_diagnostic_checkpoints
    out->vkCmdSetCheckpointNV = (PFN_vkCmdSetCheckpointNV)out->vkGetDeviceProcAddr(out->device, "vkCmdSetCheckpointNV");
    out->vkGetQueueCheckpointDataNV = (PFN_vkGetQueueCheckpointDataNV)out->vkGetDeviceProcAddr(out->device, "vkGetQueueCheckpointDataNV");
#endif
}

} // namespace goldfish_vk
