#!/bin/sh

. $(dirname "$0")/utils/common.shi

shell_import utils/option_parser.shi
shell_import utils/temp_dir.shi

PROGRAM_DESCRIPTION=\
"This script is used to download .deb packages from Ubuntu servers and unpack
them to create a valid 'sysroot' directory to be used for generating GCC based
toolchains.

A custom sysroot ensures that the binaries generated by said toolchain can
run on older Linux distributions, instead of the the build machine's one.

For example, this is typically used to download an Ubuntu 12.04 sysroot when
building on an Ubuntu 14.04 installation.
"

PROGRAM_PARAMETERS="<destination-path>"

UBUNTU_ARCHS="i386 amd64"
option_register_var "--ubuntu-archs=<list>" UBUNTU_ARCHS \
    "Specify alternative CPU architectures"

UBUNTU_RELEASE=precise
option_register_var "--ubuntu-release=<name>" UBUNTU_RELEASE \
    "Specify alternative Ubuntu release name"

UBUNTU_MIRROR=http://mirrors.us.kernel.org
option_register_var "--ubuntu-mirror=<url>" UBUNTU_MIRROR \
    "Specify alternative Ubuntu mirror"

BUILD_DIR=
option_register_var "--build-dir=<path>" BUILD_DIR \
    "Specify non-temporary download and build directory"

option_parse "$@"

if [ "$PARAMETER_COUNT" != "1" ]; then
    panic "This script takes a single parameter. See --help."
fi

DST_SYSROOT=$PARAMETER_1
log "Installation path: $DST_SYSROOT"

if [ -z "$BUILD_DIR" ]; then
    var_create_temp_dir WORK_DIR "build-ubuntu-sysroot"
else
    WORK_DIR=$BUILD_DIR
fi
log "Build directory: $WORK_DIR"

mkdir -p "$WORK_DIR" || panic "Could not create work directory: $WORK_DIR"

# The list of packages we need to download from the Ubuntu servers and
# extract into the original sysroot
#
# Call add_ubuntu_package <package-name> to add a package to the list,
# which will be processed later.
#
UBUNTU_PACKAGES=

add_ubuntu_package () {
    UBUNTU_PACKAGES="$UBUNTU_PACKAGES $@"
}

# The package files containing kernel headers for Hardy and the C
# library headers and binaries
add_ubuntu_package \
    linux-libc-dev \
    libc6 \
    libc6-dev \
    libcap2 \
    libcap-dev \
    libattr1 \
    libattr1-dev \
    libacl1 \
    libacl1-dev \

# The X11 headers and binaries (for the emulator)
add_ubuntu_package \
    libx11-6 \
    libx11-dev \
    libxau6 \
    libxcb1-dev \
    libxdmcp6 \
    libxext-dev \
    libxfixes-dev \
    libxi-dev \
    x11proto-core-dev \
    x11proto-fixes-dev \
    x11proto-xext-dev \
    x11proto-input-dev \
    x11proto-kb-dev

# The OpenGL-related headers and libraries (for GLES emulation)
add_ubuntu_package \
    mesa-common-dev \
    libgl1-mesa-dev \
    libgl1-mesa-glx \
    libxxf86vm1 \
    libxext6 \
    libxdamage1 \
    libxfixes3 \
    libdrm2

# Audio libraries (required by the emulator)
add_ubuntu_package \
    libasound2 \
    libasound2-dev \
    libesd0-dev \
    libaudiofile-dev \
    libpulse0 \
    libpulse-dev

# ZLib and others.
add_ubuntu_package \
    zlib1g \
    zlib1g-dev \
    libncurses5 \
    libncurses5-dev

# Location where we download packages from the Ubuntu servers
DOWNLOAD_DIR=$WORK_DIR/download
mkdir -p "$DOWNLOAD_DIR" || panic "Could not create dir: $DOWNLOAD_DIR"

# A file that will contain details about all the sources used to generate
# the final toolchain. This includes SHA-1 hasehs for downloaded Ubuntu
# packages.
SOURCES_LIST=$WORK_DIR/SOURCES

# Location of original sysroot. This is where we're going to extract all
# binary Ubuntu packages.
ORG_SYSROOT_DIR=$WORK_DIR/sysroot

# Empty the SOURCES file
rm -f "$SOURCES_LIST" && touch "$SOURCES_LIST"

# Sanitize a path list, we want to remove empty sub-dirs and
# leading/trailing columns.
sanitize_path_list ()
{
  local RESULT
  RESULT=$(printf "%s\n" "$*" | tr ':' '\n' | awk '$1 != "" && $1 != "." { print $0; }' | tr '\n' ':')
  printf "%s" ${RESULT%:}
}

PATH=$(sanitize_path_list $PATH)
LD_LIBRARY_PATH=$(sanitize_path_list $LD_LIBRARY_PATH)

# Remove trailing slash from input
# $1: input text
# Out: input text wihtout any trailing slashes (e.g. 'foo/bar//' -> 'foo/bar')
no_trailing_slash () {
    echo ${1##/}
}

# Load the Ubuntu packages file. This is a long text file that will list
# each package for a given release.
#
# $1: Ubuntu mirror base URL (e.g. http://mirrors.us.kernel.org/)
# $2: Release name
# $3: Download directory.
#
get_ubuntu_packages_list () {
    local DOWNLOAD_DIR=$3
    local RELEASE=$2
    local BASE="$(no_trailing_slash $1)"
    local SRCFILE DSTFILE
    for UA in $UBUNTU_ARCHS; do
        SRCFILE=$BASE/ubuntu/dists/$RELEASE/main/binary-$UA/Packages.bz2
        DSTFILE=$DOWNLOAD_DIR/Packages-$UA.bz2
        log "Trying to load $SRCFILE"
        download_file "$SRCFILE" "$DSTFILE" ||
                panic "Could not download $SRCFILE"
        (cd $DOWNLOAD_DIR && bunzip2 -cf Packages-$UA.bz2 > Packages-$UA) ||
                panic "Could not uncompress $DSTFILE to Packages-$UA"
    done

    # Write a small awk script used to extract filenames for a given package
    cat > $DOWNLOAD_DIR/extract-filename.awk <<EOF
BEGIN {
    # escape special characters in package name
    gsub("\\\\.","\\\\.",PKG)
    gsub("\\\\+","\\\\+",PKG)
    FILE = ""
    PACKAGE = ""
}

\$1 == "Package:" {
    if (\$2 == PKG) {
        PACKAGE = \$2
    } else {
        PACKAGE = ""
    }
}

\$1 == "Filename:" && PACKAGE == PKG {
    FILE = \$2
}

END {
    print FILE
}
EOF
}

# Convert an unversioned package name into a .deb package URL
#
# $1: Package name without version information (e.g. libc6-dev)
# $2: Ubuntu mirror base URL
# $3: Ubuntu arch ("i386" or "amd64")
# $4: Download directory.
# Out: full package path.
get_ubuntu_package_deb_url () {
    # The following is an awk command to parse the Packages file and extract
    # the filename of a given package.
    local BASE="$(no_trailing_slash \"$1\")"
    local FILE=$(awk -f "$4/extract-filename.awk" -v PKG=$1 $4/Packages-$3)
    if [ -z "$FILE" ]; then
        log "Could not find filename for package $1"
        exit 1
    fi
    echo "$2/ubuntu/$FILE"
}

download_packages () {
    local PACKAGE PKGURL

    rm -f $DOWNLOAD_DIR/SOURCES && touch $DOWNLOAD_DIR/SOURCES
    for PACKAGE in $UBUNTU_PACKAGES; do
        echo "Downloading $PACKAGE"
            for UA in $UBUNTU_ARCHS; do
            PKGURL=$(get_ubuntu_package_deb_url $PACKAGE $UBUNTU_MIRROR $UA $DOWNLOAD_DIR)
            echo "URL: $PKGURL"
            download_file_to $PKGURL $DOWNLOAD_DIR ||
                    panic "Could not download $PKGURL"
        done
    done
    sha1sum $DOWNLOAD_DIR/*.deb | while read LINE; do
        PACKAGE=$(basename $(echo $LINE | awk '{ print $2;}'))
        SHA1=$(echo $LINE | awk '{ print $1; }')
        printf "%-64s %s\n" $PACKAGE $SHA1 >> $DOWNLOAD_DIR/SOURCES
    done
}

build_sysroot () {
    local PACKAGE PKGURL SRC_PKG UA
    mkdir -p $SRC_PKG $ORG_SYSROOT_DIR
    for PACKAGE in $UBUNTU_PACKAGES; do
        for UA in $UBUNTU_ARCHS; do
            PKGURL=$(get_ubuntu_package_deb_url $PACKAGE $UBUNTU_MIRROR $UA $DOWNLOAD_DIR)
            SRC_PKG=$DOWNLOAD_DIR/$(basename $PKGURL)
            echo "Extracting $SRC_PKG"
            dpkg -x $SRC_PKG $ORG_SYSROOT_DIR/$UA
        done
    done
}

# Now, we need to patch libc.so which is actually a linker script
# referencing /lib and /usr/lib. Do the same for libpthread.so
# $1: library (really linker script) path.
patch_library () {
    echo "Patching $1"
    sed -i -e "s! /lib/! !g" -e "s! /usr/lib/! !g" $1
}

# Return the list of all symbolic links in a given directory, excluding
# any links in its sub-directories.
# $1: Sub-directory path.
find_symlinks_in () {
    (cd $1 && find . -maxdepth 1 -type l) | sed -e 's|^\./||g'
}

# $1: Target sysroot directory.
copy_sysroot () {
    local SL DST_SYSROOT
    DST_SYSROOT=$1

    # Copy the content of $BUILD_DIR/lib to $(sysroot_dir)/usr/lib
    copy_directory $ORG_SYSROOT_DIR/i386/lib $DST_SYSROOT/usr/lib32
    copy_directory $ORG_SYSROOT_DIR/i386/usr/lib $DST_SYSROOT/usr/lib32
    copy_directory $ORG_SYSROOT_DIR/i386/usr/include $DST_SYSROOT/usr/include

    copy_directory $ORG_SYSROOT_DIR/amd64/lib $DST_SYSROOT/usr/lib
    copy_directory $ORG_SYSROOT_DIR/amd64/usr/lib $DST_SYSROOT/usr/lib
    copy_directory $ORG_SYSROOT_DIR/amd64/usr/include $DST_SYSROOT/usr/include

    for LIB in lib lib32; do
        # We need to fix the symlink like librt.so -> /lib/librt.so.1
        # in $DST_SYSROOT/usr/$LIB, they should point to librt.so.1 instead now.
        SYMLINKS=$(find_symlinks_in $DST_SYSROOT/usr/$LIB)
        cd $DST_SYSROOT/usr/$LIB
        for SL in $SYMLINKS; do
            # convert /lib/libfoo.so.<n> into 'libfoo.so.<n>' for the target
            local DST=$(readlink $SL 2>/dev/null)
            local DST2=${DST##/lib/}
            if [ "$DST2" != "$DST" ]; then
                echo "Fixing symlink $SL --> $DST"
                rm $SL && ln -s $DST2 $SL
            fi
        done
        # NOTE: Use 'find' to get the path of the patched libraries. On some
        # distros, they will be under /usr/$LIB, on other in /usr/$ARCH/$LIB
        PATCHED_LIBS=
        var_append PATCHED_LIBS $(find $DST_SYSROOT -name "libc.so")
        var_append PATCHED_LIBS $(find $DST_SYSROOT -name "libpthread.so")
        for PATCHED_LIB in $PATCHES_LIBS; do
            patch_library $PATCH_LIB
        done
    done
}

get_ubuntu_packages_list $UBUNTU_MIRROR "$UBUNTU_RELEASE" "$DOWNLOAD_DIR"
download_packages
build_sysroot
copy_sysroot $DST_SYSROOT
