/*
 * Copyright (C) 2011 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

 
#ifndef _ES1XCONTEXT_H
#define _ES1XCONTEXT_H

#ifndef _ES1XMATRIXSTACK_H
#       include "es1xMatrixStack.h"
#endif

#ifndef _ES1XERROR_H
#       include "es1xError.h"
#endif

#ifndef _ES1XCOLOR_H
#       include "es1xColor.h"
#endif

#ifndef _ES1XVECTOR_H
#       include "es1xVector.h"
#endif

#ifndef _ES1XLIGHT_H
#       include "es1xLight.h"
#endif

#ifndef _ES1XRECT_H
#       include "es1xRect.h"
#endif

#ifndef _ES1XSHADERCACHE_H
#       include "es1xShaderCache.h"
#endif

#ifndef _ES1XSHADERPROGRAMS_H
#       include "es1xShaderPrograms.h"
#endif

#ifndef _ES1XUNIFORMVERSIONS_H
#       include "es1xUniformVersions.h"
#endif

#ifndef _ES1XTEXENV_H
#       include "es1xTexEnv.h"
#endif

#ifndef _ES1XTEXTURE_H
#       include "es1xTexture.h"
#endif

#ifndef _ES1XTEXTUREALLOCATOR_H
#       include "es1xTextureAllocator.h"
#endif

#ifndef _ES1XTEXTUREHASHTABLE_H
#       include "es1xTextureHashTable.h"
#endif

#ifndef _ES1XSTATISTICS_H
#       include "es1xStatistics.h"
#endif

#ifndef _ES1XENUMERATIONS_H
#       include "es1xEnumerations.h"
#endif

typedef struct _es1xContext_
{
  /* Matrix stacks */
  es1xMatrixStack*              projectionMatrixStack;
  es1xMatrixStack*              modelViewMatrixStack;
  es1xMatrixStack*              currentMatrixStack;
  es1xMatrixStack*              textureMatrixStack[ES1X_NUM_SUPPORTED_TEXTURE_UNITS];

  /* Clip planes */
  GLboolean                     clipPlaneEnabled[ES1X_NUM_SUPPORTED_CLIP_PLANES];

  /* Texturing */
  es1xTextureAllocator* textureAllocator;
  es1xTextureHashTable* textureHashTable;

  /* Error handling */
  GLenum                        lastError;

  /* Dirty flags */
  GLuint                        dirty;
  es1xShaderProgramInfo*        lastUsedShaderProgramInfo;

  /* Shader caching */
  es1xShaderCache*              shaderCache;
  es1xUniformVersions           uniformVersions;
  es1xIndexMapTable             currentMapTable;

  /* Unsorted */
  GLuint                        activeBufferBinding;

  /* Autogenerated fields */
#include "es1xContextFields.inl"

  /* Statistics */
  es1xStatistics                statistics;

} es1xContext;



#ifdef __cplusplus
extern "C"
{
#endif

void*    es1xContext_create(void);
void     es1xContext_destroy(void *_context_);

es1xTexture2D*  es1xContext_allocateTexture(es1xContext* context, GLuint texture);
es1xTexture2D*  es1xContext_getTexture(es1xContext* context, GLuint texture);
void            es1xContext_releaseTexture(es1xContext* context, es1xTexture2D* texture);

#define ES1X_UPDATE_CONTEXT_STATE(STATEMENT)    \
  {                                             \
    STATEMENT;                                  \
    context->dirty = GL_TRUE;                   \
  }

#define ES1X_UPDATE_CONTEXT_GENERIC_PARAMETER(STATEMENT, GROUPTYPE)     \
  {                                                                     \
    STATEMENT;                                                          \
    es1xUniformVersions_increment(&context->uniformVersions, GROUPTYPE); \
  }

#define ES1X_UPDATE_CONTEXT_GENERIC_ARRAY_PARAMETER(STATEMENT, ARRAYINDEX, MININDEX, MAXINDEXPLUSONE, GROUPTYPE) \
  {                                                                     \
    STATEMENT;                                                          \
    ES1X_ASSERT(ARRAYINDEX >= MININDEX && ARRAYINDEX < MAXINDEXPLUSONE); \
    es1xUniformVersions_increment(&context->uniformVersions, GROUPTYPE + ARRAYINDEX); \
  }

#define ES1X_UPDATE_CONTEXT_VERTEX_PARAMETER(STATEMENT) ES1X_UPDATE_CONTEXT_GENERIC_PARAMETER(STATEMENT, UNIFORM_GROUP_VERTEX_PARAMETER)
#define ES1X_UPDATE_CONTEXT_POINT_SIZE_PARAMETER(STATEMENT) ES1X_UPDATE_CONTEXT_GENERIC_PARAMETER(STATEMENT, UNIFORM_GROUP_POINT_SIZE)
#define ES1X_UPDATE_CONTEXT_ALPHA_TEST_PARAMETER(STATEMENT) ES1X_UPDATE_CONTEXT_GENERIC_PARAMETER(STATEMENT, UNIFORM_GROUP_ALPHA_TEST)
#define ES1X_UPDATE_CONTEXT_MODELVIEW_MATRIX(STATEMENT) ES1X_UPDATE_CONTEXT_GENERIC_PARAMETER(STATEMENT, UNIFORM_GROUP_MODELVIEW_MATRIX)
#define ES1X_UPDATE_CONTEXT_INVERSION_MODELVIEW_MATRIX(STATEMENT) ES1X_UPDATE_CONTEXT_GENERIC_PARAMETER(STATEMENT, UNIFORM_GROUP_INVERSION_MODELVIEW_MATRIX)
#define ES1X_UPDATE_CONTEXT_PROJECTION_MODELVIEW_MATRIX(STATEMENT) ES1X_UPDATE_CONTEXT_GENERIC_PARAMETER(STATEMENT, UNIFORM_GROUP_PMV_MATRIX)
#define ES1X_UPDATE_CONTEXT_FOG_PARAMETER(STATEMENT) ES1X_UPDATE_CONTEXT_GENERIC_PARAMETER(STATEMENT, UNIFORM_GROUP_FOG)
#define ES1X_UPDATE_CONTEXT_MATERIAL_PARAMETER(STATEMENT) ES1X_UPDATE_CONTEXT_GENERIC_PARAMETER(STATEMENT, UNIFORM_GROUP_MATERIALS)
#define ES1X_UPDATE_CONTEXT_LIGHT_MODEL_PARAMETER(STATEMENT) ES1X_UPDATE_CONTEXT_GENERIC_PARAMETER(STATEMENT, UNIFORM_GROUP_LIGHT_MODEL)
#define ES1X_UPDATE_CONTEXT_UNSORTED_PARAMETER(STATEMENT) ES1X_UPDATE_CONTEXT_GENERIC_PARAMETER(STATEMENT, UNIFORM_GROUP_UNSORTED) ;
#define ES1X_UPDATE_CONTEXT_TEXTURE_MATRIX(TEXTURE, STATEMENT) ES1X_UPDATE_CONTEXT_GENERIC_ARRAY_PARAMETER(STATEMENT, TEXTURE, 0, ES1X_NUM_SUPPORTED_TEXTURE_UNITS, UNIFORM_GROUP_TEXTURE_MATRIX)
#define ES1X_UPDATE_CONTEXT_LIGHT_PARAMETER(LIGHT, STATEMENT) ES1X_UPDATE_CONTEXT_GENERIC_ARRAY_PARAMETER(STATEMENT, LIGHT, 0, ES1X_NUM_SUPPORTED_LIGHTS, UNIFORM_GROUP_LIGHT)
#define ES1X_UDPATE_CONTEXT_CLIP_PLANE_PARAMETER(CLIPPLANE, STATEMENT) ES1X_UPDATE_CONTEXT_GENERIC_ARRAY_PARAMETER(STATEMENT, CLIPPLANE, 0, ES1X_NUM_SUPPORTED_CLIP_PLANES, UNIFORM_GROUP_CLIP_PLANE)
#define ES1X_UPDATE_CONTEXT_TEXTURE_ENV_PARAMETER(TEXTUREUNIT, STATEMENT) ES1X_UPDATE_CONTEXT_GENERIC_ARRAY_PARAMETER(STATEMENT, TEXTUREUNIT, 0, ES1X_NUM_SUPPORTED_TEXTURE_UNITS, UNIFORM_GROUP_TEXTURE_ENV)

#define ES1X_CHECK_CONTEXT(CONTEXT)             \
  if(CONTEXT == 0)                              \
    return;

#define ES1X_CHECK_CONTEXT_RET_FALSE(CONTEXT)   \
  if(CONTEXT == 0)                              \
    return GL_FALSE;

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* _ES1XCONTEXT_H */
