/*
 * Copyright (C) 2011 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

 
/* THIS FILE IS AUTOGENERATED, DO NOT MODIFY */
#ifndef _ES1XENUMERATIONS_H
#	include "es1xEnumerations.h"
#endif 

GLenum mapTextureFormatToGLEnum(deInt32 param)
{
	switch(param)
	{
		case ES1X_TEXTUREFORMAT_ALPHA: return GL_ALPHA;
		case ES1X_TEXTUREFORMAT_LUMINANCE: return GL_LUMINANCE;
		case ES1X_TEXTUREFORMAT_LUMINANCE_ALPHA: return GL_LUMINANCE_ALPHA;
		case ES1X_TEXTUREFORMAT_RGB: return GL_RGB;
		case ES1X_TEXTUREFORMAT_RGBA: return GL_RGBA;
		default:
			ES1X_ASSERT(!"Unhandled case!");
			break;
	}
	return 0;
}

GLenum mapFogModeToGLEnum(deInt32 param)
{
	switch(param)
	{
		case ES1X_FOGMODE_EXP: return GL_EXP;
		case ES1X_FOGMODE_EXP2: return GL_EXP2;
		case ES1X_FOGMODE_LINEAR: return GL_LINEAR;
		default:
			ES1X_ASSERT(!"Unhandled case!");
			break;
	}
	return 0;
}

GLenum mapCompareFuncToGLEnum(deInt32 param)
{
	switch(param)
	{
		case ES1X_COMPAREFUNC_NEVER: return GL_NEVER;
		case ES1X_COMPAREFUNC_LESS: return GL_LESS;
		case ES1X_COMPAREFUNC_LEQUAL: return GL_LEQUAL;
		case ES1X_COMPAREFUNC_EQUAL: return GL_EQUAL;
		case ES1X_COMPAREFUNC_GEQUAL: return GL_GEQUAL;
		case ES1X_COMPAREFUNC_GREATER: return GL_GREATER;
		case ES1X_COMPAREFUNC_ALWAYS: return GL_ALWAYS;
		case ES1X_COMPAREFUNC_NOTEQUAL: return GL_NOTEQUAL;
		default:
			ES1X_ASSERT(!"Unhandled case!");
			break;
	}
	return 0;
}

GLenum mapTexEnvModeToGLEnum(deInt32 param)
{
	switch(param)
	{
		case ES1X_TEXENVMODE_REPLACE: return GL_REPLACE;
		case ES1X_TEXENVMODE_MODULATE: return GL_MODULATE;
		case ES1X_TEXENVMODE_DECAL: return GL_DECAL;
		case ES1X_TEXENVMODE_BLEND: return GL_BLEND;
		case ES1X_TEXENVMODE_ADD: return GL_ADD;
		case ES1X_TEXENVMODE_COMBINE: return GL_COMBINE;
		default:
			ES1X_ASSERT(!"Unhandled case!");
			break;
	}
	return 0;
}

GLenum mapTexEnvCombineRGBToGLEnum(deInt32 param)
{
	switch(param)
	{
		case ES1X_TEXENVCOMBINERGB_REPLACE: return GL_REPLACE;
		case ES1X_TEXENVCOMBINERGB_MODULATE: return GL_MODULATE;
		case ES1X_TEXENVCOMBINERGB_ADD: return GL_ADD;
		case ES1X_TEXENVCOMBINERGB_ADD_SIGNED: return GL_ADD_SIGNED;
		case ES1X_TEXENVCOMBINERGB_INTERPOLATE: return GL_INTERPOLATE;
		case ES1X_TEXENVCOMBINERGB_SUBTRACT: return GL_SUBTRACT;
		case ES1X_TEXENVCOMBINERGB_DOT3_RGB: return GL_DOT3_RGB;
		case ES1X_TEXENVCOMBINERGB_DOT3_RGBA: return GL_DOT3_RGBA;
		default:
			ES1X_ASSERT(!"Unhandled case!");
			break;
	}
	return 0;
}

GLenum mapTexEnvCombineAlphaToGLEnum(deInt32 param)
{
	switch(param)
	{
		case ES1X_TEXENVCOMBINEALPHA_REPLACE: return GL_REPLACE;
		case ES1X_TEXENVCOMBINEALPHA_MODULATE: return GL_MODULATE;
		case ES1X_TEXENVCOMBINEALPHA_ADD: return GL_ADD;
		case ES1X_TEXENVCOMBINEALPHA_ADD_SIGNED: return GL_ADD_SIGNED;
		case ES1X_TEXENVCOMBINEALPHA_INTERPOLATE: return GL_INTERPOLATE;
		case ES1X_TEXENVCOMBINEALPHA_SUBTRACT: return GL_SUBTRACT;
		default:
			ES1X_ASSERT(!"Unhandled case!");
			break;
	}
	return 0;
}

GLenum mapTexEnvSrcToGLEnum(deInt32 param)
{
	switch(param)
	{
		case ES1X_TEXENVSRC_TEXTURE: return GL_TEXTURE;
		case ES1X_TEXENVSRC_CONSTANT: return GL_CONSTANT;
		case ES1X_TEXENVSRC_PRIMARY_COLOR: return GL_PRIMARY_COLOR;
		case ES1X_TEXENVSRC_PREVIOUS: return GL_PREVIOUS;
		default:
			ES1X_ASSERT(!"Unhandled case!");
			break;
	}
	return 0;
}

GLenum mapTexEnvOperandRGBToGLEnum(deInt32 param)
{
	switch(param)
	{
		case ES1X_TEXENVOPERANDRGB_SRC_COLOR: return GL_SRC_COLOR;
		case ES1X_TEXENVOPERANDRGB_ONE_MINUS_SRC_COLOR: return GL_ONE_MINUS_SRC_COLOR;
		case ES1X_TEXENVOPERANDRGB_SRC_ALPHA: return GL_SRC_ALPHA;
		case ES1X_TEXENVOPERANDRGB_ONE_MINUS_SRC_ALPHA: return GL_ONE_MINUS_SRC_ALPHA;
		default:
			ES1X_ASSERT(!"Unhandled case!");
			break;
	}
	return 0;
}

GLenum mapTexEnvOperandAlphaToGLEnum(deInt32 param)
{
	switch(param)
	{
		case ES1X_TEXENVOPERANDALPHA_SRC_ALPHA: return GL_SRC_ALPHA;
		case ES1X_TEXENVOPERANDALPHA_ONE_MINUS_SRC_ALPHA: return GL_ONE_MINUS_SRC_ALPHA;
		default:
			ES1X_ASSERT(!"Unhandled case!");
			break;
	}
	return 0;
}
