# Last use (date)
name        = use.date
type        = integer
default     = 0
abstract    = Timestamp of last emulator use
description = ISO formatted date of last time the emulator was launched

# Emulator version (installed)
name        = version.current
type        = string
default     = unknown
abstract    = Emulator version
description = The version of the Android Emulator

# Emulator version (latest)
name        = version.latest
type        = string
default     = unknown
abstract    = Emulator version
description = The version of the Android Emulator

# Emulator crash reporting opt-in status
name        = optin
type        = boolean
default     = false
abstract    = Crash reports opt-in preferences
description = Whether users have opted in to send crash reports

# Installation ID
name        = uid
type        = string
default     = 00000000-0000-0000-0000-000000000000
abstract    = Emulator installation ID
description = Emulator identifier, usually carried over from latest Android Studio installation

# GPU information
name        = glvendor
type        = string
default     = unknown
abstract    = Information related to the current system graphics stack
description = A succint description of the system OpenGL stack for debugging purposes

# Last telemetry properties file refresh (date)
name        = refresh.date
type        = integer
default     = 0
abstract    = Timestamp of when telemetry properties file was last updated (not considering usedate updates)
description = Date of last time the emulator telemetry properties file was updated in anything but usedate

# Emulator telemetry properties update period (in days)
name        = refresh.period
type        = integer
default     = 1
abstract    = Number of days between checks for emulator telemetry properties file refresh
description = How often (in days) to check for updates and changes to telemetry relevant data

