/* This file is autogenerated by tracetool, do not edit. */

#ifndef TRACE_HW_RDMA_GENERATED_TRACERS_H
#define TRACE_HW_RDMA_GENERATED_TRACERS_H

#include "qemu-common.h"
#include "trace/control.h"

extern TraceEvent _TRACE_CREATE_AH_CACHE_HIT_EVENT;
extern TraceEvent _TRACE_CREATE_AH_CACHE_MISS_EVENT;
extern uint16_t _TRACE_CREATE_AH_CACHE_HIT_DSTATE;
extern uint16_t _TRACE_CREATE_AH_CACHE_MISS_DSTATE;
#define TRACE_CREATE_AH_CACHE_HIT_ENABLED 1
#define TRACE_CREATE_AH_CACHE_MISS_ENABLED 1

#define TRACE_CREATE_AH_CACHE_HIT_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_create_ah_cache_hit(uint64_t subnet, uint64_t net_id)
{
}

static inline void trace_create_ah_cache_hit(uint64_t subnet, uint64_t net_id)
{
    if (true) {
        _nocheck__trace_create_ah_cache_hit(subnet, net_id);
    }
}

#define TRACE_CREATE_AH_CACHE_MISS_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_create_ah_cache_miss(uint64_t subnet, uint64_t net_id)
{
}

static inline void trace_create_ah_cache_miss(uint64_t subnet, uint64_t net_id)
{
    if (true) {
        _nocheck__trace_create_ah_cache_miss(subnet, net_id);
    }
}
#endif /* TRACE_HW_RDMA_GENERATED_TRACERS_H */
