// Copyright (C) 2023 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
#include <algorithm>
#include <condition_variable>
#include <fstream>
#include <future>
#include <mutex>
#include <cstring>
#include "aemu/base/Uuid.h"
#include "aemu/base/files/PathUtils.h"
#include "android/avd/avd-info.h"
#include "android/avd/info-grpc.h"
#include "android/avd/info.h"
#include "android/base/system/System.h"
#include "android/emulation/control/utils/AvdClient.h"
#include "android/utils/system.h"

using android::base::PathUtils;
using android::base::System;
using android::base::Uuid;

#if DEBUG >= 1
#define DD(fmt, ...) \
    dinfo("AvdClient: %s:%d| " fmt "\n", __func__, __LINE__, ##__VA_ARGS__)
#else
#define DD(...) (void)0
#endif

extern "C" int _avdInfo_getConfigIni(AvdInfo* i);
extern "C" int _avdInfo_getBuildSkinHardwareIni(AvdInfo* i);

static std::string generate_tmp_cfg(
        std::unordered_map<std::string, std::string> cfg) {
    auto configFile = PathUtils::join(System::get()->getTempDir(),
                                      Uuid::generate().toString());
    std::fstream output(PathUtils::asUnicodePath(configFile.c_str()).c_str(),
                        std::ios::out | std::ios::binary);

    output << "## Autogenerated avd cfg file." << std::endl;
    for (const auto [key, val] : cfg) {
        output << key << " = " << val << std::endl;
    }
    output.flush();
    output.close();

    return configFile;
}

static char* stringCopy(std::string str) {
  // Create a new character array to store the copied string.
  char* newString = (char*) malloc(str.size() + 1);
  memcpy(newString, str.c_str(), str.size());
  newString[str.size()] = '\0';
  return newString;
}

AvdInfo* avdInfo_from_grpc(AvdClient* client) {
    AvdInfo* avd;
    auto info = client->getAvdInfo();
    if (!info.ok()) {
        derror("Unable to obtain avd info: %s", info.status().message().data());
        return nullptr;
    }
    DD("Received: %s", info->ShortDebugString().c_str());

    ANEW0(avd);

    avd->androidOut = stringCopy(info->android_out());
    avd->androidBuildRoot = stringCopy(info->android_build_root());
    avd->targetArch = stringCopy(info->target_arch());
    avd->targetAbi = stringCopy(info->target_abi());
    avd->acpiIniPath = stringCopy(info->acpi_ini_path());
    avd->target = stringCopy(info->target());

    avd->deviceName = stringCopy(info->device_name());
    avd->deviceId = stringCopy(info->device_id());
    avd->sdkRootPath = stringCopy(info->sdk_root_path());

    int i = 0;
    for (const auto& searchPath : info->search_paths()) {
        // Do something with the search path.
        avd->searchPaths[i] = stringCopy(searchPath);
    }
    avd->numSearchPaths = i;

    avd->contentPath = stringCopy(info->content_path());
    avd->rootIniPath = stringCopy(info->root_ini_path());

    // Setup the CINI files.
    // Could also use generate_tmp_cfg(avd->root_ini());
    avd->rootIni = iniFile_newFromFile(avd->rootIniPath);
    _avdInfo_getConfigIni(avd);
    _avdInfo_getBuildSkinHardwareIni(avd);

    avd->apiLevel = info->api_level();
    avd->incrementalVersion = info->incremental_version();
    avd->isGoogleApis = info->is_google_apis();
    avd->isUserBuild = info->is_user_build();
    avd->isAtd = info->is_atd();
    avd->flavor = static_cast<AvdFlavor>((int)info->flavor() - 1);

    avd->skinName = stringCopy(info->skin_name());
    avd->skinDirPath = stringCopy(info->skin_dir_path());
    avd->coreHardwareIniPath = stringCopy(info->core_hardware_ini_path());
    avd->snapshotLockPath = stringCopy(info->snapshot_lock_path());
    avd->multiInstanceLockPath =
            stringCopy(info->multi_instance_lock_path());

    // ownership will transfer
    auto len = info->build_properties().size();
    auto copy = malloc(len);
    memcpy(copy, info->build_properties().c_str(), len);
    fileData_initFromMemory(avd->buildProperties, copy, len);

    len = info->boot_properties().size();
    copy = malloc(len);
    memcpy(copy, info->boot_properties().c_str(), len);
    fileData_initFromMemory(avd->bootProperties, copy, len);

    i = 0;
    for (const auto& path : info->image_paths()) {
        // Do something with the search path.
        avd->imagePath[i] = stringCopy(path);
    }
    i = 0;
    for (const auto& state : info->image_states()) {
        // Do something with the search path.
        avd->imageState[i] = (char)state - 1;
    }

    avd->sysdir = stringCopy(info->sysdir());
    return avd;
}
