// Auto-generated with: android/scripts/gen-entries.py --mode=static_translator_namespaced_header android/android-emugl/host/libs/libOpenGLESDispatch/gles1_extensions.entries --output=android/android-emugl/host/include/OpenGLESDispatch/gles1_static_translator_namespaced_header.h
// DO NOT EDIT THIS FILE

#pragma once

namespace translator {
namespace gles1 {
EGLAPI void EGLAPIENTRY glCurrentPaletteMatrixARB(GLint index);
EGLAPI void EGLAPIENTRY glMatrixIndexuivARB(GLint size, GLuint * indices);
EGLAPI void EGLAPIENTRY glMatrixIndexPointerARB(GLint size, GLenum type, GLsizei stride, const GLvoid* pointer);
EGLAPI void EGLAPIENTRY glWeightPointerARB(GLint size, GLenum type, GLsizei stride, const GLvoid* pointer);
EGLAPI void EGLAPIENTRY glTexGenf(GLenum coord, GLenum pname, GLfloat param);
EGLAPI void EGLAPIENTRY glTexGeni(GLenum coord, GLenum pname, GLint param);
EGLAPI void EGLAPIENTRY glTexGenfv(GLenum coord, GLenum pname, const GLfloat * params);
EGLAPI void EGLAPIENTRY glTexGeniv(GLenum coord, GLenum pname, const GLint * params);
EGLAPI void EGLAPIENTRY glGetTexGenfv(GLenum coord, GLenum pname, GLfloat * params);
EGLAPI void EGLAPIENTRY glGetTexGeniv(GLenum coord, GLenum pname, GLint * params);
EGLAPI void EGLAPIENTRY glColorPointerWithDataSize(GLint size, GLenum type, GLsizei stride, const GLvoid * pointer, GLsizei dataSize);
EGLAPI void EGLAPIENTRY glNormalPointerWithDataSize(GLenum type, GLsizei stride, const GLvoid * pointer, GLsizei dataSize);
EGLAPI void EGLAPIENTRY glTexCoordPointerWithDataSize(GLint size, GLenum type, GLsizei stride, const GLvoid * pointer, GLsizei dataSize);
EGLAPI void EGLAPIENTRY glVertexPointerWithDataSize(GLint size, GLenum type, GLsizei stride, const GLvoid * pointer, GLsizei dataSize);
} // namespace translator
} // namespace gles1
