/*
* Copyright (C) 2016 The Android Open Source Project
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#pragma once

#include <GLES/gl.h>
#include <memory>

enum NamedObjectType {
    VERTEXBUFFER,
    TEXTURE,
    RENDERBUFFER,
    FRAMEBUFFER,
    PROGRAM,
    SHADER,
    NUM_OBJECT_TYPES  // Must be last
};

struct GenNameInfo {
    NamedObjectType m_type;
    // put type specified info into the following union
    union {
        GLenum shaderType;
    } m_extraInfo;
    GenNameInfo(const GenNameInfo& genNameInfo);
    GenNameInfo(NamedObjectType type);
    GenNameInfo(GLenum shaderType);
};

typedef unsigned long long ObjectLocalName;

class GlobalNameSpace;

// NamedObject is used to manage GPU names.
// It generates / releases GPU names.
// NamedObject is expected to be encapsulated in a shared pointer when used (see
// NamedObjectPtr). The main purpose to use smart pointers is to have reference
// counters for texture objects, which are frequently shared across contexts and
// share groups when used in EGLImages. The specification of EGLImage says:
//
//    Once an EGLImage is created from an EGLImage source, the memory associated
//    with the EGLImage source will remain allocated (and all EGLImage siblings
//    in all client API contexts will be useable) as long as either of the
//    following conditions is true:
//      A)  Any EGLImage siblings exist in any client API context
//      B)  The EGLImage object exists inside EGL
// Reference: 2.5.2  Lifetime and Usage of EGLImages in
// https://www.khronos.org/registry/egl/extensions/KHR/EGL_KHR_image_base.txt
//
// In our situation, "the memory associated with the EGLImage source" means the
// textures. Thus a shared pointer is needed.
//
// NamedObject owns a function pointer m_glDelete to the glDeleteXXX function.
// The reason why we use a member function pointer instead of directly calling
// GLEScontext::dispatcher().glDeleteXXX, is that NamedObject is built into
// the static library libGLcommon, which is linked by at least 3 shared
// libraries (EGL_translator, GLES_V2_translator, GLES_CM_translator).
// GLEScontext::dispatcher() is owned by the shared library, thus calling
// GLEScontext::dispatcher() may get different results, depending on where it
// is called. What is worse, the dispatcher in EGL_translator does
// not initialize glDeleteXXX functions. Calling
// GLEScontext::dispatcher().glDeleteXXX in EGL_translator will crash. Thus, to
// avoid calling it in the wrong shared library, we need to keep the function
// pointer of the appropriate glDeleteXXX in a non-static object.

class NamedObject {
public:
    NamedObject(GenNameInfo genNameInfo,
                GlobalNameSpace *globalNameSpace);
    ~NamedObject();
    unsigned int getGlobalName() const {return m_globalName;}
private:
    // m_globalName is the name generated by GPU
    unsigned int m_globalName = 0;
    typedef void (GL_APIENTRY *GLdelete) (GLuint);
    GLdelete m_glDelete = nullptr;
    GlobalNameSpace *m_globalNameSpace;
};

typedef std::shared_ptr<NamedObject> NamedObjectPtr;
