/*
* Copyright (C) 2016 The Android Open Source Project
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#pragma once

#include <GLES/gl.h>
#include <memory>

enum NamedObjectType {
    VERTEXBUFFER = 0,
    TEXTURE = 1,
    RENDERBUFFER = 2,
    FRAMEBUFFER = 3,
    PROGRAM = 4,
    SHADER = 5,
    NUM_OBJECT_TYPES = 6  // Must be last
};

struct GenNameInfo {
    NamedObjectType m_type;
    // put type specified info into the following union
    union {
        GLuint shaderType;
    } m_extraInfo;
    GenNameInfo(const GenNameInfo& genNameInfo);
    GenNameInfo(NamedObjectType type);
    GenNameInfo(NamedObjectType type, GLuint shaderType);
};

typedef unsigned long long ObjectLocalName;

class GlobalNameSpace;

class NamedObject {
public:
    // NamedObject is used to manage GPU names.
    // It generates / releases GPU names.
    NamedObject(NamedObjectType type, GLuint shaderType,
                GlobalNameSpace *globalNameSpace);
    ~NamedObject();
    unsigned int getGlobalName() {return m_globalName;}
private:
    // m_globalName is the name generated by GPU
    unsigned int m_globalName = 0;
    typedef void (GL_APIENTRY *GLrelease) (GLsizei, const GLuint *);
    typedef void (GL_APIENTRY *GLdelete) (GLuint);
    GLrelease m_glRelease = nullptr;
    GLdelete m_glDelete = nullptr;
    GlobalNameSpace *m_globalNameSpace;
};

typedef std::shared_ptr<NamedObject> NamedObjectPtr;
