// Generated Code - DO NOT EDIT !!
// generated by 'emugen'
#ifndef __foo_client_base_t_h
#define __foo_client_base_t_h

#include "foo_client_proc.h"


struct foo_client_base_t {

	fooAlphaFunc_client_proc_t fooAlphaFunc;
	fooIsBuffer_client_proc_t fooIsBuffer;
	fooUnsupported_client_proc_t fooUnsupported;
	fooDoEncoderFlush_client_proc_t fooDoEncoderFlush;
	fooTakeConstVoidPtrConstPtr_client_proc_t fooTakeConstVoidPtrConstPtr;
};

#endif
