alpha-debian-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-alpha-cross

amd64-debian-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-amd64-cross

amd64-debian-user-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-all-test-cross

arm64-debian-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-arm64-cross

armel-debian-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-armel-cross

armhf-debian-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-armhf-cross

hexagon-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-hexagon-cross

hppa-debian-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-hppa-cross

m68k-debian-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-m68k-cross

mips64-debian-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-mips64-cross

mips64el-debian-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-mips64el-cross

mips-debian-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-mips-cross

mipsel-debian-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-mipsel-cross

powerpc-test-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-powerpc-test-cross

ppc64el-debian-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-ppc64el-cross

riscv64-debian-cross-container:
  extends: .container_job_template
  stage: containers
  # as we are currently based on 'sid/unstable' we may break so...
  allow_failure: true
  variables:
    NAME: debian-riscv64-cross

# we can however build TCG tests using a non-sid base
riscv64-debian-test-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-riscv64-test-cross

s390x-debian-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-s390x-cross

sh4-debian-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-sh4-cross

sparc64-debian-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-sparc64-cross

tricore-debian-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-tricore-cross

xtensa-debian-cross-container:
  extends: .container_job_template
  variables:
    NAME: debian-xtensa-cross

cris-fedora-cross-container:
  extends: .container_job_template
  variables:
    NAME: fedora-cris-cross

i386-fedora-cross-container:
  extends: .container_job_template
  variables:
    NAME: fedora-i386-cross

win32-fedora-cross-container:
  extends: .container_job_template
  variables:
    NAME: fedora-win32-cross

win64-fedora-cross-container:
  extends: .container_job_template
  variables:
    NAME: fedora-win64-cross
