// Generated Code - DO NOT EDIT !!
// generated by 'emugen'
#ifndef __foo_wrapper_base_t_h
#define __foo_wrapper_base_t_h

#include "foo_wrapper_proc.h"


struct foo_wrapper_base_t {

	fooAlphaFunc_wrapper_proc_t fooAlphaFunc;
	fooIsBuffer_wrapper_proc_t fooIsBuffer;
	fooUnsupported_wrapper_proc_t fooUnsupported;
	fooDoEncoderFlush_wrapper_proc_t fooDoEncoderFlush;
	fooTakeConstVoidPtrConstPtr_wrapper_proc_t fooTakeConstVoidPtrConstPtr;
};

#endif
