/* This file is autogenerated by tracetool, do not edit. */

#ifndef TRACE_HW_VFIO_GENERATED_TRACERS_H
#define TRACE_HW_VFIO_GENERATED_TRACERS_H

#include "qemu-common.h"
#include "trace/control.h"

extern TraceEvent _TRACE_VFIO_INTX_INTERRUPT_EVENT;
extern TraceEvent _TRACE_VFIO_INTX_EOI_EVENT;
extern TraceEvent _TRACE_VFIO_INTX_ENABLE_KVM_EVENT;
extern TraceEvent _TRACE_VFIO_INTX_DISABLE_KVM_EVENT;
extern TraceEvent _TRACE_VFIO_INTX_UPDATE_EVENT;
extern TraceEvent _TRACE_VFIO_INTX_ENABLE_EVENT;
extern TraceEvent _TRACE_VFIO_INTX_DISABLE_EVENT;
extern TraceEvent _TRACE_VFIO_MSI_INTERRUPT_EVENT;
extern TraceEvent _TRACE_VFIO_MSIX_VECTOR_DO_USE_EVENT;
extern TraceEvent _TRACE_VFIO_MSIX_VECTOR_RELEASE_EVENT;
extern TraceEvent _TRACE_VFIO_MSIX_ENABLE_EVENT;
extern TraceEvent _TRACE_VFIO_MSIX_PBA_DISABLE_EVENT;
extern TraceEvent _TRACE_VFIO_MSIX_PBA_ENABLE_EVENT;
extern TraceEvent _TRACE_VFIO_MSIX_DISABLE_EVENT;
extern TraceEvent _TRACE_VFIO_MSIX_FIXUP_EVENT;
extern TraceEvent _TRACE_VFIO_MSIX_RELO_COST_EVENT;
extern TraceEvent _TRACE_VFIO_MSIX_RELO_EVENT;
extern TraceEvent _TRACE_VFIO_MSI_ENABLE_EVENT;
extern TraceEvent _TRACE_VFIO_MSI_DISABLE_EVENT;
extern TraceEvent _TRACE_VFIO_PCI_LOAD_ROM_EVENT;
extern TraceEvent _TRACE_VFIO_ROM_READ_EVENT;
extern TraceEvent _TRACE_VFIO_PCI_SIZE_ROM_EVENT;
extern TraceEvent _TRACE_VFIO_VGA_WRITE_EVENT;
extern TraceEvent _TRACE_VFIO_VGA_READ_EVENT;
extern TraceEvent _TRACE_VFIO_PCI_READ_CONFIG_EVENT;
extern TraceEvent _TRACE_VFIO_PCI_WRITE_CONFIG_EVENT;
extern TraceEvent _TRACE_VFIO_MSI_SETUP_EVENT;
extern TraceEvent _TRACE_VFIO_MSIX_EARLY_SETUP_EVENT;
extern TraceEvent _TRACE_VFIO_CHECK_PCIE_FLR_EVENT;
extern TraceEvent _TRACE_VFIO_CHECK_PM_RESET_EVENT;
extern TraceEvent _TRACE_VFIO_CHECK_AF_FLR_EVENT;
extern TraceEvent _TRACE_VFIO_PCI_HOT_RESET_EVENT;
extern TraceEvent _TRACE_VFIO_PCI_HOT_RESET_HAS_DEP_DEVICES_EVENT;
extern TraceEvent _TRACE_VFIO_PCI_HOT_RESET_DEP_DEVICES_EVENT;
extern TraceEvent _TRACE_VFIO_PCI_HOT_RESET_RESULT_EVENT;
extern TraceEvent _TRACE_VFIO_POPULATE_DEVICE_CONFIG_EVENT;
extern TraceEvent _TRACE_VFIO_POPULATE_DEVICE_GET_IRQ_INFO_FAILURE_EVENT;
extern TraceEvent _TRACE_VFIO_REALIZE_EVENT;
extern TraceEvent _TRACE_VFIO_ADD_EXT_CAP_DROPPED_EVENT;
extern TraceEvent _TRACE_VFIO_PCI_RESET_EVENT;
extern TraceEvent _TRACE_VFIO_PCI_RESET_FLR_EVENT;
extern TraceEvent _TRACE_VFIO_PCI_RESET_PM_EVENT;
extern TraceEvent _TRACE_VFIO_PCI_EMULATED_VENDOR_ID_EVENT;
extern TraceEvent _TRACE_VFIO_PCI_EMULATED_DEVICE_ID_EVENT;
extern TraceEvent _TRACE_VFIO_PCI_EMULATED_SUB_VENDOR_ID_EVENT;
extern TraceEvent _TRACE_VFIO_PCI_EMULATED_SUB_DEVICE_ID_EVENT;
extern TraceEvent _TRACE_VFIO_QUIRK_ROM_BLACKLISTED_EVENT;
extern TraceEvent _TRACE_VFIO_QUIRK_GENERIC_WINDOW_ADDRESS_WRITE_EVENT;
extern TraceEvent _TRACE_VFIO_QUIRK_GENERIC_WINDOW_DATA_READ_EVENT;
extern TraceEvent _TRACE_VFIO_QUIRK_GENERIC_WINDOW_DATA_WRITE_EVENT;
extern TraceEvent _TRACE_VFIO_QUIRK_GENERIC_MIRROR_READ_EVENT;
extern TraceEvent _TRACE_VFIO_QUIRK_GENERIC_MIRROR_WRITE_EVENT;
extern TraceEvent _TRACE_VFIO_QUIRK_ATI_3C3_READ_EVENT;
extern TraceEvent _TRACE_VFIO_QUIRK_ATI_3C3_PROBE_EVENT;
extern TraceEvent _TRACE_VFIO_QUIRK_ATI_BAR4_PROBE_EVENT;
extern TraceEvent _TRACE_VFIO_QUIRK_ATI_BAR2_PROBE_EVENT;
extern TraceEvent _TRACE_VFIO_QUIRK_NVIDIA_3D0_STATE_EVENT;
extern TraceEvent _TRACE_VFIO_QUIRK_NVIDIA_3D0_READ_EVENT;
extern TraceEvent _TRACE_VFIO_QUIRK_NVIDIA_3D0_WRITE_EVENT;
extern TraceEvent _TRACE_VFIO_QUIRK_NVIDIA_3D0_PROBE_EVENT;
extern TraceEvent _TRACE_VFIO_QUIRK_NVIDIA_BAR5_STATE_EVENT;
extern TraceEvent _TRACE_VFIO_QUIRK_NVIDIA_BAR5_PROBE_EVENT;
extern TraceEvent _TRACE_VFIO_QUIRK_NVIDIA_BAR0_MSI_ACK_EVENT;
extern TraceEvent _TRACE_VFIO_QUIRK_NVIDIA_BAR0_PROBE_EVENT;
extern TraceEvent _TRACE_VFIO_QUIRK_RTL8168_FAKE_LATCH_EVENT;
extern TraceEvent _TRACE_VFIO_QUIRK_RTL8168_MSIX_WRITE_EVENT;
extern TraceEvent _TRACE_VFIO_QUIRK_RTL8168_MSIX_READ_EVENT;
extern TraceEvent _TRACE_VFIO_QUIRK_RTL8168_PROBE_EVENT;
extern TraceEvent _TRACE_VFIO_QUIRK_ATI_BONAIRE_RESET_SKIPPED_EVENT;
extern TraceEvent _TRACE_VFIO_QUIRK_ATI_BONAIRE_RESET_NO_SMC_EVENT;
extern TraceEvent _TRACE_VFIO_QUIRK_ATI_BONAIRE_RESET_TIMEOUT_EVENT;
extern TraceEvent _TRACE_VFIO_QUIRK_ATI_BONAIRE_RESET_DONE_EVENT;
extern TraceEvent _TRACE_VFIO_QUIRK_ATI_BONAIRE_RESET_EVENT;
extern TraceEvent _TRACE_VFIO_PCI_IGD_BAR4_WRITE_EVENT;
extern TraceEvent _TRACE_VFIO_PCI_IGD_BDSM_ENABLED_EVENT;
extern TraceEvent _TRACE_VFIO_PCI_IGD_OPREGION_ENABLED_EVENT;
extern TraceEvent _TRACE_VFIO_PCI_IGD_HOST_BRIDGE_ENABLED_EVENT;
extern TraceEvent _TRACE_VFIO_PCI_IGD_LPC_BRIDGE_ENABLED_EVENT;
extern TraceEvent _TRACE_VFIO_REGION_WRITE_EVENT;
extern TraceEvent _TRACE_VFIO_REGION_READ_EVENT;
extern TraceEvent _TRACE_VFIO_IOMMU_MAP_NOTIFY_EVENT;
extern TraceEvent _TRACE_VFIO_LISTENER_REGION_ADD_SKIP_EVENT;
extern TraceEvent _TRACE_VFIO_LISTENER_REGION_ADD_IOMMU_EVENT;
extern TraceEvent _TRACE_VFIO_LISTENER_REGION_ADD_RAM_EVENT;
extern TraceEvent _TRACE_VFIO_LISTENER_REGION_ADD_NO_DMA_MAP_EVENT;
extern TraceEvent _TRACE_VFIO_LISTENER_REGION_DEL_SKIP_EVENT;
extern TraceEvent _TRACE_VFIO_LISTENER_REGION_DEL_EVENT;
extern TraceEvent _TRACE_VFIO_DISCONNECT_CONTAINER_EVENT;
extern TraceEvent _TRACE_VFIO_PUT_GROUP_EVENT;
extern TraceEvent _TRACE_VFIO_GET_DEVICE_EVENT;
extern TraceEvent _TRACE_VFIO_PUT_BASE_DEVICE_EVENT;
extern TraceEvent _TRACE_VFIO_REGION_SETUP_EVENT;
extern TraceEvent _TRACE_VFIO_REGION_MMAP_FAULT_EVENT;
extern TraceEvent _TRACE_VFIO_REGION_MMAP_EVENT;
extern TraceEvent _TRACE_VFIO_REGION_EXIT_EVENT;
extern TraceEvent _TRACE_VFIO_REGION_FINALIZE_EVENT;
extern TraceEvent _TRACE_VFIO_REGION_MMAPS_SET_ENABLED_EVENT;
extern TraceEvent _TRACE_VFIO_REGION_SPARSE_MMAP_HEADER_EVENT;
extern TraceEvent _TRACE_VFIO_REGION_SPARSE_MMAP_ENTRY_EVENT;
extern TraceEvent _TRACE_VFIO_GET_DEV_REGION_EVENT;
extern TraceEvent _TRACE_VFIO_PLATFORM_BASE_DEVICE_INIT_EVENT;
extern TraceEvent _TRACE_VFIO_PLATFORM_REALIZE_EVENT;
extern TraceEvent _TRACE_VFIO_PLATFORM_EOI_EVENT;
extern TraceEvent _TRACE_VFIO_PLATFORM_INTP_MMAP_ENABLE_EVENT;
extern TraceEvent _TRACE_VFIO_PLATFORM_INTP_INTERRUPT_EVENT;
extern TraceEvent _TRACE_VFIO_PLATFORM_INTP_INJECT_PENDING_LOCKHELD_EVENT;
extern TraceEvent _TRACE_VFIO_PLATFORM_POPULATE_INTERRUPTS_EVENT;
extern TraceEvent _TRACE_VFIO_INTP_INTERRUPT_SET_PENDING_EVENT;
extern TraceEvent _TRACE_VFIO_PLATFORM_START_LEVEL_IRQFD_INJECTION_EVENT;
extern TraceEvent _TRACE_VFIO_PLATFORM_START_EDGE_IRQFD_INJECTION_EVENT;
extern TraceEvent _TRACE_VFIO_PREREG_LISTENER_REGION_ADD_SKIP_EVENT;
extern TraceEvent _TRACE_VFIO_PREREG_LISTENER_REGION_DEL_SKIP_EVENT;
extern TraceEvent _TRACE_VFIO_PREREG_REGISTER_EVENT;
extern TraceEvent _TRACE_VFIO_PREREG_UNREGISTER_EVENT;
extern TraceEvent _TRACE_VFIO_SPAPR_CREATE_WINDOW_EVENT;
extern TraceEvent _TRACE_VFIO_SPAPR_REMOVE_WINDOW_EVENT;
extern TraceEvent _TRACE_VFIO_SPAPR_GROUP_ATTACH_EVENT;
extern uint16_t _TRACE_VFIO_INTX_INTERRUPT_DSTATE;
extern uint16_t _TRACE_VFIO_INTX_EOI_DSTATE;
extern uint16_t _TRACE_VFIO_INTX_ENABLE_KVM_DSTATE;
extern uint16_t _TRACE_VFIO_INTX_DISABLE_KVM_DSTATE;
extern uint16_t _TRACE_VFIO_INTX_UPDATE_DSTATE;
extern uint16_t _TRACE_VFIO_INTX_ENABLE_DSTATE;
extern uint16_t _TRACE_VFIO_INTX_DISABLE_DSTATE;
extern uint16_t _TRACE_VFIO_MSI_INTERRUPT_DSTATE;
extern uint16_t _TRACE_VFIO_MSIX_VECTOR_DO_USE_DSTATE;
extern uint16_t _TRACE_VFIO_MSIX_VECTOR_RELEASE_DSTATE;
extern uint16_t _TRACE_VFIO_MSIX_ENABLE_DSTATE;
extern uint16_t _TRACE_VFIO_MSIX_PBA_DISABLE_DSTATE;
extern uint16_t _TRACE_VFIO_MSIX_PBA_ENABLE_DSTATE;
extern uint16_t _TRACE_VFIO_MSIX_DISABLE_DSTATE;
extern uint16_t _TRACE_VFIO_MSIX_FIXUP_DSTATE;
extern uint16_t _TRACE_VFIO_MSIX_RELO_COST_DSTATE;
extern uint16_t _TRACE_VFIO_MSIX_RELO_DSTATE;
extern uint16_t _TRACE_VFIO_MSI_ENABLE_DSTATE;
extern uint16_t _TRACE_VFIO_MSI_DISABLE_DSTATE;
extern uint16_t _TRACE_VFIO_PCI_LOAD_ROM_DSTATE;
extern uint16_t _TRACE_VFIO_ROM_READ_DSTATE;
extern uint16_t _TRACE_VFIO_PCI_SIZE_ROM_DSTATE;
extern uint16_t _TRACE_VFIO_VGA_WRITE_DSTATE;
extern uint16_t _TRACE_VFIO_VGA_READ_DSTATE;
extern uint16_t _TRACE_VFIO_PCI_READ_CONFIG_DSTATE;
extern uint16_t _TRACE_VFIO_PCI_WRITE_CONFIG_DSTATE;
extern uint16_t _TRACE_VFIO_MSI_SETUP_DSTATE;
extern uint16_t _TRACE_VFIO_MSIX_EARLY_SETUP_DSTATE;
extern uint16_t _TRACE_VFIO_CHECK_PCIE_FLR_DSTATE;
extern uint16_t _TRACE_VFIO_CHECK_PM_RESET_DSTATE;
extern uint16_t _TRACE_VFIO_CHECK_AF_FLR_DSTATE;
extern uint16_t _TRACE_VFIO_PCI_HOT_RESET_DSTATE;
extern uint16_t _TRACE_VFIO_PCI_HOT_RESET_HAS_DEP_DEVICES_DSTATE;
extern uint16_t _TRACE_VFIO_PCI_HOT_RESET_DEP_DEVICES_DSTATE;
extern uint16_t _TRACE_VFIO_PCI_HOT_RESET_RESULT_DSTATE;
extern uint16_t _TRACE_VFIO_POPULATE_DEVICE_CONFIG_DSTATE;
extern uint16_t _TRACE_VFIO_POPULATE_DEVICE_GET_IRQ_INFO_FAILURE_DSTATE;
extern uint16_t _TRACE_VFIO_REALIZE_DSTATE;
extern uint16_t _TRACE_VFIO_ADD_EXT_CAP_DROPPED_DSTATE;
extern uint16_t _TRACE_VFIO_PCI_RESET_DSTATE;
extern uint16_t _TRACE_VFIO_PCI_RESET_FLR_DSTATE;
extern uint16_t _TRACE_VFIO_PCI_RESET_PM_DSTATE;
extern uint16_t _TRACE_VFIO_PCI_EMULATED_VENDOR_ID_DSTATE;
extern uint16_t _TRACE_VFIO_PCI_EMULATED_DEVICE_ID_DSTATE;
extern uint16_t _TRACE_VFIO_PCI_EMULATED_SUB_VENDOR_ID_DSTATE;
extern uint16_t _TRACE_VFIO_PCI_EMULATED_SUB_DEVICE_ID_DSTATE;
extern uint16_t _TRACE_VFIO_QUIRK_ROM_BLACKLISTED_DSTATE;
extern uint16_t _TRACE_VFIO_QUIRK_GENERIC_WINDOW_ADDRESS_WRITE_DSTATE;
extern uint16_t _TRACE_VFIO_QUIRK_GENERIC_WINDOW_DATA_READ_DSTATE;
extern uint16_t _TRACE_VFIO_QUIRK_GENERIC_WINDOW_DATA_WRITE_DSTATE;
extern uint16_t _TRACE_VFIO_QUIRK_GENERIC_MIRROR_READ_DSTATE;
extern uint16_t _TRACE_VFIO_QUIRK_GENERIC_MIRROR_WRITE_DSTATE;
extern uint16_t _TRACE_VFIO_QUIRK_ATI_3C3_READ_DSTATE;
extern uint16_t _TRACE_VFIO_QUIRK_ATI_3C3_PROBE_DSTATE;
extern uint16_t _TRACE_VFIO_QUIRK_ATI_BAR4_PROBE_DSTATE;
extern uint16_t _TRACE_VFIO_QUIRK_ATI_BAR2_PROBE_DSTATE;
extern uint16_t _TRACE_VFIO_QUIRK_NVIDIA_3D0_STATE_DSTATE;
extern uint16_t _TRACE_VFIO_QUIRK_NVIDIA_3D0_READ_DSTATE;
extern uint16_t _TRACE_VFIO_QUIRK_NVIDIA_3D0_WRITE_DSTATE;
extern uint16_t _TRACE_VFIO_QUIRK_NVIDIA_3D0_PROBE_DSTATE;
extern uint16_t _TRACE_VFIO_QUIRK_NVIDIA_BAR5_STATE_DSTATE;
extern uint16_t _TRACE_VFIO_QUIRK_NVIDIA_BAR5_PROBE_DSTATE;
extern uint16_t _TRACE_VFIO_QUIRK_NVIDIA_BAR0_MSI_ACK_DSTATE;
extern uint16_t _TRACE_VFIO_QUIRK_NVIDIA_BAR0_PROBE_DSTATE;
extern uint16_t _TRACE_VFIO_QUIRK_RTL8168_FAKE_LATCH_DSTATE;
extern uint16_t _TRACE_VFIO_QUIRK_RTL8168_MSIX_WRITE_DSTATE;
extern uint16_t _TRACE_VFIO_QUIRK_RTL8168_MSIX_READ_DSTATE;
extern uint16_t _TRACE_VFIO_QUIRK_RTL8168_PROBE_DSTATE;
extern uint16_t _TRACE_VFIO_QUIRK_ATI_BONAIRE_RESET_SKIPPED_DSTATE;
extern uint16_t _TRACE_VFIO_QUIRK_ATI_BONAIRE_RESET_NO_SMC_DSTATE;
extern uint16_t _TRACE_VFIO_QUIRK_ATI_BONAIRE_RESET_TIMEOUT_DSTATE;
extern uint16_t _TRACE_VFIO_QUIRK_ATI_BONAIRE_RESET_DONE_DSTATE;
extern uint16_t _TRACE_VFIO_QUIRK_ATI_BONAIRE_RESET_DSTATE;
extern uint16_t _TRACE_VFIO_PCI_IGD_BAR4_WRITE_DSTATE;
extern uint16_t _TRACE_VFIO_PCI_IGD_BDSM_ENABLED_DSTATE;
extern uint16_t _TRACE_VFIO_PCI_IGD_OPREGION_ENABLED_DSTATE;
extern uint16_t _TRACE_VFIO_PCI_IGD_HOST_BRIDGE_ENABLED_DSTATE;
extern uint16_t _TRACE_VFIO_PCI_IGD_LPC_BRIDGE_ENABLED_DSTATE;
extern uint16_t _TRACE_VFIO_REGION_WRITE_DSTATE;
extern uint16_t _TRACE_VFIO_REGION_READ_DSTATE;
extern uint16_t _TRACE_VFIO_IOMMU_MAP_NOTIFY_DSTATE;
extern uint16_t _TRACE_VFIO_LISTENER_REGION_ADD_SKIP_DSTATE;
extern uint16_t _TRACE_VFIO_LISTENER_REGION_ADD_IOMMU_DSTATE;
extern uint16_t _TRACE_VFIO_LISTENER_REGION_ADD_RAM_DSTATE;
extern uint16_t _TRACE_VFIO_LISTENER_REGION_ADD_NO_DMA_MAP_DSTATE;
extern uint16_t _TRACE_VFIO_LISTENER_REGION_DEL_SKIP_DSTATE;
extern uint16_t _TRACE_VFIO_LISTENER_REGION_DEL_DSTATE;
extern uint16_t _TRACE_VFIO_DISCONNECT_CONTAINER_DSTATE;
extern uint16_t _TRACE_VFIO_PUT_GROUP_DSTATE;
extern uint16_t _TRACE_VFIO_GET_DEVICE_DSTATE;
extern uint16_t _TRACE_VFIO_PUT_BASE_DEVICE_DSTATE;
extern uint16_t _TRACE_VFIO_REGION_SETUP_DSTATE;
extern uint16_t _TRACE_VFIO_REGION_MMAP_FAULT_DSTATE;
extern uint16_t _TRACE_VFIO_REGION_MMAP_DSTATE;
extern uint16_t _TRACE_VFIO_REGION_EXIT_DSTATE;
extern uint16_t _TRACE_VFIO_REGION_FINALIZE_DSTATE;
extern uint16_t _TRACE_VFIO_REGION_MMAPS_SET_ENABLED_DSTATE;
extern uint16_t _TRACE_VFIO_REGION_SPARSE_MMAP_HEADER_DSTATE;
extern uint16_t _TRACE_VFIO_REGION_SPARSE_MMAP_ENTRY_DSTATE;
extern uint16_t _TRACE_VFIO_GET_DEV_REGION_DSTATE;
extern uint16_t _TRACE_VFIO_PLATFORM_BASE_DEVICE_INIT_DSTATE;
extern uint16_t _TRACE_VFIO_PLATFORM_REALIZE_DSTATE;
extern uint16_t _TRACE_VFIO_PLATFORM_EOI_DSTATE;
extern uint16_t _TRACE_VFIO_PLATFORM_INTP_MMAP_ENABLE_DSTATE;
extern uint16_t _TRACE_VFIO_PLATFORM_INTP_INTERRUPT_DSTATE;
extern uint16_t _TRACE_VFIO_PLATFORM_INTP_INJECT_PENDING_LOCKHELD_DSTATE;
extern uint16_t _TRACE_VFIO_PLATFORM_POPULATE_INTERRUPTS_DSTATE;
extern uint16_t _TRACE_VFIO_INTP_INTERRUPT_SET_PENDING_DSTATE;
extern uint16_t _TRACE_VFIO_PLATFORM_START_LEVEL_IRQFD_INJECTION_DSTATE;
extern uint16_t _TRACE_VFIO_PLATFORM_START_EDGE_IRQFD_INJECTION_DSTATE;
extern uint16_t _TRACE_VFIO_PREREG_LISTENER_REGION_ADD_SKIP_DSTATE;
extern uint16_t _TRACE_VFIO_PREREG_LISTENER_REGION_DEL_SKIP_DSTATE;
extern uint16_t _TRACE_VFIO_PREREG_REGISTER_DSTATE;
extern uint16_t _TRACE_VFIO_PREREG_UNREGISTER_DSTATE;
extern uint16_t _TRACE_VFIO_SPAPR_CREATE_WINDOW_DSTATE;
extern uint16_t _TRACE_VFIO_SPAPR_REMOVE_WINDOW_DSTATE;
extern uint16_t _TRACE_VFIO_SPAPR_GROUP_ATTACH_DSTATE;
#define TRACE_VFIO_INTX_INTERRUPT_ENABLED 1
#define TRACE_VFIO_INTX_EOI_ENABLED 1
#define TRACE_VFIO_INTX_ENABLE_KVM_ENABLED 1
#define TRACE_VFIO_INTX_DISABLE_KVM_ENABLED 1
#define TRACE_VFIO_INTX_UPDATE_ENABLED 1
#define TRACE_VFIO_INTX_ENABLE_ENABLED 1
#define TRACE_VFIO_INTX_DISABLE_ENABLED 1
#define TRACE_VFIO_MSI_INTERRUPT_ENABLED 1
#define TRACE_VFIO_MSIX_VECTOR_DO_USE_ENABLED 1
#define TRACE_VFIO_MSIX_VECTOR_RELEASE_ENABLED 1
#define TRACE_VFIO_MSIX_ENABLE_ENABLED 1
#define TRACE_VFIO_MSIX_PBA_DISABLE_ENABLED 1
#define TRACE_VFIO_MSIX_PBA_ENABLE_ENABLED 1
#define TRACE_VFIO_MSIX_DISABLE_ENABLED 1
#define TRACE_VFIO_MSIX_FIXUP_ENABLED 1
#define TRACE_VFIO_MSIX_RELO_COST_ENABLED 1
#define TRACE_VFIO_MSIX_RELO_ENABLED 1
#define TRACE_VFIO_MSI_ENABLE_ENABLED 1
#define TRACE_VFIO_MSI_DISABLE_ENABLED 1
#define TRACE_VFIO_PCI_LOAD_ROM_ENABLED 1
#define TRACE_VFIO_ROM_READ_ENABLED 1
#define TRACE_VFIO_PCI_SIZE_ROM_ENABLED 1
#define TRACE_VFIO_VGA_WRITE_ENABLED 1
#define TRACE_VFIO_VGA_READ_ENABLED 1
#define TRACE_VFIO_PCI_READ_CONFIG_ENABLED 1
#define TRACE_VFIO_PCI_WRITE_CONFIG_ENABLED 1
#define TRACE_VFIO_MSI_SETUP_ENABLED 1
#define TRACE_VFIO_MSIX_EARLY_SETUP_ENABLED 1
#define TRACE_VFIO_CHECK_PCIE_FLR_ENABLED 1
#define TRACE_VFIO_CHECK_PM_RESET_ENABLED 1
#define TRACE_VFIO_CHECK_AF_FLR_ENABLED 1
#define TRACE_VFIO_PCI_HOT_RESET_ENABLED 1
#define TRACE_VFIO_PCI_HOT_RESET_HAS_DEP_DEVICES_ENABLED 1
#define TRACE_VFIO_PCI_HOT_RESET_DEP_DEVICES_ENABLED 1
#define TRACE_VFIO_PCI_HOT_RESET_RESULT_ENABLED 1
#define TRACE_VFIO_POPULATE_DEVICE_CONFIG_ENABLED 1
#define TRACE_VFIO_POPULATE_DEVICE_GET_IRQ_INFO_FAILURE_ENABLED 1
#define TRACE_VFIO_REALIZE_ENABLED 1
#define TRACE_VFIO_ADD_EXT_CAP_DROPPED_ENABLED 1
#define TRACE_VFIO_PCI_RESET_ENABLED 1
#define TRACE_VFIO_PCI_RESET_FLR_ENABLED 1
#define TRACE_VFIO_PCI_RESET_PM_ENABLED 1
#define TRACE_VFIO_PCI_EMULATED_VENDOR_ID_ENABLED 1
#define TRACE_VFIO_PCI_EMULATED_DEVICE_ID_ENABLED 1
#define TRACE_VFIO_PCI_EMULATED_SUB_VENDOR_ID_ENABLED 1
#define TRACE_VFIO_PCI_EMULATED_SUB_DEVICE_ID_ENABLED 1
#define TRACE_VFIO_QUIRK_ROM_BLACKLISTED_ENABLED 1
#define TRACE_VFIO_QUIRK_GENERIC_WINDOW_ADDRESS_WRITE_ENABLED 1
#define TRACE_VFIO_QUIRK_GENERIC_WINDOW_DATA_READ_ENABLED 1
#define TRACE_VFIO_QUIRK_GENERIC_WINDOW_DATA_WRITE_ENABLED 1
#define TRACE_VFIO_QUIRK_GENERIC_MIRROR_READ_ENABLED 1
#define TRACE_VFIO_QUIRK_GENERIC_MIRROR_WRITE_ENABLED 1
#define TRACE_VFIO_QUIRK_ATI_3C3_READ_ENABLED 1
#define TRACE_VFIO_QUIRK_ATI_3C3_PROBE_ENABLED 1
#define TRACE_VFIO_QUIRK_ATI_BAR4_PROBE_ENABLED 1
#define TRACE_VFIO_QUIRK_ATI_BAR2_PROBE_ENABLED 1
#define TRACE_VFIO_QUIRK_NVIDIA_3D0_STATE_ENABLED 1
#define TRACE_VFIO_QUIRK_NVIDIA_3D0_READ_ENABLED 1
#define TRACE_VFIO_QUIRK_NVIDIA_3D0_WRITE_ENABLED 1
#define TRACE_VFIO_QUIRK_NVIDIA_3D0_PROBE_ENABLED 1
#define TRACE_VFIO_QUIRK_NVIDIA_BAR5_STATE_ENABLED 1
#define TRACE_VFIO_QUIRK_NVIDIA_BAR5_PROBE_ENABLED 1
#define TRACE_VFIO_QUIRK_NVIDIA_BAR0_MSI_ACK_ENABLED 1
#define TRACE_VFIO_QUIRK_NVIDIA_BAR0_PROBE_ENABLED 1
#define TRACE_VFIO_QUIRK_RTL8168_FAKE_LATCH_ENABLED 1
#define TRACE_VFIO_QUIRK_RTL8168_MSIX_WRITE_ENABLED 1
#define TRACE_VFIO_QUIRK_RTL8168_MSIX_READ_ENABLED 1
#define TRACE_VFIO_QUIRK_RTL8168_PROBE_ENABLED 1
#define TRACE_VFIO_QUIRK_ATI_BONAIRE_RESET_SKIPPED_ENABLED 1
#define TRACE_VFIO_QUIRK_ATI_BONAIRE_RESET_NO_SMC_ENABLED 1
#define TRACE_VFIO_QUIRK_ATI_BONAIRE_RESET_TIMEOUT_ENABLED 1
#define TRACE_VFIO_QUIRK_ATI_BONAIRE_RESET_DONE_ENABLED 1
#define TRACE_VFIO_QUIRK_ATI_BONAIRE_RESET_ENABLED 1
#define TRACE_VFIO_PCI_IGD_BAR4_WRITE_ENABLED 1
#define TRACE_VFIO_PCI_IGD_BDSM_ENABLED_ENABLED 1
#define TRACE_VFIO_PCI_IGD_OPREGION_ENABLED_ENABLED 1
#define TRACE_VFIO_PCI_IGD_HOST_BRIDGE_ENABLED_ENABLED 1
#define TRACE_VFIO_PCI_IGD_LPC_BRIDGE_ENABLED_ENABLED 1
#define TRACE_VFIO_REGION_WRITE_ENABLED 1
#define TRACE_VFIO_REGION_READ_ENABLED 1
#define TRACE_VFIO_IOMMU_MAP_NOTIFY_ENABLED 1
#define TRACE_VFIO_LISTENER_REGION_ADD_SKIP_ENABLED 1
#define TRACE_VFIO_LISTENER_REGION_ADD_IOMMU_ENABLED 1
#define TRACE_VFIO_LISTENER_REGION_ADD_RAM_ENABLED 1
#define TRACE_VFIO_LISTENER_REGION_ADD_NO_DMA_MAP_ENABLED 1
#define TRACE_VFIO_LISTENER_REGION_DEL_SKIP_ENABLED 1
#define TRACE_VFIO_LISTENER_REGION_DEL_ENABLED 1
#define TRACE_VFIO_DISCONNECT_CONTAINER_ENABLED 1
#define TRACE_VFIO_PUT_GROUP_ENABLED 1
#define TRACE_VFIO_GET_DEVICE_ENABLED 1
#define TRACE_VFIO_PUT_BASE_DEVICE_ENABLED 1
#define TRACE_VFIO_REGION_SETUP_ENABLED 1
#define TRACE_VFIO_REGION_MMAP_FAULT_ENABLED 1
#define TRACE_VFIO_REGION_MMAP_ENABLED 1
#define TRACE_VFIO_REGION_EXIT_ENABLED 1
#define TRACE_VFIO_REGION_FINALIZE_ENABLED 1
#define TRACE_VFIO_REGION_MMAPS_SET_ENABLED_ENABLED 1
#define TRACE_VFIO_REGION_SPARSE_MMAP_HEADER_ENABLED 1
#define TRACE_VFIO_REGION_SPARSE_MMAP_ENTRY_ENABLED 1
#define TRACE_VFIO_GET_DEV_REGION_ENABLED 1
#define TRACE_VFIO_PLATFORM_BASE_DEVICE_INIT_ENABLED 1
#define TRACE_VFIO_PLATFORM_REALIZE_ENABLED 1
#define TRACE_VFIO_PLATFORM_EOI_ENABLED 1
#define TRACE_VFIO_PLATFORM_INTP_MMAP_ENABLE_ENABLED 1
#define TRACE_VFIO_PLATFORM_INTP_INTERRUPT_ENABLED 1
#define TRACE_VFIO_PLATFORM_INTP_INJECT_PENDING_LOCKHELD_ENABLED 1
#define TRACE_VFIO_PLATFORM_POPULATE_INTERRUPTS_ENABLED 1
#define TRACE_VFIO_INTP_INTERRUPT_SET_PENDING_ENABLED 1
#define TRACE_VFIO_PLATFORM_START_LEVEL_IRQFD_INJECTION_ENABLED 1
#define TRACE_VFIO_PLATFORM_START_EDGE_IRQFD_INJECTION_ENABLED 1
#define TRACE_VFIO_PREREG_LISTENER_REGION_ADD_SKIP_ENABLED 1
#define TRACE_VFIO_PREREG_LISTENER_REGION_DEL_SKIP_ENABLED 1
#define TRACE_VFIO_PREREG_REGISTER_ENABLED 1
#define TRACE_VFIO_PREREG_UNREGISTER_ENABLED 1
#define TRACE_VFIO_SPAPR_CREATE_WINDOW_ENABLED 1
#define TRACE_VFIO_SPAPR_REMOVE_WINDOW_ENABLED 1
#define TRACE_VFIO_SPAPR_GROUP_ATTACH_ENABLED 1

#define TRACE_VFIO_INTX_INTERRUPT_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_intx_interrupt(const char * name, char line)
{
}

static inline void trace_vfio_intx_interrupt(const char * name, char line)
{
    if (true) {
        _nocheck__trace_vfio_intx_interrupt(name, line);
    }
}

#define TRACE_VFIO_INTX_EOI_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_intx_eoi(const char * name)
{
}

static inline void trace_vfio_intx_eoi(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_intx_eoi(name);
    }
}

#define TRACE_VFIO_INTX_ENABLE_KVM_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_intx_enable_kvm(const char * name)
{
}

static inline void trace_vfio_intx_enable_kvm(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_intx_enable_kvm(name);
    }
}

#define TRACE_VFIO_INTX_DISABLE_KVM_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_intx_disable_kvm(const char * name)
{
}

static inline void trace_vfio_intx_disable_kvm(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_intx_disable_kvm(name);
    }
}

#define TRACE_VFIO_INTX_UPDATE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_intx_update(const char * name, int new_irq, int target_irq)
{
}

static inline void trace_vfio_intx_update(const char * name, int new_irq, int target_irq)
{
    if (true) {
        _nocheck__trace_vfio_intx_update(name, new_irq, target_irq);
    }
}

#define TRACE_VFIO_INTX_ENABLE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_intx_enable(const char * name)
{
}

static inline void trace_vfio_intx_enable(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_intx_enable(name);
    }
}

#define TRACE_VFIO_INTX_DISABLE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_intx_disable(const char * name)
{
}

static inline void trace_vfio_intx_disable(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_intx_disable(name);
    }
}

#define TRACE_VFIO_MSI_INTERRUPT_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_msi_interrupt(const char * name, int index, uint64_t addr, int data)
{
}

static inline void trace_vfio_msi_interrupt(const char * name, int index, uint64_t addr, int data)
{
    if (true) {
        _nocheck__trace_vfio_msi_interrupt(name, index, addr, data);
    }
}

#define TRACE_VFIO_MSIX_VECTOR_DO_USE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_msix_vector_do_use(const char * name, int index)
{
}

static inline void trace_vfio_msix_vector_do_use(const char * name, int index)
{
    if (true) {
        _nocheck__trace_vfio_msix_vector_do_use(name, index);
    }
}

#define TRACE_VFIO_MSIX_VECTOR_RELEASE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_msix_vector_release(const char * name, int index)
{
}

static inline void trace_vfio_msix_vector_release(const char * name, int index)
{
    if (true) {
        _nocheck__trace_vfio_msix_vector_release(name, index);
    }
}

#define TRACE_VFIO_MSIX_ENABLE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_msix_enable(const char * name)
{
}

static inline void trace_vfio_msix_enable(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_msix_enable(name);
    }
}

#define TRACE_VFIO_MSIX_PBA_DISABLE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_msix_pba_disable(const char * name)
{
}

static inline void trace_vfio_msix_pba_disable(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_msix_pba_disable(name);
    }
}

#define TRACE_VFIO_MSIX_PBA_ENABLE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_msix_pba_enable(const char * name)
{
}

static inline void trace_vfio_msix_pba_enable(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_msix_pba_enable(name);
    }
}

#define TRACE_VFIO_MSIX_DISABLE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_msix_disable(const char * name)
{
}

static inline void trace_vfio_msix_disable(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_msix_disable(name);
    }
}

#define TRACE_VFIO_MSIX_FIXUP_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_msix_fixup(const char * name, int bar, uint64_t start, uint64_t end)
{
}

static inline void trace_vfio_msix_fixup(const char * name, int bar, uint64_t start, uint64_t end)
{
    if (true) {
        _nocheck__trace_vfio_msix_fixup(name, bar, start, end);
    }
}

#define TRACE_VFIO_MSIX_RELO_COST_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_msix_relo_cost(const char * name, int bar, uint64_t cost)
{
}

static inline void trace_vfio_msix_relo_cost(const char * name, int bar, uint64_t cost)
{
    if (true) {
        _nocheck__trace_vfio_msix_relo_cost(name, bar, cost);
    }
}

#define TRACE_VFIO_MSIX_RELO_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_msix_relo(const char * name, int bar, uint64_t offset)
{
}

static inline void trace_vfio_msix_relo(const char * name, int bar, uint64_t offset)
{
    if (true) {
        _nocheck__trace_vfio_msix_relo(name, bar, offset);
    }
}

#define TRACE_VFIO_MSI_ENABLE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_msi_enable(const char * name, int nr_vectors)
{
}

static inline void trace_vfio_msi_enable(const char * name, int nr_vectors)
{
    if (true) {
        _nocheck__trace_vfio_msi_enable(name, nr_vectors);
    }
}

#define TRACE_VFIO_MSI_DISABLE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_msi_disable(const char * name)
{
}

static inline void trace_vfio_msi_disable(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_msi_disable(name);
    }
}

#define TRACE_VFIO_PCI_LOAD_ROM_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_pci_load_rom(const char * name, unsigned long size, unsigned long offset, unsigned long flags)
{
}

static inline void trace_vfio_pci_load_rom(const char * name, unsigned long size, unsigned long offset, unsigned long flags)
{
    if (true) {
        _nocheck__trace_vfio_pci_load_rom(name, size, offset, flags);
    }
}

#define TRACE_VFIO_ROM_READ_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_rom_read(const char * name, uint64_t addr, int size, uint64_t data)
{
}

static inline void trace_vfio_rom_read(const char * name, uint64_t addr, int size, uint64_t data)
{
    if (true) {
        _nocheck__trace_vfio_rom_read(name, addr, size, data);
    }
}

#define TRACE_VFIO_PCI_SIZE_ROM_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_pci_size_rom(const char * name, int size)
{
}

static inline void trace_vfio_pci_size_rom(const char * name, int size)
{
    if (true) {
        _nocheck__trace_vfio_pci_size_rom(name, size);
    }
}

#define TRACE_VFIO_VGA_WRITE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_vga_write(uint64_t addr, uint64_t data, int size)
{
}

static inline void trace_vfio_vga_write(uint64_t addr, uint64_t data, int size)
{
    if (true) {
        _nocheck__trace_vfio_vga_write(addr, data, size);
    }
}

#define TRACE_VFIO_VGA_READ_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_vga_read(uint64_t addr, int size, uint64_t data)
{
}

static inline void trace_vfio_vga_read(uint64_t addr, int size, uint64_t data)
{
    if (true) {
        _nocheck__trace_vfio_vga_read(addr, size, data);
    }
}

#define TRACE_VFIO_PCI_READ_CONFIG_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_pci_read_config(const char * name, int addr, int len, int val)
{
}

static inline void trace_vfio_pci_read_config(const char * name, int addr, int len, int val)
{
    if (true) {
        _nocheck__trace_vfio_pci_read_config(name, addr, len, val);
    }
}

#define TRACE_VFIO_PCI_WRITE_CONFIG_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_pci_write_config(const char * name, int addr, int val, int len)
{
}

static inline void trace_vfio_pci_write_config(const char * name, int addr, int val, int len)
{
    if (true) {
        _nocheck__trace_vfio_pci_write_config(name, addr, val, len);
    }
}

#define TRACE_VFIO_MSI_SETUP_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_msi_setup(const char * name, int pos)
{
}

static inline void trace_vfio_msi_setup(const char * name, int pos)
{
    if (true) {
        _nocheck__trace_vfio_msi_setup(name, pos);
    }
}

#define TRACE_VFIO_MSIX_EARLY_SETUP_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_msix_early_setup(const char * name, int pos, int table_bar, int offset, int entries)
{
}

static inline void trace_vfio_msix_early_setup(const char * name, int pos, int table_bar, int offset, int entries)
{
    if (true) {
        _nocheck__trace_vfio_msix_early_setup(name, pos, table_bar, offset, entries);
    }
}

#define TRACE_VFIO_CHECK_PCIE_FLR_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_check_pcie_flr(const char * name)
{
}

static inline void trace_vfio_check_pcie_flr(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_check_pcie_flr(name);
    }
}

#define TRACE_VFIO_CHECK_PM_RESET_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_check_pm_reset(const char * name)
{
}

static inline void trace_vfio_check_pm_reset(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_check_pm_reset(name);
    }
}

#define TRACE_VFIO_CHECK_AF_FLR_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_check_af_flr(const char * name)
{
}

static inline void trace_vfio_check_af_flr(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_check_af_flr(name);
    }
}

#define TRACE_VFIO_PCI_HOT_RESET_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_pci_hot_reset(const char * name, const char * type)
{
}

static inline void trace_vfio_pci_hot_reset(const char * name, const char * type)
{
    if (true) {
        _nocheck__trace_vfio_pci_hot_reset(name, type);
    }
}

#define TRACE_VFIO_PCI_HOT_RESET_HAS_DEP_DEVICES_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_pci_hot_reset_has_dep_devices(const char * name)
{
}

static inline void trace_vfio_pci_hot_reset_has_dep_devices(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_pci_hot_reset_has_dep_devices(name);
    }
}

#define TRACE_VFIO_PCI_HOT_RESET_DEP_DEVICES_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_pci_hot_reset_dep_devices(int domain, int bus, int slot, int function, int group_id)
{
}

static inline void trace_vfio_pci_hot_reset_dep_devices(int domain, int bus, int slot, int function, int group_id)
{
    if (true) {
        _nocheck__trace_vfio_pci_hot_reset_dep_devices(domain, bus, slot, function, group_id);
    }
}

#define TRACE_VFIO_PCI_HOT_RESET_RESULT_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_pci_hot_reset_result(const char * name, const char * result)
{
}

static inline void trace_vfio_pci_hot_reset_result(const char * name, const char * result)
{
    if (true) {
        _nocheck__trace_vfio_pci_hot_reset_result(name, result);
    }
}

#define TRACE_VFIO_POPULATE_DEVICE_CONFIG_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_populate_device_config(const char * name, unsigned long size, unsigned long offset, unsigned long flags)
{
}

static inline void trace_vfio_populate_device_config(const char * name, unsigned long size, unsigned long offset, unsigned long flags)
{
    if (true) {
        _nocheck__trace_vfio_populate_device_config(name, size, offset, flags);
    }
}

#define TRACE_VFIO_POPULATE_DEVICE_GET_IRQ_INFO_FAILURE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_populate_device_get_irq_info_failure(void)
{
}

static inline void trace_vfio_populate_device_get_irq_info_failure(void)
{
    if (true) {
        _nocheck__trace_vfio_populate_device_get_irq_info_failure();
    }
}

#define TRACE_VFIO_REALIZE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_realize(const char * name, int group_id)
{
}

static inline void trace_vfio_realize(const char * name, int group_id)
{
    if (true) {
        _nocheck__trace_vfio_realize(name, group_id);
    }
}

#define TRACE_VFIO_ADD_EXT_CAP_DROPPED_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_add_ext_cap_dropped(const char * name, uint16_t cap, uint16_t offset)
{
}

static inline void trace_vfio_add_ext_cap_dropped(const char * name, uint16_t cap, uint16_t offset)
{
    if (true) {
        _nocheck__trace_vfio_add_ext_cap_dropped(name, cap, offset);
    }
}

#define TRACE_VFIO_PCI_RESET_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_pci_reset(const char * name)
{
}

static inline void trace_vfio_pci_reset(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_pci_reset(name);
    }
}

#define TRACE_VFIO_PCI_RESET_FLR_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_pci_reset_flr(const char * name)
{
}

static inline void trace_vfio_pci_reset_flr(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_pci_reset_flr(name);
    }
}

#define TRACE_VFIO_PCI_RESET_PM_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_pci_reset_pm(const char * name)
{
}

static inline void trace_vfio_pci_reset_pm(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_pci_reset_pm(name);
    }
}

#define TRACE_VFIO_PCI_EMULATED_VENDOR_ID_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_pci_emulated_vendor_id(const char * name, uint16_t val)
{
}

static inline void trace_vfio_pci_emulated_vendor_id(const char * name, uint16_t val)
{
    if (true) {
        _nocheck__trace_vfio_pci_emulated_vendor_id(name, val);
    }
}

#define TRACE_VFIO_PCI_EMULATED_DEVICE_ID_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_pci_emulated_device_id(const char * name, uint16_t val)
{
}

static inline void trace_vfio_pci_emulated_device_id(const char * name, uint16_t val)
{
    if (true) {
        _nocheck__trace_vfio_pci_emulated_device_id(name, val);
    }
}

#define TRACE_VFIO_PCI_EMULATED_SUB_VENDOR_ID_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_pci_emulated_sub_vendor_id(const char * name, uint16_t val)
{
}

static inline void trace_vfio_pci_emulated_sub_vendor_id(const char * name, uint16_t val)
{
    if (true) {
        _nocheck__trace_vfio_pci_emulated_sub_vendor_id(name, val);
    }
}

#define TRACE_VFIO_PCI_EMULATED_SUB_DEVICE_ID_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_pci_emulated_sub_device_id(const char * name, uint16_t val)
{
}

static inline void trace_vfio_pci_emulated_sub_device_id(const char * name, uint16_t val)
{
    if (true) {
        _nocheck__trace_vfio_pci_emulated_sub_device_id(name, val);
    }
}

#define TRACE_VFIO_QUIRK_ROM_BLACKLISTED_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_quirk_rom_blacklisted(const char * name, uint16_t vid, uint16_t did)
{
}

static inline void trace_vfio_quirk_rom_blacklisted(const char * name, uint16_t vid, uint16_t did)
{
    if (true) {
        _nocheck__trace_vfio_quirk_rom_blacklisted(name, vid, did);
    }
}

#define TRACE_VFIO_QUIRK_GENERIC_WINDOW_ADDRESS_WRITE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_quirk_generic_window_address_write(const char * name, const char * region_name, uint64_t data)
{
}

static inline void trace_vfio_quirk_generic_window_address_write(const char * name, const char * region_name, uint64_t data)
{
    if (true) {
        _nocheck__trace_vfio_quirk_generic_window_address_write(name, region_name, data);
    }
}

#define TRACE_VFIO_QUIRK_GENERIC_WINDOW_DATA_READ_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_quirk_generic_window_data_read(const char * name, const char * region_name, uint64_t data)
{
}

static inline void trace_vfio_quirk_generic_window_data_read(const char * name, const char * region_name, uint64_t data)
{
    if (true) {
        _nocheck__trace_vfio_quirk_generic_window_data_read(name, region_name, data);
    }
}

#define TRACE_VFIO_QUIRK_GENERIC_WINDOW_DATA_WRITE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_quirk_generic_window_data_write(const char * name, const char * region_name, uint64_t data)
{
}

static inline void trace_vfio_quirk_generic_window_data_write(const char * name, const char * region_name, uint64_t data)
{
    if (true) {
        _nocheck__trace_vfio_quirk_generic_window_data_write(name, region_name, data);
    }
}

#define TRACE_VFIO_QUIRK_GENERIC_MIRROR_READ_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_quirk_generic_mirror_read(const char * name, const char * region_name, uint64_t addr, uint64_t data)
{
}

static inline void trace_vfio_quirk_generic_mirror_read(const char * name, const char * region_name, uint64_t addr, uint64_t data)
{
    if (true) {
        _nocheck__trace_vfio_quirk_generic_mirror_read(name, region_name, addr, data);
    }
}

#define TRACE_VFIO_QUIRK_GENERIC_MIRROR_WRITE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_quirk_generic_mirror_write(const char * name, const char * region_name, uint64_t addr, uint64_t data)
{
}

static inline void trace_vfio_quirk_generic_mirror_write(const char * name, const char * region_name, uint64_t addr, uint64_t data)
{
    if (true) {
        _nocheck__trace_vfio_quirk_generic_mirror_write(name, region_name, addr, data);
    }
}

#define TRACE_VFIO_QUIRK_ATI_3C3_READ_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_quirk_ati_3c3_read(const char * name, uint64_t data)
{
}

static inline void trace_vfio_quirk_ati_3c3_read(const char * name, uint64_t data)
{
    if (true) {
        _nocheck__trace_vfio_quirk_ati_3c3_read(name, data);
    }
}

#define TRACE_VFIO_QUIRK_ATI_3C3_PROBE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_quirk_ati_3c3_probe(const char * name)
{
}

static inline void trace_vfio_quirk_ati_3c3_probe(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_quirk_ati_3c3_probe(name);
    }
}

#define TRACE_VFIO_QUIRK_ATI_BAR4_PROBE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_quirk_ati_bar4_probe(const char * name)
{
}

static inline void trace_vfio_quirk_ati_bar4_probe(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_quirk_ati_bar4_probe(name);
    }
}

#define TRACE_VFIO_QUIRK_ATI_BAR2_PROBE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_quirk_ati_bar2_probe(const char * name)
{
}

static inline void trace_vfio_quirk_ati_bar2_probe(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_quirk_ati_bar2_probe(name);
    }
}

#define TRACE_VFIO_QUIRK_NVIDIA_3D0_STATE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_quirk_nvidia_3d0_state(const char * name, const char * state)
{
}

static inline void trace_vfio_quirk_nvidia_3d0_state(const char * name, const char * state)
{
    if (true) {
        _nocheck__trace_vfio_quirk_nvidia_3d0_state(name, state);
    }
}

#define TRACE_VFIO_QUIRK_NVIDIA_3D0_READ_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_quirk_nvidia_3d0_read(const char * name, uint8_t offset, unsigned size, uint64_t val)
{
}

static inline void trace_vfio_quirk_nvidia_3d0_read(const char * name, uint8_t offset, unsigned size, uint64_t val)
{
    if (true) {
        _nocheck__trace_vfio_quirk_nvidia_3d0_read(name, offset, size, val);
    }
}

#define TRACE_VFIO_QUIRK_NVIDIA_3D0_WRITE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_quirk_nvidia_3d0_write(const char * name, uint8_t offset, uint64_t data, unsigned size)
{
}

static inline void trace_vfio_quirk_nvidia_3d0_write(const char * name, uint8_t offset, uint64_t data, unsigned size)
{
    if (true) {
        _nocheck__trace_vfio_quirk_nvidia_3d0_write(name, offset, data, size);
    }
}

#define TRACE_VFIO_QUIRK_NVIDIA_3D0_PROBE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_quirk_nvidia_3d0_probe(const char * name)
{
}

static inline void trace_vfio_quirk_nvidia_3d0_probe(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_quirk_nvidia_3d0_probe(name);
    }
}

#define TRACE_VFIO_QUIRK_NVIDIA_BAR5_STATE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_quirk_nvidia_bar5_state(const char * name, const char * state)
{
}

static inline void trace_vfio_quirk_nvidia_bar5_state(const char * name, const char * state)
{
    if (true) {
        _nocheck__trace_vfio_quirk_nvidia_bar5_state(name, state);
    }
}

#define TRACE_VFIO_QUIRK_NVIDIA_BAR5_PROBE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_quirk_nvidia_bar5_probe(const char * name)
{
}

static inline void trace_vfio_quirk_nvidia_bar5_probe(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_quirk_nvidia_bar5_probe(name);
    }
}

#define TRACE_VFIO_QUIRK_NVIDIA_BAR0_MSI_ACK_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_quirk_nvidia_bar0_msi_ack(const char * name)
{
}

static inline void trace_vfio_quirk_nvidia_bar0_msi_ack(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_quirk_nvidia_bar0_msi_ack(name);
    }
}

#define TRACE_VFIO_QUIRK_NVIDIA_BAR0_PROBE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_quirk_nvidia_bar0_probe(const char * name)
{
}

static inline void trace_vfio_quirk_nvidia_bar0_probe(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_quirk_nvidia_bar0_probe(name);
    }
}

#define TRACE_VFIO_QUIRK_RTL8168_FAKE_LATCH_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_quirk_rtl8168_fake_latch(const char * name, uint64_t val)
{
}

static inline void trace_vfio_quirk_rtl8168_fake_latch(const char * name, uint64_t val)
{
    if (true) {
        _nocheck__trace_vfio_quirk_rtl8168_fake_latch(name, val);
    }
}

#define TRACE_VFIO_QUIRK_RTL8168_MSIX_WRITE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_quirk_rtl8168_msix_write(const char * name, uint16_t offset, uint64_t val)
{
}

static inline void trace_vfio_quirk_rtl8168_msix_write(const char * name, uint16_t offset, uint64_t val)
{
    if (true) {
        _nocheck__trace_vfio_quirk_rtl8168_msix_write(name, offset, val);
    }
}

#define TRACE_VFIO_QUIRK_RTL8168_MSIX_READ_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_quirk_rtl8168_msix_read(const char * name, uint16_t offset, uint64_t val)
{
}

static inline void trace_vfio_quirk_rtl8168_msix_read(const char * name, uint16_t offset, uint64_t val)
{
    if (true) {
        _nocheck__trace_vfio_quirk_rtl8168_msix_read(name, offset, val);
    }
}

#define TRACE_VFIO_QUIRK_RTL8168_PROBE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_quirk_rtl8168_probe(const char * name)
{
}

static inline void trace_vfio_quirk_rtl8168_probe(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_quirk_rtl8168_probe(name);
    }
}

#define TRACE_VFIO_QUIRK_ATI_BONAIRE_RESET_SKIPPED_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_quirk_ati_bonaire_reset_skipped(const char * name)
{
}

static inline void trace_vfio_quirk_ati_bonaire_reset_skipped(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_quirk_ati_bonaire_reset_skipped(name);
    }
}

#define TRACE_VFIO_QUIRK_ATI_BONAIRE_RESET_NO_SMC_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_quirk_ati_bonaire_reset_no_smc(const char * name)
{
}

static inline void trace_vfio_quirk_ati_bonaire_reset_no_smc(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_quirk_ati_bonaire_reset_no_smc(name);
    }
}

#define TRACE_VFIO_QUIRK_ATI_BONAIRE_RESET_TIMEOUT_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_quirk_ati_bonaire_reset_timeout(const char * name)
{
}

static inline void trace_vfio_quirk_ati_bonaire_reset_timeout(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_quirk_ati_bonaire_reset_timeout(name);
    }
}

#define TRACE_VFIO_QUIRK_ATI_BONAIRE_RESET_DONE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_quirk_ati_bonaire_reset_done(const char * name)
{
}

static inline void trace_vfio_quirk_ati_bonaire_reset_done(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_quirk_ati_bonaire_reset_done(name);
    }
}

#define TRACE_VFIO_QUIRK_ATI_BONAIRE_RESET_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_quirk_ati_bonaire_reset(const char * name)
{
}

static inline void trace_vfio_quirk_ati_bonaire_reset(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_quirk_ati_bonaire_reset(name);
    }
}

#define TRACE_VFIO_PCI_IGD_BAR4_WRITE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_pci_igd_bar4_write(const char * name, uint32_t index, uint32_t data, uint32_t base)
{
}

static inline void trace_vfio_pci_igd_bar4_write(const char * name, uint32_t index, uint32_t data, uint32_t base)
{
    if (true) {
        _nocheck__trace_vfio_pci_igd_bar4_write(name, index, data, base);
    }
}

#define TRACE_VFIO_PCI_IGD_BDSM_ENABLED_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_pci_igd_bdsm_enabled(const char * name, int size)
{
}

static inline void trace_vfio_pci_igd_bdsm_enabled(const char * name, int size)
{
    if (true) {
        _nocheck__trace_vfio_pci_igd_bdsm_enabled(name, size);
    }
}

#define TRACE_VFIO_PCI_IGD_OPREGION_ENABLED_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_pci_igd_opregion_enabled(const char * name)
{
}

static inline void trace_vfio_pci_igd_opregion_enabled(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_pci_igd_opregion_enabled(name);
    }
}

#define TRACE_VFIO_PCI_IGD_HOST_BRIDGE_ENABLED_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_pci_igd_host_bridge_enabled(const char * name)
{
}

static inline void trace_vfio_pci_igd_host_bridge_enabled(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_pci_igd_host_bridge_enabled(name);
    }
}

#define TRACE_VFIO_PCI_IGD_LPC_BRIDGE_ENABLED_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_pci_igd_lpc_bridge_enabled(const char * name)
{
}

static inline void trace_vfio_pci_igd_lpc_bridge_enabled(const char * name)
{
    if (true) {
        _nocheck__trace_vfio_pci_igd_lpc_bridge_enabled(name);
    }
}

#define TRACE_VFIO_REGION_WRITE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_region_write(const char * name, int index, uint64_t addr, uint64_t data, unsigned size)
{
}

static inline void trace_vfio_region_write(const char * name, int index, uint64_t addr, uint64_t data, unsigned size)
{
    if (true) {
        _nocheck__trace_vfio_region_write(name, index, addr, data, size);
    }
}

#define TRACE_VFIO_REGION_READ_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_region_read(char * name, int index, uint64_t addr, unsigned size, uint64_t data)
{
}

static inline void trace_vfio_region_read(char * name, int index, uint64_t addr, unsigned size, uint64_t data)
{
    if (true) {
        _nocheck__trace_vfio_region_read(name, index, addr, size, data);
    }
}

#define TRACE_VFIO_IOMMU_MAP_NOTIFY_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_iommu_map_notify(const char * op, uint64_t iova_start, uint64_t iova_end)
{
}

static inline void trace_vfio_iommu_map_notify(const char * op, uint64_t iova_start, uint64_t iova_end)
{
    if (true) {
        _nocheck__trace_vfio_iommu_map_notify(op, iova_start, iova_end);
    }
}

#define TRACE_VFIO_LISTENER_REGION_ADD_SKIP_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_listener_region_add_skip(uint64_t start, uint64_t end)
{
}

static inline void trace_vfio_listener_region_add_skip(uint64_t start, uint64_t end)
{
    if (true) {
        _nocheck__trace_vfio_listener_region_add_skip(start, end);
    }
}

#define TRACE_VFIO_LISTENER_REGION_ADD_IOMMU_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_listener_region_add_iommu(uint64_t start, uint64_t end)
{
}

static inline void trace_vfio_listener_region_add_iommu(uint64_t start, uint64_t end)
{
    if (true) {
        _nocheck__trace_vfio_listener_region_add_iommu(start, end);
    }
}

#define TRACE_VFIO_LISTENER_REGION_ADD_RAM_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_listener_region_add_ram(uint64_t iova_start, uint64_t iova_end, void * vaddr)
{
}

static inline void trace_vfio_listener_region_add_ram(uint64_t iova_start, uint64_t iova_end, void * vaddr)
{
    if (true) {
        _nocheck__trace_vfio_listener_region_add_ram(iova_start, iova_end, vaddr);
    }
}

#define TRACE_VFIO_LISTENER_REGION_ADD_NO_DMA_MAP_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_listener_region_add_no_dma_map(const char * name, uint64_t iova, uint64_t size, uint64_t page_size)
{
}

static inline void trace_vfio_listener_region_add_no_dma_map(const char * name, uint64_t iova, uint64_t size, uint64_t page_size)
{
    if (true) {
        _nocheck__trace_vfio_listener_region_add_no_dma_map(name, iova, size, page_size);
    }
}

#define TRACE_VFIO_LISTENER_REGION_DEL_SKIP_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_listener_region_del_skip(uint64_t start, uint64_t end)
{
}

static inline void trace_vfio_listener_region_del_skip(uint64_t start, uint64_t end)
{
    if (true) {
        _nocheck__trace_vfio_listener_region_del_skip(start, end);
    }
}

#define TRACE_VFIO_LISTENER_REGION_DEL_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_listener_region_del(uint64_t start, uint64_t end)
{
}

static inline void trace_vfio_listener_region_del(uint64_t start, uint64_t end)
{
    if (true) {
        _nocheck__trace_vfio_listener_region_del(start, end);
    }
}

#define TRACE_VFIO_DISCONNECT_CONTAINER_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_disconnect_container(int fd)
{
}

static inline void trace_vfio_disconnect_container(int fd)
{
    if (true) {
        _nocheck__trace_vfio_disconnect_container(fd);
    }
}

#define TRACE_VFIO_PUT_GROUP_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_put_group(int fd)
{
}

static inline void trace_vfio_put_group(int fd)
{
    if (true) {
        _nocheck__trace_vfio_put_group(fd);
    }
}

#define TRACE_VFIO_GET_DEVICE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_get_device(const char * name, unsigned int flags, unsigned int num_regions, unsigned int num_irqs)
{
}

static inline void trace_vfio_get_device(const char * name, unsigned int flags, unsigned int num_regions, unsigned int num_irqs)
{
    if (true) {
        _nocheck__trace_vfio_get_device(name, flags, num_regions, num_irqs);
    }
}

#define TRACE_VFIO_PUT_BASE_DEVICE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_put_base_device(int fd)
{
}

static inline void trace_vfio_put_base_device(int fd)
{
    if (true) {
        _nocheck__trace_vfio_put_base_device(fd);
    }
}

#define TRACE_VFIO_REGION_SETUP_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_region_setup(const char * dev, int index, const char * name, unsigned long flags, unsigned long offset, unsigned long size)
{
}

static inline void trace_vfio_region_setup(const char * dev, int index, const char * name, unsigned long flags, unsigned long offset, unsigned long size)
{
    if (true) {
        _nocheck__trace_vfio_region_setup(dev, index, name, flags, offset, size);
    }
}

#define TRACE_VFIO_REGION_MMAP_FAULT_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_region_mmap_fault(const char * name, int index, unsigned long offset, unsigned long size, int fault)
{
}

static inline void trace_vfio_region_mmap_fault(const char * name, int index, unsigned long offset, unsigned long size, int fault)
{
    if (true) {
        _nocheck__trace_vfio_region_mmap_fault(name, index, offset, size, fault);
    }
}

#define TRACE_VFIO_REGION_MMAP_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_region_mmap(const char * name, unsigned long offset, unsigned long end)
{
}

static inline void trace_vfio_region_mmap(const char * name, unsigned long offset, unsigned long end)
{
    if (true) {
        _nocheck__trace_vfio_region_mmap(name, offset, end);
    }
}

#define TRACE_VFIO_REGION_EXIT_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_region_exit(const char * name, int index)
{
}

static inline void trace_vfio_region_exit(const char * name, int index)
{
    if (true) {
        _nocheck__trace_vfio_region_exit(name, index);
    }
}

#define TRACE_VFIO_REGION_FINALIZE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_region_finalize(const char * name, int index)
{
}

static inline void trace_vfio_region_finalize(const char * name, int index)
{
    if (true) {
        _nocheck__trace_vfio_region_finalize(name, index);
    }
}

#define TRACE_VFIO_REGION_MMAPS_SET_ENABLED_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_region_mmaps_set_enabled(const char * name, bool enabled)
{
}

static inline void trace_vfio_region_mmaps_set_enabled(const char * name, bool enabled)
{
    if (true) {
        _nocheck__trace_vfio_region_mmaps_set_enabled(name, enabled);
    }
}

#define TRACE_VFIO_REGION_SPARSE_MMAP_HEADER_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_region_sparse_mmap_header(const char * name, int index, int nr_areas)
{
}

static inline void trace_vfio_region_sparse_mmap_header(const char * name, int index, int nr_areas)
{
    if (true) {
        _nocheck__trace_vfio_region_sparse_mmap_header(name, index, nr_areas);
    }
}

#define TRACE_VFIO_REGION_SPARSE_MMAP_ENTRY_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_region_sparse_mmap_entry(int i, unsigned long start, unsigned long end)
{
}

static inline void trace_vfio_region_sparse_mmap_entry(int i, unsigned long start, unsigned long end)
{
    if (true) {
        _nocheck__trace_vfio_region_sparse_mmap_entry(i, start, end);
    }
}

#define TRACE_VFIO_GET_DEV_REGION_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_get_dev_region(const char * name, int index, uint32_t type, uint32_t subtype)
{
}

static inline void trace_vfio_get_dev_region(const char * name, int index, uint32_t type, uint32_t subtype)
{
    if (true) {
        _nocheck__trace_vfio_get_dev_region(name, index, type, subtype);
    }
}

#define TRACE_VFIO_PLATFORM_BASE_DEVICE_INIT_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_platform_base_device_init(char * name, int groupid)
{
}

static inline void trace_vfio_platform_base_device_init(char * name, int groupid)
{
    if (true) {
        _nocheck__trace_vfio_platform_base_device_init(name, groupid);
    }
}

#define TRACE_VFIO_PLATFORM_REALIZE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_platform_realize(char * name, char * compat)
{
}

static inline void trace_vfio_platform_realize(char * name, char * compat)
{
    if (true) {
        _nocheck__trace_vfio_platform_realize(name, compat);
    }
}

#define TRACE_VFIO_PLATFORM_EOI_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_platform_eoi(int pin, int fd)
{
}

static inline void trace_vfio_platform_eoi(int pin, int fd)
{
    if (true) {
        _nocheck__trace_vfio_platform_eoi(pin, fd);
    }
}

#define TRACE_VFIO_PLATFORM_INTP_MMAP_ENABLE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_platform_intp_mmap_enable(int pin)
{
}

static inline void trace_vfio_platform_intp_mmap_enable(int pin)
{
    if (true) {
        _nocheck__trace_vfio_platform_intp_mmap_enable(pin);
    }
}

#define TRACE_VFIO_PLATFORM_INTP_INTERRUPT_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_platform_intp_interrupt(int pin, int fd)
{
}

static inline void trace_vfio_platform_intp_interrupt(int pin, int fd)
{
    if (true) {
        _nocheck__trace_vfio_platform_intp_interrupt(pin, fd);
    }
}

#define TRACE_VFIO_PLATFORM_INTP_INJECT_PENDING_LOCKHELD_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_platform_intp_inject_pending_lockheld(int pin, int fd)
{
}

static inline void trace_vfio_platform_intp_inject_pending_lockheld(int pin, int fd)
{
    if (true) {
        _nocheck__trace_vfio_platform_intp_inject_pending_lockheld(pin, fd);
    }
}

#define TRACE_VFIO_PLATFORM_POPULATE_INTERRUPTS_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_platform_populate_interrupts(int pin, int count, int flags)
{
}

static inline void trace_vfio_platform_populate_interrupts(int pin, int count, int flags)
{
    if (true) {
        _nocheck__trace_vfio_platform_populate_interrupts(pin, count, flags);
    }
}

#define TRACE_VFIO_INTP_INTERRUPT_SET_PENDING_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_intp_interrupt_set_pending(int index)
{
}

static inline void trace_vfio_intp_interrupt_set_pending(int index)
{
    if (true) {
        _nocheck__trace_vfio_intp_interrupt_set_pending(index);
    }
}

#define TRACE_VFIO_PLATFORM_START_LEVEL_IRQFD_INJECTION_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_platform_start_level_irqfd_injection(int index, int fd, int resamplefd)
{
}

static inline void trace_vfio_platform_start_level_irqfd_injection(int index, int fd, int resamplefd)
{
    if (true) {
        _nocheck__trace_vfio_platform_start_level_irqfd_injection(index, fd, resamplefd);
    }
}

#define TRACE_VFIO_PLATFORM_START_EDGE_IRQFD_INJECTION_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_platform_start_edge_irqfd_injection(int index, int fd)
{
}

static inline void trace_vfio_platform_start_edge_irqfd_injection(int index, int fd)
{
    if (true) {
        _nocheck__trace_vfio_platform_start_edge_irqfd_injection(index, fd);
    }
}

#define TRACE_VFIO_PREREG_LISTENER_REGION_ADD_SKIP_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_prereg_listener_region_add_skip(uint64_t start, uint64_t end)
{
}

static inline void trace_vfio_prereg_listener_region_add_skip(uint64_t start, uint64_t end)
{
    if (true) {
        _nocheck__trace_vfio_prereg_listener_region_add_skip(start, end);
    }
}

#define TRACE_VFIO_PREREG_LISTENER_REGION_DEL_SKIP_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_prereg_listener_region_del_skip(uint64_t start, uint64_t end)
{
}

static inline void trace_vfio_prereg_listener_region_del_skip(uint64_t start, uint64_t end)
{
    if (true) {
        _nocheck__trace_vfio_prereg_listener_region_del_skip(start, end);
    }
}

#define TRACE_VFIO_PREREG_REGISTER_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_prereg_register(uint64_t va, uint64_t size, int ret)
{
}

static inline void trace_vfio_prereg_register(uint64_t va, uint64_t size, int ret)
{
    if (true) {
        _nocheck__trace_vfio_prereg_register(va, size, ret);
    }
}

#define TRACE_VFIO_PREREG_UNREGISTER_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_prereg_unregister(uint64_t va, uint64_t size, int ret)
{
}

static inline void trace_vfio_prereg_unregister(uint64_t va, uint64_t size, int ret)
{
    if (true) {
        _nocheck__trace_vfio_prereg_unregister(va, size, ret);
    }
}

#define TRACE_VFIO_SPAPR_CREATE_WINDOW_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_spapr_create_window(int ps, uint64_t ws, uint64_t off)
{
}

static inline void trace_vfio_spapr_create_window(int ps, uint64_t ws, uint64_t off)
{
    if (true) {
        _nocheck__trace_vfio_spapr_create_window(ps, ws, off);
    }
}

#define TRACE_VFIO_SPAPR_REMOVE_WINDOW_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_spapr_remove_window(uint64_t off)
{
}

static inline void trace_vfio_spapr_remove_window(uint64_t off)
{
    if (true) {
        _nocheck__trace_vfio_spapr_remove_window(off);
    }
}

#define TRACE_VFIO_SPAPR_GROUP_ATTACH_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_vfio_spapr_group_attach(int groupfd, int tablefd)
{
}

static inline void trace_vfio_spapr_group_attach(int groupfd, int tablefd)
{
    if (true) {
        _nocheck__trace_vfio_spapr_group_attach(groupfd, tablefd);
    }
}
#endif /* TRACE_HW_VFIO_GENERATED_TRACERS_H */
