# -*- coding: utf-8 -*-
# Copyright 2023 - The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the',  help='License');
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an',  help='AS IS' BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from aemu.configure.base_builder import LibInfo
from aemu.configure.linux_builder import LinuxBuilder

class TrustyBuilder(LinuxBuilder):
    def meson_config(self):
        return [
            "-Dalsa=disabled",
            "-Dandroid=enabled",
            "-Dattr=disabled",
            "-Daudio_drv_list=default",
            "-Dauth_pam=disabled",
            "-Dauto_features=disabled",
            "-Davx2=enabled",
            "-Davx512bw=enabled",
            "-Davx512f=enabled",
            "-Db_pie=false",
            "-Dblkio=disabled",
            "-Dbochs=disabled",
            "-Dbpf=disabled",
            "-Dbrlapi=disabled",
            "-Dbzip2=disabled",
            "-Dcanokey=disabled",
            "-Dcap_ng=disabled",
            "-Dcapstone=disabled",
            "-Dcloop=disabled",
            "-Dcocoa=disabled",
            "-Dcolo_proxy=disabled",
            "-Dcoreaudio=disabled",
            "-Dcrypto_afalg=enabled",
            "-Dcurl=disabled",
            "-Dcurses=disabled",
            "-Ddbus_display=disabled",
            "-Ddmg=disabled",
            "-Ddocs=disabled",
            "-Ddsound=disabled",
            "-Dfdt=auto",
            "-Dfuse_lseek=disabled",
            "-Dfuse=disabled",
            "-Dgcrypt=disabled",
            "-Dgettext=disabled",
            "-Dgio=disabled",
            "-Dglusterfs=disabled",
            "-Dgnutls=disabled",
            "-Dgtk_clipboard=disabled",
            "-Dgtk=disabled",
            "-Dguest_agent_msi=disabled",
            "-Dguest_agent=disabled",
            "-Dhvf=disabled",
            "-Diconv=disabled",
            "-Djack=disabled",
            "-Dkeyring=disabled",
            "-Dkvm=enabled",
            "-Dl2tpv3=disabled",
            "-Dlibdaxctl=disabled",
            "-Dlibdw=disabled",
            "-Dlibiscsi=disabled",
            "-Dlibnfs=disabled",
            "-Dlibpmem=disabled",
            "-Dlibssh=disabled",
            "-Dlibudev=disabled",
            "-Dlibusb=disabled",
            "-Dlibvduse=disabled",
            "-Dlinux_aio=disabled",
            "-Dlinux_io_uring=disabled",
            "-Dlive_block_migration=enabled",
            "-Dlzfse=disabled",
            "-Dlzo=disabled",
            "-Dmalloc_trim=enabled",
            "-Dmembarrier=disabled",
            "-Dmodules=disabled",
            "-Dmpath=disabled",
            "-Dmultiprocess=disabled",
            "-Dnetmap=disabled",
            "-Dnettle=disabled",
            "-Dnuma=disabled",
            "-Dnvmm=disabled",
            "-Dopengl=disabled",
            "-Doss=disabled",
            "-Dpa=disabled",
            "-Dparallels=disabled",
            "-Dpipewire=disabled",
            "-Dpng=disabled",
            "-Dprefer_static=true",
            "-Dpvrdma=disabled",
            "-Dqcow1=disabled",
            "-Dqed=disabled",
            "-Dqga_vss=disabled",
            "-Drbd=disabled",
            "-Drdma=disabled",
            "-Dreplication=disabled",
            "-Dsdl_image=disabled",
            "-Dsdl=disabled",
            "-Dseccomp=disabled",
            "-Dselinux=disabled",
            "-Dslirp_smbd=disabled",
            "-Dslirp=enabled",
            "-Dsmartcard=disabled",
            "-Dsnappy=disabled",
            "-Dsndio=disabled",
            "-Dsparse=disabled",
            "-Dspice_protocol=disabled",
            "-Dspice=disabled",
            "-Dstack_protector=disabled",
            "-Dtools=enabled",
            "-Dtpm=disabled",
            "-Du2f=disabled",
            "-Dusb_redir=disabled",
            "-Dvde=disabled",
            "-Dvdi=disabled",
            "-Dvduse_blk_export=disabled",
            "-Dvfio_user_server=disabled",
            "-Dvhdx=disabled",
            "-Dvhost_crypto=enabled",
            "-Dvhost_kernel=enabled",
            "-Dvhost_net=enabled",
            "-Dvhost_user_blk_server=enabled",
            "-Dvhost_user=enabled",
            "-Dvhost_vdpa=disabled",
            "-Dvirglrenderer=disabled",
            "-Dvirtfs_proxy_helper=disabled",
            "-Dvirtfs=disabled",
            "-Dvmdk=disabled",
            "-Dvmnet=disabled",
            "-Dvnc_jpeg=disabled",
            "-Dvnc_sasl=disabled",
            "-Dvnc=disabled",
            "-Dvpc=disabled",
            "-Dvte=disabled",
            "-Dvvfat=disabled",
            "-Dwerror=true",
            "-Dwhpx=disabled",
            "-Dxen_pci_passthrough=disabled",
            "-Dxen=disabled",
            "-Dxkbcommon=disabled",
            "-Dzstd=disabled",
            f"-Dprefix={self.dest / 'release'}",
            "--native-file",
        ]

    def packages(self):
        # Similar to linux, but using static dependencies.
        super().packages();

        includes = [
            self.aosp / "external" / "glib",
            self.aosp / "external" / "glib" / "gmodule",
            self.aosp / "external" / "glib" / "os" / "linux",
            self.aosp / "external" / "glib" / "os" / "linux" / "glib",
            self.aosp / "external" / "glib" / "os" / "linux" / "gmodule",
            "${libdir}",
        ]
        # Next we have our dependencies.
        return [
            LibInfo("//external/dtc:libfdt", "1.6.0", {}),
            LibInfo("@glib//:gmodule-static", "2.77.2", {}),
            LibInfo("@glib//:glib-static", "2.77.2",
                {
                    "name": "glib-2.0",
                    "includes": [str(x) for x in includes],
                    "link_flags": "-pthread",
                    "Requires": "pcre2, gmodule-static",
                },
                    ),
            LibInfo("@zlib//:zlib", "1.2.10", {}),
            LibInfo("@pixman//:pixman-1", "0.42.3", {"Requires": "pixman_simd"}),
            LibInfo("@pixman//:pixman_simd", "0.42.3", {}),
            LibInfo("@pcre2//:pcre2", "10.42", {}),
        ]

